Repository red-hat-storage/odf-console, pull requests merged in 2021-09, with the labels that each got.

#24 Update dynamic-plugin-sdk version to beta
  package.json
  src/components/odf-dashboard/activity-card/activity-card.tsx
  src/components/odf-dashboard/dashboard.tsx
  src/components/odf-dashboard/object-storage-card/capacity-card.tsx
  src/components/odf-dashboard/performance-card/performance-card.tsx
  src/components/odf-dashboard/status-card/status-card.tsx
  src/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: approved

#27 Bug 2001970: Openshift Data Foundation navitem missing under "Storage" navsection
  console-extensions.json
  package.json
  src/features.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#29 Bug 2001539: ODF Overview showing two different status for the same storage system
  src/components/odf-dashboard/queries.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#25 Incorporate Cypress support
  cypress/.eslintrc.js
  cypress/cypress.json
  cypress/plugin.js
  cypress/reporter-config.json
  package.json
  yarn.lock
Labels: approved, lgtm

#28 chore(i18n): update translations
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
Labels: approved, lgtm

#31 Bug 1999050: Fix links to Vendor Dashboard from all cards
  src/components/common/capacity-card/capacity-card.scss
  src/components/common/capacity-card/capacity-card.tsx
  src/components/odf-dashboard/activity-card/activity-card.scss
  src/components/odf-dashboard/object-storage-card/capacity-card.tsx
  src/components/odf-dashboard/performance-card/performance-card.tsx
  src/components/odf-dashboard/status-card/status-card.tsx
  src/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  src/components/utils/common.ts
  src/constants/common.ts
  src/constants/index.ts
  src/types.ts
  src/types/common.ts
  src/types/console-types.ts
  src/types/index.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#32 Bug 2001580: Title "OpenShift Data Foundation" should be used instead of "OpenShift Data Foundation Overview"
  locales/en/plugin__odf-console.json
  src/components/odf-dashboard/dashboard.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#30 Update Cypress webpack and TSC configs
  cypress/plugin.js
  cypress/tsconfig.json
Labels: approved, lgtm

#35 Adds dockerfile for upstream odf bundle
  openshift-ci/bundle.Dockerfile
Labels: approved, lgtm

#34 Updates dockerfile for the CI
  Dockerfile.ci
Labels: approved, lgtm, ok-to-test

#36 Adds Dockerfile for building CI index
  openshift-ci/database/index.db
  openshift-ci/index.Dockerfile
Labels: approved, lgtm

#37 Add Dockerfile for OCS bundle
  openshift-ci/ocsbundle.Dockerfile
Labels: approved, lgtm

#33 Add basic helper methods for Cypress
  cypress/cypress.json
  cypress/support.ts
  cypress/support/consts.ts
  cypress/support/login.ts
  cypress/support/selectors.ts
  cypress/support/views.ts
Labels: approved, lgtm

#38 Add CI entrypoint scripts
  .gitignore
  cypress/cypress.json
  cypress/reporter-config.json
  package.json
  test-prow-e2e.sh
  yarn.lock
Labels: approved, lgtm

#40 Inject ODF CSV image through Prow script
  test-prow-e2e.sh
Labels: approved, lgtm
