Repository red-hat-storage/odf-console, pull requests merged in 2022-05, with the labels that each got.

#200 Custom translation hook for odf shared
  packages/shared/dashboards/utilization-card/utilization-item.tsx
  packages/shared/kebab/kebab.tsx
  packages/shared/utils/Conditions.tsx
  packages/shared/utils/Errors.tsx
  packages/shared/utils/RequestSizeInput.tsx
  packages/shared/utils/link.tsx
Labels: approved, lgtm

#199 Added data-test for DR UI components
  console-extensions.json
  locales/en/plugin__odf-console.json
  packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
  packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
  packages/mco/components/empty-state-page/empty-page.tsx
  packages/mco/components/mco-dashboard/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
  packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
  packages/mco/constants/common.ts
  packages/shared/dashboards/status-card/HealthItem.tsx
  packages/shared/popup/status-popup.tsx
Labels: approved, lgtm

#202 fix kms issue for mcg standalone
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
  packages/odf/components/kms-config/hpcs-config.tsx
  packages/odf/components/kms-config/kms-config.tsx
  packages/odf/components/kms-config/providers.ts
  packages/odf/components/kms-config/vault-config.tsx
Labels: approved, lgtm

#207 Bug 2084041: Fix DetailsCard
  package.json
  packages/ocs/block-pool/BlockPoolDetailsPage.tsx
  packages/ocs/dashboards/block-pool/compression-details-card.tsx
  packages/ocs/dashboards/block-pool/details-card.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/types/lso.ts
  packages/odf/utils/lso.ts
  packages/odf/utils/ocs.ts
  webpack.config.ts
  yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#206 [release-4.10-compatibility] Bug 2082102: Dashboard name is incorrect with OCP 4.11 and ODF 4.10.1
  console-extensions.json
  locales/en/plugin__odf-console.json
  packages/shared/dashboards/status-card/HealthItem.tsx
  packages/shared/dashboards/status-card/states.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#86 Add cypress bucket-class test
  cypress/mocks/bucket-class.ts
  cypress/support/selectors.ts
  cypress/tests/bucket-class-spec.ts
  cypress/views/bc.ts
  cypress/views/common.ts
Labels: approved, lgtm

#216 Update CI configuration
  .github/workflows/frontend-build.yml
  cypress/tests/bucket-class-spec.ts
  cypress/views/bc.ts
  cypress/views/common.ts
Labels: approved, lgtm

#215 The creation of new backing store, directs to a blank page
  packages/odf/components/create-bs/create-bs.tsx
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/components/resource-pages/list-page.tsx
Labels: approved, lgtm

#214 After clicking on Create StorageSystem, it navigates to Storage Systems tab but shows an error message
  packages/odf/components/system-list/odf-system-list.tsx
Labels: approved, lgtm

#217 add events tab and own ref for mcg pages
  locales/en/plugin__odf-console.json
  packages/odf/components/resource-pages/BackingStoreDetailsPage.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/CommonDetails.tsx
  packages/odf/components/resource-pages/NamespaceStoreDetailsPage.tsx
  packages/shared/details-page/DetailsPage.tsx
  packages/shared/details-page/details.scss
  packages/shared/heading/page-heading.scss
  packages/shared/heading/page-heading.tsx
Labels: approved, lgtm

#222 Fix Tabs in OCS Dashboard
  console-extensions.json
  packages/ocs/block-pool/CreateBlockPool.tsx
  packages/ocs/dashboards/ocs-system-dashboard.tsx
  packages/odf/features.ts
  packages/shared/heading/page-heading.scss
  packages/shared/heading/page-heading.tsx
  packages/shared/utils/Tabs.tsx
  packages/shared/utils/tabs.scss
Labels: approved, lgtm

#223 Bucket Class details page doesn't have the complete details in UI
  locales/en/plugin__odf-console.json
  packages/odf/components/bucket-class/modals/edit-backingstore-modal.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/list-page.tsx
Labels: approved, lgtm

#233 Updates Owners file
  OWNERS
  packages/mco/OWNERS
Labels: approved, lgtm

#226 Dropdown with options like `false` are visible while creation of DR Policy
  packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
Labels: approved, lgtm, requires-backport

#240 Fix CI: Pass certs to server
  http-server.sh
Labels: approved, lgtm

#224 Fix Multiple instances of Object Bucket, Object Bucket Claims under storage section
  console-extensions.json
Labels: approved, lgtm

#246 Fix ACM thanos proxy URL
  packages/mco/constants/common.ts
Labels: approved, lgtm

#201 fixes for cypress tests
  cypress/tests/active-health-checks.ts
  cypress/tests/add-capacity.spec.ts
  cypress/tests/list-page.spec.ts
  cypress/tests/multiple-pool.spec.ts
  cypress/tests/namespace-store.spec.ts
  cypress/views/bc.ts
  cypress/views/common.ts
  cypress/views/modals.ts
  cypress/views/pvc.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/shared/kebab/kebab.tsx
Labels: approved, lgtm
