Repository red-hat-storage/odf-console, pull requests merged in 2022-10, with the labels that each got.

#458 yarn: Update dependency tree in yarn.lock
  yarn.lock
Labels: approved, lgtm, ok-to-test

#457 patch pull-secret in openshift-config namespace [CI]
  openshift-ci/odf-catalog-source.yaml
  test-prow-e2e.sh
Labels: approved, lgtm

#450 Build: reduce size: enable production mode and minification for prod.
  .gitignore
  Dockerfile
  Dockerfile.ci
  Dockerfile.mco.ci
  http-server.sh
  package.json
  tsconfig.json
  webpack.config.ts
Labels: approved, lgtm

#465 add translations for 4.12
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
Labels: approved, lgtm

#469 Enable Github CI workflow for release-4.12 branches
  .github/workflows/frontend-build.yml
  package.json
Labels: approved, lgtm

#462 Bug 2107213: add warning to 2way replication about possible data-loss
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/body.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#454 [release-4.11] Fix namespace store tests
  cypress/tests/active-health-checks.ts
  cypress/tests/add-capacity.spec.ts
  cypress/tests/namespace-store.spec.ts
  cypress/views/block-pool.ts
  cypress/views/pvc.ts
  cypress/views/store.ts
  packages/odf/components/create-bs/create-bs.tsx
  packages/odf/components/mcg-endpoints/s3-endpoint-type.tsx
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/shared/dropdown/StaticDropdown.tsx
  packages/shared/kebab/kebab.tsx
  packages/shared/modals/DeleteModal.tsx
Labels: approved, lgtm

#414 Bug 2051563: add popover for MCG clusters to depict no limit.
  packages/shared/dashboards/capacity-card/capacity-card.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#471 Fix provisioned capacity calculation
  cypress/tests/add-capacity.spec.ts
  cypress/tests/namespace-store.spec.ts
Labels: do-not-merge/hold

#482 Update Nginx cache configuration
  default.conf
Labels: approved, lgtm

#485 Allow DR UI for the subsequent failover/relocate actions
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/app-dr-status/dr-status-table.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/reducer.ts
  packages/mco/components/disaster-recovery/app-failover-relocate/subscription-group-selector.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/target-cluster-selector.tsx
  packages/mco/types/common.ts
Labels: approved, lgtm

#427 [release-4.11] Bug 2128994: Custom PVC selector option while applying DRPolicy
  locales/en/plugin__odf-console.json
  packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.scss
  packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
  packages/shared/modals/EditLabelModal.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#428 [release-4.11-compatibility] Bug 2128994: Custom PVC selector option while applying DRPolicy
  locales/en/plugin__odf-console.json
  packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.scss
  packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
  packages/shared/modals/EditLabelModal.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#431 Bug 2022356: Range value is not properly displayed for performance card
  packages/shared/dashboards/line-graph/line-graph.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#470 migrate/enable + fix Vault KMS cypress test cases
  cypress/helpers/vault.ts
  cypress/support/vault-standalone.ts
  cypress/tests/kms-encryption-sc.ts
  cypress/tests/persistent-dashboard-check-spec.ts
  cypress/views/pvc.ts
  cypress/views/storage-class.ts
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
Labels: approved, lgtm

#492 add block pool cypress tests
  cypress/tests/block-pool-create.spec.ts
  cypress/tests/block-pool-delete.spec.ts
  cypress/tests/block-pool-update.spec.ts
  cypress/tests/block-pool.spec.ts
  cypress/tests/multiple-pool.spec.ts
  cypress/views/block-pool.ts
Labels: approved, lgtm

#502 add check for managed clusters status for relocate modal
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/reducer.ts
  packages/mco/components/disaster-recovery/app-failover-relocate/target-cluster-selector.tsx
Labels: approved, lgtm

#493 add number increment input for sync interval
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
Labels: approved, lgtm

#511 Upgrade Cypress to the latest stable version
  .gitignore
  cypress/cypress.config.ts
  cypress/cypress.json
  cypress/support/selectors.ts
  package.json
  yarn.lock
Labels: approved, lgtm

#512 Upgrade TypeScript to the latest stable version
  package.json
  yarn.lock
Labels: approved, lgtm
