Repository red-hat-storage/odf-console, pull requests merged in 2022-02, with the labels that each got.

#105 Wait for created resources to be deleted
  cypress/support/selectors.ts
  cypress/tests/namespace-store.spec.ts
  test-prow-e2e.sh
Labels: approved, lgtm

#89 Update PF react-core
  package.json
  yarn.lock
Labels: approved, lgtm

#74 Improve support for Systems that cannot provide total capacity
  packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  packages/shared/dashboards/capacity-card/capacity-card.tsx
Labels: approved, lgtm

#80 Check for ODF SS list page during installation.
  cypress/support.ts
Labels: approved, lgtm

#110 Change cypress image from docker to quay
  Dockerfile.ci
Labels: approved, lgtm

#106 i18n path update
  locales/en/plugin__odf-console.json
  package.json
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/components/system-list/utils.ts
  packages/odf/constants/common.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/shared/generic/ButtonBar.tsx
  packages/shared/generic/CloseButton.tsx
  packages/shared/generic/FieldLevelHelp.tsx
  packages/shared/generic/ModalTitle.tsx
  packages/shared/models/common.ts
  packages/shared/status/statuses.tsx
  packages/shared/storage/pvc/pvs-available-capacity.tsx
Labels: approved, lgtm, ok-to-test

#94 Migration: Add shared components
  locales/en/plugin__odf-console.json
  packages/odf/components/system-list/odf-system-list.tsx
  packages/shared/badges/Badge.scss
  packages/shared/badges/DevPreviewBadge.tsx
  packages/shared/badges/TechPreviewBadge.tsx
  packages/shared/badges/advanced-subscription.tsx
  packages/shared/constants/common.ts
  packages/shared/dropdown/ResourceDropdown.tsx
  packages/shared/dropdown/multiselectdropdown.tsx
  packages/shared/dropdown/resourceDropdown.scss
  packages/shared/dropdown/singleselectdropdown.tsx
  packages/shared/generic/Error.tsx
  packages/shared/generic/ModalTitle.tsx
  packages/shared/generic/promise-component.tsx
  packages/shared/generic/status-box.tsx
  packages/shared/hooks/deep-compare-memoize.ts
  packages/shared/hooks/history.ts
  packages/shared/hooks/k8s-get-hook.ts
  packages/shared/hooks/select-list.ts
  packages/shared/hooks/sort-list.ts
  packages/shared/models/common.ts
  packages/shared/models/console-models.ts
  packages/shared/models/index.ts
  packages/shared/selectors/k8s.ts
  packages/shared/types/common.ts
  packages/shared/types/console-types.ts
  packages/shared/types/index.ts
  packages/shared/types/k8s.ts
  packages/shared/types/storage.ts
  packages/shared/utils/common.ts
  packages/shared/utils/error/custom-error.ts
  packages/shared/utils/error/http-error.ts
  packages/shared/utils/humanize.js
  packages/shared/utils/index.ts
Labels: approved, lgtm

#113 (fix) Show OCS subcomponent health issue in UI
  locales/en/plugin__odf-console.json
  packages/ocs/hooks/index.ts
  packages/ocs/hooks/useOcsHealth.ts
  packages/ocs/models/core.ts
  packages/ocs/models/index.ts
  packages/ocs/queries/index.ts
  packages/ocs/queries/object-storage.ts
  packages/ocs/utils/ceph-health.ts
  packages/ocs/utils/index.ts
  packages/ocs/utils/noobaa-health.ts
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/status-card/storage-system-popup.scss
  packages/odf/components/odf-dashboard/status-card/storage-system-popup.tsx
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  packages/odf/components/utils/common.ts
  packages/shared/popup/status-popup.scss
  packages/shared/popup/status-popup.tsx
  packages/shared/utils/index.ts
  packages/shared/utils/metrics.ts
Labels: approved, lgtm

#117 [release-4.10] Bug 2022693: Add subcomponent status in the ODF Overview dahsboard
  locales/en/plugin__odf-console.json
  packages/ocs/hooks/index.ts
  packages/ocs/hooks/useOcsHealth.ts
  packages/ocs/models/core.ts
  packages/ocs/models/index.ts
  packages/ocs/queries/index.ts
  packages/ocs/queries/object-storage.ts
  packages/ocs/utils/ceph-health.ts
  packages/ocs/utils/index.ts
  packages/ocs/utils/noobaa-health.ts
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/status-card/storage-system-popup.scss
  packages/odf/components/odf-dashboard/status-card/storage-system-popup.tsx
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  packages/odf/components/utils/common.ts
  packages/shared/dashboards/status-card/HealthItem.tsx
  packages/shared/dashboards/status-card/states.tsx
  packages/shared/popup/status-popup.scss
  packages/shared/popup/status-popup.tsx
  packages/shared/status/SecondaryStatus.tsx
  packages/shared/status/icons.tsx
  packages/shared/utils/index.ts
  packages/shared/utils/metrics.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#118 [release-4.10-compatibility] Bug 2022693: Add subcomponent status in the ODF Overview dahsboard
  locales/en/plugin__odf-console.json
  packages/ocs/hooks/index.ts
  packages/ocs/hooks/useOcsHealth.ts
  packages/ocs/models/core.ts
  packages/ocs/models/index.ts
  packages/ocs/queries/index.ts
  packages/ocs/queries/object-storage.ts
  packages/ocs/utils/ceph-health.ts
  packages/ocs/utils/index.ts
  packages/ocs/utils/noobaa-health.ts
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/status-card/storage-system-popup.scss
  packages/odf/components/odf-dashboard/status-card/storage-system-popup.tsx
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  packages/odf/components/utils/common.ts
  packages/shared/dashboards/status-card/HealthItem.tsx
  packages/shared/dashboards/status-card/states.tsx
  packages/shared/popup/status-popup.scss
  packages/shared/popup/status-popup.tsx
  packages/shared/status/SecondaryStatus.tsx
  packages/shared/status/icons.tsx
  packages/shared/utils/index.ts
  packages/shared/utils/metrics.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#119 Update VSCode settings
  .vscode/settings.json
Labels: approved, lgtm

#112 Bug 2036194: Rename name to Data Foundation
  console-extensions.json
  cypress/support.ts
  cypress/views/odf-common.ts
  packages/odf/components/odf-dashboard/dashboard.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#121 Add multiple pool test
  cypress/tests/multiple-pool.spec.ts
  cypress/views/block-pool.ts
Labels: approved, lgtm

#95 Migration: Add constants, types and models
  locales/en/plugin__odf-console.json
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/constants/common.ts
  packages/odf/constants/index.ts
  packages/odf/constants/kms.ts
  packages/odf/constants/lso.ts
  packages/odf/constants/network.ts
  packages/odf/constants/tooltips.tsx
  packages/odf/features.ts
  packages/odf/models/index.ts
  packages/odf/models/lso.ts
  packages/odf/models/network.ts
  packages/odf/models/ocs.ts
  packages/odf/types/common.ts
  packages/odf/types/external-storage.ts
  packages/odf/types/index.ts
  packages/odf/types/kms.ts
  packages/odf/types/lso.ts
  packages/odf/types/network.ts
  packages/shared/types/k8s.ts
Labels: approved, lgtm

#98 Basic Modal utilities for ODF Console
  locales/en/plugin__odf-console.json
  packages/shared/dashboards/status-card/HealthItem.tsx
  packages/shared/dashboards/status-card/states.tsx
  packages/shared/kebab/kebab.tsx
  packages/shared/modals/DeleteModal.tsx
  packages/shared/modals/Modal.tsx
  packages/shared/modals/modal.scss
  packages/shared/modals/modalLauncher.tsx
  packages/shared/utils/common.ts
Labels: approved, lgtm

#123 Bug 2036194:[release-4.10] Rename to Data Foundation in nav item
  console-extensions.json
  cypress/views/odf-common.ts
  packages/odf/components/odf-dashboard/dashboard.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low
