Repository red-hat-storage/odf-console, pull requests merged in 2022-09, with the labels that each got.

#392 Fix packages import path
  packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
  packages/odf/components/namespace-store/namespace-store-form.tsx
Labels: approved, lgtm, ok-to-test

#389 Integration with Thales enterprise key management
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/index.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/kms-config/hpcs-config.tsx
  packages/odf/components/kms-config/kms-config.tsx
  packages/odf/components/kms-config/name-address-port.tsx
  packages/odf/components/kms-config/thales-config.tsx
  packages/odf/components/kms-config/utils.tsx
  packages/odf/components/kms-config/vault-config.tsx
  packages/odf/constants/kms.ts
  packages/odf/modals/advanced-kms-modal/advanced-ibm-kms-modal.tsx
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
  packages/odf/types/kms.ts
  packages/shared/utils/common.ts
Labels: approved, lgtm

#390 Application wise data policies status
  locales/en/plugin__odf-console.json
  packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.scss
  packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
  packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.scss
  packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
  packages/mco/components/data-policies/data-policies-list/data-policies-list.tsx
  packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
  packages/mco/components/disaster-recovery/application-dr-status/dr-status-table.scss
  packages/mco/components/disaster-recovery/application-dr-status/dr-status-table.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.scss
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/reducer.ts
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.scss
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/selected-cluster-view.tsx
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/application-selector.scss
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/application-selector.tsx
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/apply-policy-modal.scss
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/apply-policy-modal.tsx
  packages/mco/components/disaster-recovery/drpolicy-actions/policy-actions.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/application-status.scss
  packages/mco/components/disaster-recovery/drpolicy-list-page/application-status.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.scss
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/types/common.ts
  packages/mco/utils/disaster-recovery.ts
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#388 Migrates Project dashboard Inventory Item status mapper for OBC
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#353 Bug 2104492: Fix the capacity queries
  packages/ocs/queries/ceph-storage.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#315 Bug 2038873: Fix wrong encryption message for block and file storage
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#395 Bug 2044157: Use correct caps for names in external mode deployment
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-external/details-card.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#397 Updates dynamic plugin sdk
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#398 Migrates Storage Class provisioner
  .prettierignore
  locales/en/plugin__odf-console.json
  packages/ocs/constants/common.ts
  packages/ocs/modals/block-pool/create-block-pool-modal.scss
  packages/ocs/modals/block-pool/create-block-pool-modal.tsx
  packages/ocs/storage-class/provisioners.ts
  packages/ocs/storage-class/sc-form.scss
  packages/ocs/storage-class/sc-form.tsx
  packages/ocs/storage-class/thick-provisioner.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#393 Fix cluster claim issue
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/reducer.ts
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
Labels: approved, lgtm

#402 Thales integration with StorageClass flow
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/components/kms-config/vault-config.tsx
Labels: approved, lgtm

#399 Migrates alert actions
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#400 Target cluster tooltip for application DR status
  locales/en/plugin__odf-console.json
  packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
  packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
  packages/mco/components/disaster-recovery/app-dr-status/dr-status-card.tsx
  packages/mco/components/disaster-recovery/app-dr-status/dr-status-table.scss
  packages/mco/components/disaster-recovery/app-dr-status/dr-status-table.tsx
  packages/mco/types/common.ts
Labels: approved, lgtm

#347 DR Failover/Relocate action
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/app-failover-relocate/dr-policy-selector.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.scss
  packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/reducer.ts
  packages/mco/components/disaster-recovery/app-failover-relocate/subscription-group-selector.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/target-cluster-selector.tsx
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/apply-policy-modal.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/application-status.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/models/common.ts
  packages/mco/types/common.ts
  packages/mco/utils/disaster-recovery.ts
  packages/shared/details-page/datetime.ts
  packages/shared/utils/common.ts
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#401 Bug 2118683: [release-4.11] Pass certs to http-server.sh
  Dockerfile.ci
  http-server.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#406 Bug 2118683: Fix typo in private key name
  Dockerfile.ci
Labels: bugzilla/severity-medium, bugzilla/invalid-bug

#403 Migrate CSV Actions
  packages/odf/components/actions/csv-actions.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/shared/utils/storage.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#404 Bug 2114831: fix edit BucketClass modal action
  packages/odf/components/resource-pages/list-page.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#407 Bug 2123193: undefined check for infrastructure + shared utility method
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/shared/selectors/k8s.ts
  packages/shared/utils/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#409 Bug fix on failover and relocate modal
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/app-dr-status/dr-status-table.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/subscription-group-selector.tsx
  packages/mco/utils/disaster-recovery.ts
Labels: approved, lgtm

#396 Bug 2115037: Text correction in DR policy creation
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#411 update Thales address validation
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
  packages/odf/components/kms-config/name-address-port.tsx
  packages/odf/components/kms-config/thales-config.tsx
  packages/odf/components/kms-config/utils.tsx
  packages/odf/components/kms-config/vault-config.tsx
  packages/shared/utils/common.ts
Labels: approved, lgtm

#412 Bug 2120104: Create MirrorPeer only if DRPolicy succeeds
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#415 Bug 2126694: add filter for kms connection details
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/constants/kms.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#413 Bug 2127098: A check for ODF operator version to its corresponding ODF-MCO operator version
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/reducer.ts
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
  packages/mco/constants/dr-policy.ts
  packages/mco/utils/disaster-recovery.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
  packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
  packages/shared/hooks/use-fetch-csv.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#419 Bug 2128074: Fix last sync time for DR
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/app-dr-status/dr-status-table.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/target-cluster-selector.tsx
  packages/mco/types/common.ts
  packages/shared/details-page/datetime.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#408 Bug 2109140: fix multiple OB/OBC tabs for non-admin user
  plugins/odf/console-extensions.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#416 Bug 2126604: change name for Thales provider
  packages/odf/components/kms-config/kms-config.tsx
  packages/odf/constants/kms.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#410 Bug 2043572: adding random characters if secret exists with same name during nss creation
  packages/odf/components/namespace-store/namespace-store-form.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#422 Bug 2128506: Fix application tree selection issue
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/application-selector.tsx
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/apply-policy-modal.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#424 Bug 2124834: Fixes caching issues by adding Expires and Cache-Control headers
  default.conf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#405 Bug 2061428: add validations to KMS connection name input
  locales/en/plugin__odf-console.json
  packages/odf/components/kms-config/hpcs-config.tsx
  packages/odf/components/kms-config/name-address-port.tsx
  packages/odf/components/kms-config/thales-config.tsx
  packages/odf/components/kms-config/utils.tsx
  packages/odf/constants/kms.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#421 Bug 2125356: Custom PVC selector option while applying DRPolicy
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/apply-policy-modal.scss
  packages/mco/components/disaster-recovery/drpolicy-actions/apply-policy/apply-policy-modal.tsx
  packages/shared/modals/EditLabelModal.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#262 add memsource translation scripts
  i18n-scripts/README.md
  i18n-scripts/common.js
  i18n-scripts/export-pos.sh
  i18n-scripts/i18n-to-po.js
  i18n-scripts/languages.sh
  i18n-scripts/memsource-download.sh
  i18n-scripts/memsource-upload.sh
  i18n-scripts/po-to-i18n.js
  package.json
  yarn.lock
Labels: approved, lgtm

#352 Fix Utilization card queries
  packages/ocs/queries/ceph-storage.ts
Labels: approved, lgtm

#423 Bug 2128572: Added application namepace on connected application modal
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-list-page/application-status.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#432 Supress known warnings in compilation process
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#433 Updates ts-loader to remove webpack deprecation warning
  package.json
  yarn.lock
Labels: approved, lgtm

#434 Improves build time by 2x
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#438 Bug 2130465: fix delete modal routing
  packages/shared/modals/DeleteModal.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#417 Bug 2114504: flip menu vertically when it reaches the boundary
  packages/shared/kebab/kebab.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#442 Bug 2110866: store enterprise namespace to configmap
  packages/odf/components/kms-config/utils.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#440 Adds bundle analyzer
  .github/workflows/frontend-build.yml
  .prettierignore
  analyzeTest.ts
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#443 Update staged linter
  .husky/.gitignore
  .husky/pre-commit
  package.json
Labels: approved, lgtm

#435 UI dev. deps: replace deprecated node-sass with dart-sass
  .github/workflows/frontend-build.yml
  .nvmrc
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#436 Bug 2118683: [release-4.11] Fix PVC tests
  cypress/tests/expand-pvc.spec.ts
  cypress/views/pvc.ts
Labels: bugzilla/severity-medium, bugzilla/valid-bug

#439 Bug 2118683: [release-4.11-compatibility] Fix PVCs tests
  cypress/tests/expand-pvc.spec.ts
  cypress/views/pvc.ts
Labels: bugzilla/severity-medium, bugzilla/valid-bug

#430 update test cases to run with ODF version 4.12 - CI
  cypress/support.ts
  cypress/support/selectors.ts
  cypress/tests/create-backing-store.spec.ts
  cypress/tests/multiple-pool.spec.ts
  cypress/tests/multiple-storageclass-selection.spec.ts
  cypress/tests/namespace-store.spec.ts
  cypress/tests/obc-test.spec.ts
  cypress/tests/object-service-dashboards.spec.ts
  cypress/views/bc.ts
  cypress/views/multiple-storageclass.ts
  cypress/views/obcPage.ts
  cypress/views/pvc.ts
  cypress/views/store.ts
  openshift-ci/odf-catalog-source.yaml
  packages/odf/components/create-bs/create-bs.tsx
  packages/odf/components/mcg-endpoints/s3-endpoint-type.tsx
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/modals/attach-deployment/attach-deployment-obc-modal.tsx
  packages/shared/dropdown/StaticDropdown.tsx
  packages/shared/kebab/kebab.tsx
  packages/shared/modals/DeleteModal.tsx
  packages/shared/utils/Tabs.tsx
Labels: approved, lgtm

#451 Add config file path to eslint package.json
  package.json
Labels: approved, lgtm
