Repository red-hat-storage/odf-console, pull requests merged in 2022-06, with the labels that each got.

#237 Add yaml and events tab for ObjectBucketClaim page
  packages/odf/components/mcg/ObjectBucketClaim.tsx
Labels: approved, lgtm

#225 Rephrase ODF minimum supported error message
  locales/en/plugin__odf-console.json
  packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
Labels: approved, lgtm

#239 add attributes to few components
  packages/odf/components/utils/osd-size-dropdown.tsx
  packages/shared/dropdown/ResourceDropdown.tsx
  packages/shared/dropdown/singleselectdropdown.tsx
Labels: approved, lgtm

#250 Bug 2087755: cherry pick #223 onto 4.11 branch
  locales/en/plugin__odf-console.json
  packages/odf/components/bucket-class/modals/edit-backingstore-modal.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/list-page.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#251 Bug 2087755: cherry pick #223 onto 4.11-compat
  locales/en/plugin__odf-console.json
  packages/odf/components/bucket-class/modals/edit-backingstore-modal.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/list-page.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#203 Disable ODF BackingStore, BucketClass, and NamespaceStore tabs and OCS BlockPool tab
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/odf/components/odf-dashboard/dashboard.tsx
Labels: approved, lgtm

#259 prevent duplicate blockpool tabs
  packages/ocs/dashboards/odf-system-dashboard.tsx
Labels: approved, lgtm

#236 Fixing text visibility under Token text-box
  packages/odf/components/kms-config/vault-auth-methods.tsx
  packages/odf/components/kms-config/vault-config.tsx
Labels: approved, lgtm

#270 Add yaml and events page for ObjectBuckets
  packages/odf/components/mcg/ObjectBucket.tsx
Labels: approved, lgtm

#221 Migrate persistent dashboard test to ODF
  cypress/tests/persistent-dashboard-check-spec.ts
Labels: approved, lgtm, test

#125 Add object-service-dashboard test
  cypress/tests/object-service-dashboards.spec.ts
Labels: approved, lgtm, test

#274 Fix uploding JSON data for external cluster connection strict checking issue
  packages/odf/components/utils/common.ts
Labels: approved, lgtm

#265 allow resource dropdown to select storageclass in dropdown
  packages/shared/dropdown/ResourceDropdown.tsx
Labels: approved, lgtm

#266 Fix css issue with OBC claim details page
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/shared/heading/page-heading.scss
  packages/shared/heading/page-heading.tsx
  packages/shared/style.scss
  packages/shared/styles/_actions.scss
  packages/shared/styles/_alerts.scss
  packages/shared/styles/_common.scss
  packages/shared/styles/_copy-to-clipboard.scss
  packages/shared/styles/_resource.scss
  packages/shared/styles/_vars.scss
  packages/shared/utils/copy-to-clipboard.tsx
Labels: approved, lgtm

#260 Bug 2096513: [release-4.11] prevent duplicate blockpool tabs
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/odf/components/odf-dashboard/dashboard.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#261 Bug 2096513: [release-4.11-compatibility] prevent duplicate blockpool tabs
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/odf/components/odf-dashboard/dashboard.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#88 Add backing-store cypress test to odf-console
  cypress/tests/create-backing-store.spec.ts
  cypress/views/store.ts
Labels: approved, lgtm, test

#198 Remove NooBaa Management UI link
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
Labels: approved, lgtm

#255 Fix missing attach to deployment option for obc
  packages/odf/components/mcg/ObjectBucketClaim.tsx
Labels: approved, lgtm

#282 Fix Dashboard crashes in ODF
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/odf/components/odf-dashboard/dashboard.tsx
Labels: approved, lgtm

#284 fix: Description under storage class drop down missing in obc creation page
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
Labels: approved, lgtm

#252 Fix Authorization Header leak
  package.json
  yarn.lock
Labels: approved, lgtm, do-not-merge/hold

#269 Fix Forge security issue
  package.json
  yarn.lock
Labels: approved, lgtm

#291 Bug 2097287: Dropdown doesn't close on it's own after arbiter zone se…
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/stretch-cluster.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#288 add translations for 4.11
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
Labels: approved, lgtm

#294 added the description for StorageClass dropdown in Add Capacity modal
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/utils/odf.ts
Labels: approved, lgtm

#277 Managed ODF not getting detected
  packages/odf/features.ts
Labels: approved, lgtm

#258 Bug 2091638: add yaml tab to blockpool
  packages/ocs/block-pool/BlockPoolDetailsPage.tsx
  packages/odf/components/mcg/ObjectBucket.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/components/resource-pages/BackingStoreDetailsPage.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/CommonDetails.tsx
  packages/odf/components/resource-pages/NamespaceStoreDetailsPage.tsx
  packages/shared/utils/Tabs.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#122 Add cypress obc-test migration
  cypress/mocks/deploymentData.ts
  cypress/mocks/storageclass.ts
  cypress/support/pages/app.ts
  cypress/tests/obc-test.spec.ts
  cypress/views/details-page.ts
  cypress/views/list-page.ts
  cypress/views/obcPage.ts
  package.json
Labels: approved, lgtm, test

#314 Bug 2096509: [release-4.11-compatibility] add attributes to few components
  packages/odf/components/utils/osd-size-dropdown.tsx
  packages/shared/dropdown/ResourceDropdown.tsx
  packages/shared/dropdown/singleselectdropdown.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#317 Bug 2069607: Fixes node forge CVE
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#318 fix: compression status for cephblockpool
  packages/ocs/block-pool/BlockPoolListPage.tsx
  packages/ocs/dashboards/block-pool/compression-details-card.tsx
Labels: approved, lgtm

#304 Bug 2098261: Remove BlockPools tab in external mode
  packages/ocs/dashboards/odf-system-dashboard.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#319 Redirect to OCS dashboards without clicking "Overview"
  console-extensions.json
  packages/odf/components/utils/common.ts
  packages/shared/utils/dashboard.ts
Labels: approved, lgtm

#283 Block pool list page showing empty option on kebab action menu
  locales/en/plugin__odf-console.json
  packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
  packages/ocs/block-pool/BlockPoolDetailsPage.tsx
  packages/ocs/block-pool/BlockPoolListPage.tsx
  packages/ocs/block-pool/body.scss
  packages/ocs/block-pool/body.tsx
  packages/ocs/utils/block-pool.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/list-page.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/constants/mcg.ts
  packages/shared/kebab/kebab.tsx
Labels: approved, lgtm

#316 wizard page going blank for KMS
  packages/odf/components/kms-config/vault-config.tsx
Labels: approved, lgtm

#169 [release-4.10-compatibility] Bug 2074518: Use List Page exposed components and fix Kubevirt imports
  locales/en/plugin__odf-console.json
  package.json
  packages/ocs/hooks/useOcsHealth.ts
  packages/odf/components/odf-dashboard/dashboard.tsx
  packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
  packages/odf/components/odf-dashboard/performance-card/performance-card.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/components/system-list/system-link.tsx
  packages/odf/components/system-list/utils.ts
  packages/odf/modals/add-capacity/add-capacity-modal.scss
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/modals/add-capacity/pvs-available-capacity.scss
  packages/odf/modals/add-capacity/pvs-available-capacity.tsx
  packages/odf/utils/index.ts
  packages/odf/utils/ocs.ts
  packages/odf/utils/storage.ts
  packages/shared/dashboards/status-card/HealthItem.tsx
  packages/shared/hooks/k8s-get-hook.ts
  packages/shared/kebab/kebab.tsx
  packages/shared/modals/DeleteModal.tsx
  packages/shared/modals/EditAnnotations.tsx
  packages/shared/modals/EditLabelModal.tsx
  packages/shared/modals/Modal.tsx
  packages/shared/modals/Selector.tsx
  packages/shared/modals/common.ts
  packages/shared/modals/modal.scss
  packages/shared/modals/modalLauncher.tsx
  packages/shared/modals/selector-requirement.ts
  packages/shared/models/common.ts
  packages/shared/resource-link/resource-link.tsx
  packages/shared/selectors/k8s.ts
  packages/shared/status/GenericStatus.tsx
  packages/shared/status/PopoverStatus.tsx
  packages/shared/status/Status.tsx
  packages/shared/status/statuses.tsx
  packages/shared/types/index.ts
  packages/shared/utils/AsyncLoader.tsx
  packages/shared/utils/NameValueEditor.tsx
  packages/shared/utils/ResourceDropdown.tsx
  packages/shared/utils/common.ts
  yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#332 [release-4.10-compatibility] Bug 2074518: fix dashboard based on usePrometheusPoll response
  packages/ocs/hooks/useOcsHealth.ts
  packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
  packages/odf/components/odf-dashboard/performance-card/performance-card.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#220 Migrate multiple storage class selection to odf
  cypress/mocks/ksm.ts
  cypress/mocks/storageclass.ts
  cypress/tests/multiple-storageclass-selection.spec.ts
  cypress/views/multiple-storageclass.ts
  cypress/views/yaml-editor.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/shared/kebab/kebab.tsx
Labels: approved, lgtm, test
