Repository red-hat-storage/odf-console, pull requests merged in 2022-08, with the labels that each got.

#355 Data Foundation tab should not be blocked on StorageCluster presence
  console-extensions.json
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
Labels: approved, lgtm

#354 show vault namespace option for cluster-wide (SA auth)
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
Labels: approved, lgtm

#210 Bug 2097772: Visual feedback on OBC deletion
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/BlockPoolListPage.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/shared/kebab/kebab.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#351 Fix Overview tab is present under Storage section
  .gitignore
  Dockerfile
  Dockerfile.ci
  Dockerfile.mco.ci
  Dockerfile.prod
  package.json
  packages/odf/features.ts
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
  scripts/generatePluginPackage.ts
  webpack.config.ts
Labels: approved, lgtm

#350 Bug 2091967: add description to storageclass dropdown
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/utils/odf.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#361 Bug 2103975: Add admin flag (for hiding Data Foundation navItem from non-admin users)
  packages/odf/features.ts
  plugins/odf/console-extensions.json
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#385 Bug 2112698: Add listen directives for IPv6 stack
  default.conf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#382 [release-4.10-compatibility] Bug 2116263: Add admin flag (for hiding Data Foundation navItem from non-admin users)
  console-extensions.json
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/features.ts
  packages/shared/constants/common.ts
  packages/shared/models/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#383 [release-4.10] Bug 2116263: Add admin flag (for hiding Data Foundation navItem from non-admin users)
  console-extensions.json
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/features.ts
  packages/shared/constants/common.ts
  packages/shared/models/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#384 [release-4.9-compatibility] Bug 2116264: Add admin flag (for hiding Data Foundation navItem from non-admin users)
  console-extensions.json
  src/constants/common.ts
  src/features.ts
  src/types/console-types.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#386 [release-4.9] Bug 2116264: Add admin flag (for hiding Data Foundation navItem from non-admin users)
  console-extensions.json
  src/constants/common.ts
  src/features.ts
  src/types/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#380 [release-4.11] Bug 2116262: Add admin flag (for hiding Data Foundation navItem from non-admin users)
  packages/odf/features.ts
  packages/shared/models/common.ts
  plugins/odf/console-extensions.json
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#381 [release-4.11-compatibility] Bug 2116262: Add admin flag (for hiding Data Foundation navItem from non-admin users)
  packages/odf/features.ts
  packages/shared/models/common.ts
  plugins/odf/console-extensions.json
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#364 Bug 2118683: [release-4.11] fix cypress issues for 4.11
  cypress/mocks/bucket-class.ts
  cypress/tests/active-health-checks.ts
  cypress/tests/add-capacity.spec.ts
  cypress/tests/list-page.spec.ts
  cypress/tests/namespace-store.spec.ts
  cypress/views/bc.ts
  cypress/views/common.ts
  cypress/views/modals.ts
  cypress/views/pvc.ts
  openshift-ci/odf-catalog-source.yaml
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/shared/kebab/kebab.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#375 Migrate Health Resource extension for cluster dashboard
  locales/en/plugin__odf-console.json
  packages/odf/components/cluster-overview-extensions/HealthOverview.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#376 Migrate Cluster Expansion activity extension
  packages/odf/components/cluster-overview-extensions/ClusterExpansion.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#373 Migrates Attach Storage Provider extension
  locales/en/plugin__odf-console.json
  packages/odf/components/attach-obc/AttachOBC.scss
  packages/odf/components/attach-obc/AttachOBC.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#391 Using clusterclaims for odf related information
  packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/data-policies/create-dr-policy/reducer.ts
  packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/data-policies/create-dr-policy/select-replication-type.tsx
  packages/mco/components/data-policies/create-dr-policy/selected-cluster-view.tsx
  packages/mco/constants/dr-policy.ts
Labels: approved, lgtm
