Repository red-hat-storage/odf-console, pull requests merged in 2023-05, with the labels that each got.

#823 [RDR] Dashbaord font size fix
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.scss
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.scss
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/mco-dashboard/data-policy/status-card/status-card.scss
  packages/mco/components/mco-dashboard/data-policy/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.scss
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/mco-dashboard/mco-dashboard.scss
Labels: approved, lgtm

#831 Topology: Node Details: fix error when providerID is undefined
  packages/shared/topology/sidebar/node/NodeDetails.tsx
  packages/shared/types/k8s.ts
  packages/shared/utils/node.spec.ts
  packages/shared/utils/node.ts
Labels: approved, lgtm

#842 Fix for the issue DRPolicy doesn't show connected application
  packages/mco/hooks/applications-hook.ts
Labels: approved, lgtm

#839 ESLint: enable rule: @typescript-eslint/no-shadow
  .eslintrc.js
  cypress/views/block-pool.ts
  packages/ibm/system-connection-details.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/dr-policy-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/subscription-group-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/target-cluster-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/ocs/block-pool/CreateBlockPool.tsx
  packages/ocs/block-pool/body.tsx
  packages/odf/components/bucket-class/wizard-pages/general-page.tsx
  packages/odf/components/create-bs/create-bs.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-storage-class-step/create-storage-class-step.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/ObjectBucket.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/components/mcg/useObcNameSchema.ts
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/components/topology/TopBar/TopologySearch.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/utils/common.ts
  packages/odf/components/utils/osd-size-dropdown.tsx
  packages/odf/features.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/modals/attach-deployment/attach-deployment-obc-modal.tsx
  packages/shared/details-page/datetime.ts
  packages/shared/input-with-requirements/TextInputWithFieldRequirements.tsx
  packages/shared/kebab/kebab.tsx
  packages/shared/modals/DeleteModal.tsx
  packages/shared/modals/modalLauncher.tsx
  packages/shared/yaml-editor/YAMLEditor.tsx
Labels: approved, lgtm

#854 revert ODF version to 4.13 (CI)
  Dockerfile.ci
  openshift-ci/odf-catalog-source.yaml
Labels: approved, lgtm

#848 Fixes Multus filtering issue
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/security-and-network-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/shared/dropdown/ResourceDropdown.tsx
Labels: approved, lgtm

#855 Fixes test issues
  cypress/consts.ts
  cypress/support.ts
Labels: approved, lgtm

#852 fix status card for nfs
  packages/ocs/dashboards/network-file-system/status-card/status-card.tsx
  packages/ocs/queries/nfs.ts
  packages/shared/types/k8s.ts
  packages/shared/utils/index.ts
  packages/shared/utils/pod-health.ts
Labels: approved, lgtm

#851 fix replica calculation for cluster capacity expansion
  packages/ocs/dashboards/persistent-internal/inventory-card.tsx
  packages/ocs/utils/common.ts
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
  packages/odf/components/utils/common.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
Labels: approved, lgtm

#861 Fix cant initiate failover of applicationSet based apps after hub recovery
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/utils/acm.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#849 Placement support for subscription
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-popover.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/dr-policy-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/peer-cluster-status.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/subscription-group-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/target-cluster-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/application-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/mco/hooks/applications-hook.ts
  packages/mco/hooks/mco-resources.ts
  packages/mco/types/acm.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#859 Fixes storageCluster status when Alerts are firing
  packages/ocs/dashboards/object-service/status-card/status-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/utils/metrics.ts
  packages/shared/models/common.ts
  packages/shared/topology/factory/StyleGroup.tsx
  packages/shared/topology/utils/AlertFilters.ts
  packages/shared/topology/utils/Monitoring.tsx
  packages/shared/utils/AlertFilters.ts
  packages/shared/utils/index.ts
Labels: approved, lgtm

#868 Bug 2196236: [release-4.13]Placement support for subscription
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-popover.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/dr-policy-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/peer-cluster-status.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/subscription-group-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/target-cluster-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/application-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/mco/hooks/applications-hook.ts
  packages/mco/hooks/mco-resources.ts
  packages/mco/types/acm.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm, jira/valid-bug

#867 Bug 2209288: [release-4.13] Fix cant initiate failover of applicationSet based apps after hub recovery
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/utils/acm.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm, jira/valid-bug

#850 change schema type for pvc-name from string to type PersistenVolumeClaimKind
  packages/odf/constants/providerSchema.ts
Labels: approved, lgtm

#876 [release-4.13-compatibility] Bug 2208962: Fixes storageCluster status when Alerts are firing
  packages/ocs/dashboards/object-service/status-card/status-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/utils/metrics.ts
  packages/shared/models/common.ts
  packages/shared/topology/factory/StyleGroup.tsx
  packages/shared/topology/utils/AlertFilters.ts
  packages/shared/topology/utils/Monitoring.tsx
  packages/shared/utils/AlertFilters.ts
  packages/shared/utils/index.ts
Labels: approved, lgtm, jira/valid-bug

#875 [release-4.13] Bug 2208962: Fixes storageCluster status when Alerts are firing
  packages/ocs/dashboards/object-service/status-card/status-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/utils/metrics.ts
  packages/shared/models/common.ts
  packages/shared/topology/factory/StyleGroup.tsx
  packages/shared/topology/utils/AlertFilters.ts
  packages/shared/topology/utils/Monitoring.tsx
  packages/shared/utils/AlertFilters.ts
  packages/shared/utils/index.ts
Labels: approved, lgtm, jira/valid-bug

#881 Add version info to package.json file
  scripts/generatePluginPackage.mts
Labels: approved, lgtm

#884 Additional fixes for ConsolePlugin version
  package.json
Labels: approved

#840 Bug 2193109: fixed startAndEndsWithAlphanumerics regex
  packages/odf/utils/validation.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#887 Bug 2211334: Remove replication history graph from 4.13
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent
