Repository red-hat-storage/odf-console, pull requests merged in 2023-01, with the labels that each got.

#583 Upgrade node engine version
  .nvmrc
  package.json
Labels: approved, lgtm

#541 Bug 2141095: [RDR] Storage System page on ACM Hub is visible even when data observability is not enabled
  packages/mco/constants/common.ts
  packages/mco/features.ts
  packages/mco/models/acm.ts
  packages/mco/types/acm.ts
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#584 Fix DRPolicy list page access issue for application users
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.scss
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx
Labels: approved, lgtm

#585 Fix failover/relocate modal issue for app users
  packages/mco/models/acm.ts
Labels: approved, lgtm

#588 Bug 2159466: [release-4.12] Fix failover/relocate modal issue for app users
  packages/mco/models/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#582 Bug 2156069: Instances of OCS can be seen on BlockPool action modals
  locales/en/plugin__odf-console.json
  packages/ocs/utils/block-pool.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#572 Edit labels - Error Messages on client validation
  locales/en/plugin__odf-console.json
  packages/shared/generic/FormAlertInline.tsx
  packages/shared/modals/EditAnnotations.tsx
  packages/shared/modals/EditLabelModal.tsx
  packages/shared/modals/Selector.tsx
Labels: approved, lgtm, ok-to-test

#590 Refactor: Package file and plugin generation scripts
  .gitignore
  package.json
  scripts/generatePluginPackage.mts
  scripts/generatePluginPackage.ts
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#562 Move i18n-scripts under scripts
  package.json
  scripts/i18n/README.md
  scripts/i18n/common.js
  scripts/i18n/export-pos.sh
  scripts/i18n/i18n-to-po.js
  scripts/i18n/languages.sh
  scripts/i18n/memsource-download.sh
  scripts/i18n/memsource-upload.sh
  scripts/i18n/po-to-i18n.js
Labels: approved, lgtm

#594 Fix warning in tsconfig.json file
  tsconfig.json
Labels: approved, lgtm

#597 add initial layout for DR dashboard
  packages/mco/components/data-policies/data-policies-page.tsx
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-card.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard-context.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/mco-dashboard/data-policy/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/components/mco-dashboard/storage-system/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/storage-system/system-capacity-card/capacity-card.tsx
  packages/mco/components/mco-dashboard/storage-system/system-dashboard.tsx
  packages/mco/constants/dr-policy.ts
  packages/mco/hooks/argo-application-set.ts
  packages/mco/hooks/disaster-recovery.ts
  packages/mco/hooks/index.ts
  packages/mco/models/acm.ts
  packages/mco/models/argo-cd.ts
  packages/mco/models/index.ts
  packages/mco/types/acm.ts
  packages/mco/types/argo-cd.ts
  packages/mco/types/index.ts
  packages/mco/utils/acm.ts
  packages/mco/utils/common.ts
  packages/mco/utils/disaster-recovery.ts
  packages/mco/utils/index.ts
  packages/shared/style.scss
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#599 Bug 2158922: add pvcName to NSS instead of entire PVC CR
  packages/odf/components/namespace-store/namespace-store-form.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#580 Bug 1989088: Convey proper details for network selection
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#596 Setup a package for ODF extensions
  packages/odf-plugin-sdk/extensions/dashboard.ts
  packages/odf-plugin-sdk/extensions/index.ts
  packages/odf-plugin-sdk/package.json
  packages/odf/components/odf-dashboard/dashboard.tsx
  packages/odf/components/odf-dashboard/utils.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#604 made setErrorMessage prop optional
  packages/shared/modals/Selector.tsx
Labels: approved, lgtm, ok-to-test

#602 use generic names for Data Foundation
  cypress/tests/persistent-dashboard-check-spec.ts
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/ocs/block-pool/CreateBlockPool.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/object-service/storage-efficiency-card/storage-efficiency-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/ocs-upgrade-activity.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/utils/block-pool.tsx
  packages/odf/components/bucket-class/backingstore-table.tsx
  packages/odf/components/bucket-class/wizard-pages/general-page.tsx
  packages/odf/components/cluster-overview-extensions/HealthOverview.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
  packages/odf/components/create-storage-system/header.tsx
  packages/odf/components/resource-pages/BackingStoreDetailsPage.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/NamespaceStoreDetailsPage.tsx
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/constants/tooltips.tsx
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#577 Refactoring failover/relocate modal to support application set
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page-actions.tsx
  packages/mco/components/modals/app-failover-relocate/acm-action-callback.tsx
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/app-failover-relocate/dr-policy-selector.tsx
  packages/mco/components/modals/app-failover-relocate/error-messages.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.scss
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/peer-cluster-status.tsx
  packages/mco/components/modals/app-failover-relocate/reducer.ts
  packages/mco/components/modals/app-failover-relocate/subscription-group-selector.tsx
  packages/mco/components/modals/app-failover-relocate/target-cluster-selector.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/constants/index.ts
  packages/mco/types/acm.ts
  packages/mco/types/ramen.ts
  packages/mco/utils/acm.ts
  packages/mco/utils/common.ts
  packages/mco/utils/disaster-recovery.ts
  packages/mco/utils/doc-utils.tsx
  packages/mco/utils/index.ts
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#579 Apply modal refactoring (Subscriptions to ApplicationSet)
  locales/en/plugin__odf-console.json
  package.json
  packages/mco/components/modals/drpolicy-apps-apply/application-selector.scss
  packages/mco/components/modals/drpolicy-apps-apply/application-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/applicationset-handler.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.scss
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.scss
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx
  packages/mco/components/modals/drpolicy-apps-apply/reducer.ts
  packages/mco/components/modals/drpolicy-apps-apply/utils.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/models/acm.ts
  packages/mco/models/odf-mco.ts
  packages/mco/models/ramen.ts
  packages/mco/types/acm.ts
  packages/mco/utils/disaster-recovery.ts
  packages/shared/generic/custom-dual-list-selector.tsx
  packages/shared/modals/EditLabelModal.tsx
  packages/shared/modals/Selector.tsx
  yarn.lock
Labels: approved, lgtm

#612 Restoring 4.12 subscription UI for backward compatibility
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page-actions.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/modals/app-failover-relocate/acm-action-callback.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/dr-policy-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/error-messages.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.scss
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/peer-cluster-status.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/reducer.ts
  packages/mco/components/modals/app-failover-relocate/subscriptions/subscription-group-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/target-cluster-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/application-selector.scss
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/application-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.scss
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/acm.ts
  packages/mco/utils/doc-utils.tsx
  plugins/mco/console-extensions.json
Labels: approved, lgtm

#603 Adds bucket replication UI for OBC page
  locales/en/plugin__odf-console.json
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/create-obc.scss
  packages/odf/components/mcg/replication-policy-form.tsx
  packages/odf/components/mcg/state.ts
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/types/mcg.ts
  packages/odf/utils/mcg.ts
Labels: approved, lgtm

#607 Input with field requirements
  .eslintrc.js
  package.json
  packages/shared/input-with-requirements/TextInputWithFieldRequirements.scss
  packages/shared/input-with-requirements/TextInputWithFieldRequirements.tsx
  packages/shared/input-with-requirements/useFieldRequirements.spec.ts
  packages/shared/input-with-requirements/useFieldRequirements.ts
  yarn.lock
Labels: approved, lgtm, ok-to-test
