Repository red-hat-storage/odf-console, pull requests merged in 2023-10, with the labels that each got.

#1063 update CI to ODF 4.14 release
  .github/workflows/frontend-build.yml
  openshift-ci/odf-catalog-source.yaml
  test-prow-e2e.sh
Labels: approved, lgtm

#1066 [release-4.14-compatibility] update CI to ODF 4.14 release
  .github/workflows/frontend-build.yml
  openshift-ci/odf-catalog-source.yaml
  test-prow-e2e.sh
Labels: approved

#1065 [release-4.14] update CI to ODF 4.14 release
  .github/workflows/frontend-build.yml
  openshift-ci/odf-catalog-source.yaml
  test-prow-e2e.sh
Labels: approved

#1068 Revert to nodejs 18.17.1
  .github/workflows/frontend-build.yml
Labels: approved, lgtm

#1067 enable OBC test, as CI is now moved to OCP 4.14
  cypress/tests/obc-test.spec.ts
Labels: approved, lgtm

#1060 Update lint rule: no-extraneous-deps
  .eslintrc.js
Labels: approved, lgtm

#1061 Fix tooltips messages in the graphs at DR Policy dashboard
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/constants/dashboard.ts
  packages/shared/src/alert/AlertsPanel.tsx
Labels: approved, lgtm

#1072 Bug 2240756: Fix node details roles display issue under odf-topology
  packages/shared/src/topology/sidebar/node/NodeDetails.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#1074 Bug 2239093: [release-4.14] Fix tooltips messages in the graphs at DR Policy dashboard
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/constants/dashboard.ts
  packages/shared/src/alert/AlertsPanel.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#1079 Bug 2239093: [release-4.14-compatibility] Fix tooltips messages in DR dashboard
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/constants/dashboard.ts
  packages/shared/src/alert/AlertsPanel.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#1080 Syncing latest changes from master for odf-console
  .eslintrc.js
  .github/workflows/frontend-build.yml
  cypress/tests/obc-test.spec.ts
  locales/en/plugin__odf-console.json
  openshift-ci/odf-catalog-source.yaml
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/constants/dashboard.ts
  packages/shared/src/alert/AlertsPanel.tsx
  packages/shared/src/topology/sidebar/node/NodeDetails.tsx
  test-prow-e2e.sh
Labels: approved, lgtm

#832 added unit tests for useObcNameSchema hook
  packages/odf/components/mcg/useObcNameSchema.spec.ts
Labels: approved, lgtm

#1082 Fix mpath filtering issue
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/selected-capacity.tsx
Labels: approved, lgtm

#1086 Unit tests for CreateNamespaceStore & NamespaceStoreForm
  package.json
  packages/odf/components/namespace-store/create-namespace-store.spec.tsx
  packages/odf/components/namespace-store/namespace-store-form.spec.tsx
  yarn.lock
Labels: approved, lgtm

#1062 [release-4.13] Bug 2241179: remove 'Volume type' from BlockPool create/update form
  cypress/views/block-pool.ts
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/body.scss
  packages/ocs/block-pool/body.tsx
  packages/ocs/block-pool/reducer.ts
  packages/ocs/modals/block-pool/update-block-pool-modal.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1090 Removing dead code and minor refactoring for 4.15
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.scss
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.scss
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/components/data-policies/data-policies-page.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.scss
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/drpolicy-list-page/helper.ts
  packages/mco/components/modals/drpolicy-apps-apply/applicationset-handler.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.scss
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.scss
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx
  packages/mco/components/modals/drpolicy-apps-apply/reducer.ts
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/application-selector.scss
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/application-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.scss
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/mco/components/modals/drpolicy-apps-apply/utils.tsx
  packages/mco/utils/acm.ts
  packages/mco/utils/common.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/mco/utils/index.ts
  plugins/mco/console-plugin.json
Labels: approved, lgtm
