Repository red-hat-storage/odf-console, pull requests merged in 2023-08, with the labels that each got.

#948 tests: moved the test file and updated the imports
  packages/shared/src/status/Inventory.spec.tsx
  packages/shared/src/status/icons.spec.tsx
Labels: approved, lgtm

#945 Bug 2219136: Values on graph go out of tile
  packages/ocs/dashboards/block-pool/mirroring-card.scss
  packages/ocs/dashboards/block-pool/utilization-card.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#934 Adding tool tips for RBD snapshot graph title
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
Labels: approved, lgtm

#932 After hub recovery, cant initiate failover
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/acm.ts
  packages/mco/utils/acm.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#943 Remove date from x-axis label of ceph RBD snapshot graph
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/shared/src/dashboards/utilization-card/prometheus-utilization-item.tsx
  packages/shared/src/dashboards/utilization-card/utilization-item.tsx
  packages/shared/src/details-page/datetime.ts
Labels: approved, lgtm

#937 Page loader for DR policy list page and create policy page
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.scss
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/empty-state-page/empty-page.scss
  packages/mco/components/empty-state-page/empty-page.tsx
  packages/mco/constants/acm.ts
  packages/mco/hooks/applications-hook.ts
Labels: approved, lgtm

#962 OB/OBC: fix list filter
  packages/odf/components/mcg/ObjectBucket.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
Labels: approved, lgtm

#951 Fixes filesystem provider details
  locales/en/plugin__odf-console.json
  packages/odf/components/resource-pages/Providers.tsx
Labels: approved, lgtm

#946 fix: added Rack info for the topology details screen
  locales/en/plugin__odf-console.json
  packages/odf/components/topology/utils.ts
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/utils/ocs.ts
  packages/shared/src/constants/common.ts
  packages/shared/src/topology/sidebar/node/NodeDetails.tsx
  packages/shared/src/utils/node.spec.ts
  packages/shared/src/utils/node.ts
Labels: approved, lgtm

#973 add translations for 4.14 release
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
Labels: approved, lgtm

#944 fix: add capacity error message
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
Labels: approved, lgtm

#972 Running OCP console as a container
  README.md
  package.json
  scripts/start-ocp-console.sh
Labels: approved, lgtm

#841 tests: added for camel case wrap
  packages/shared/src/utils/CamelCaseWrap.spec.tsx
Labels: approved, lgtm

#971 Refactors Modal usage
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/helper.ts
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-popover.tsx
  packages/ocs/block-pool/BlockPoolDetailsPage.tsx
  packages/ocs/block-pool/BlockPoolListPage.tsx
  packages/ocs/utils/block-pool.tsx
  packages/odf/components/bucket-class/create-bc.tsx
  packages/odf/components/bucket-class/wizard-pages/backingstore-page.tsx
  packages/odf/components/kms-config/providers.ts
  packages/odf/components/kms-config/vault-config.tsx
  packages/odf/components/mcg/ObjectBucket.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/components/mcg/replication-policy-form.tsx
  packages/odf/components/resource-pages/BackingStoreDetailsPage.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/CommonDetails.tsx
  packages/odf/components/resource-pages/NamespaceStoreDetailsPage.tsx
  packages/odf/components/resource-pages/list-page.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
  packages/shared/package.json
  packages/shared/src/details-page/DetailsPage.tsx
  packages/shared/src/kebab/kebab.tsx
  packages/shared/src/modals/DeleteModal.tsx
  packages/shared/src/modals/index.ts
  packages/shared/src/modals/modalLauncher.tsx
  packages/shared/src/modals/types.tsx
  packages/shared/src/utils/Tabs.tsx
  yarn.lock
Labels: approved, lgtm

#947 Remove link and remove cluster name
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/shared/src/dashboards/utilization-card/prometheus-utilization-item.tsx
  packages/shared/src/dashboards/utilization-card/utilization-item.tsx
Labels: approved, lgtm

#970 Description text change for manage policy modal
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/mco/components/modals/app-manage-policies/helper/select-policy-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/mco/components/modals/app-manage-policies/style.scss
  packages/shared/src/table/selectable-table.tsx
Labels: approved, lgtm

#991 Bug 2233027: Fixes Deployment node map
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/utils.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#982 Fix search issue on list policy view
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
Labels: approved, lgtm

#986 Add initial default sorting for SelectableTable.
  packages/shared/package.json
  packages/shared/src/hooks/sort-list.ts
  packages/shared/src/table/selectable-table.tsx
  yarn.lock
Labels: approved, lgtm

#997 Text "Last on" changed to "Last replicated on" in DR dashboard
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
Labels: approved, lgtm

#996 [Greenfield] Option to prepare ODF cluster for Regional-DR
  cypress/support.ts
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/data-protection-step/data-protection-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/index.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/dataProtection.ts
  packages/odf/constants/index.ts
Labels: approved, lgtm

#1004 Changes the text from SDN to OVN
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.tsx
  packages/odf/constants/network.ts
Labels: approved, lgtm

#1005 Bug 2233505: Fix provider details for NS details page
  locales/en/plugin__odf-console.json
  packages/odf/components/resource-pages/Providers.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#983 Fetching alerts from OCP thanos instead of ACM thanos
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#1011 Fix wrong measurement unit in Receive bandwidth graph
  packages/shared/src/topology/sidebar/deployments/DeploymentObserve.tsx
Labels: approved, lgtm
