Repository red-hat-storage/odf-console, pull requests merged in 2023-02, with the labels that each got.

#617 Refactoring DR hook
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/app-failover-relocate/error-messages.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/error-messages.tsx
  packages/mco/hooks/argo-application-set.ts
  packages/mco/hooks/disaster-recovery.ts
  packages/mco/hooks/index.ts
  packages/mco/hooks/mco-resources.ts
  packages/mco/utils/acm.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/mco/utils/doc-utils.tsx
Labels: approved, lgtm

#624 Bug 2167299: Change version formatting for details card
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/utils/common.ts
  packages/odf/utils/odf.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#605 Bug 2161903: Error message on UI during failover
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/app-failover-relocate/error-messages.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/reducer.ts
  packages/mco/components/disaster-recovery/app-failover-relocate/subscription-group-selector.tsx
  packages/mco/components/disaster-recovery/app-failover-relocate/target-cluster-selector.tsx
  packages/mco/utils/doc-utils.tsx
  packages/mco/utils/index.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#622 Fix input value print over control buttons
  packages/shared/modals/Selector.tsx
  packages/shared/modals/modal.scss
Labels: approved, lgtm

#630 Bug 2167301: [release-4.12-compatibility] Use generics names for Data Foundation
  cypress/tests/persistent-dashboard-check-spec.ts
  cypress/views/block-pool.ts
  locales/en/plugin__odf-console.json
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/ocs/block-pool/CreateBlockPool.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/object-service/storage-efficiency-card/storage-efficiency-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/ocs-upgrade-activity.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/utils/block-pool.tsx
  packages/odf/components/bucket-class/backingstore-table.tsx
  packages/odf/components/bucket-class/wizard-pages/general-page.tsx
  packages/odf/components/cluster-overview-extensions/HealthOverview.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
  packages/odf/components/create-storage-system/header.tsx
  packages/odf/components/resource-pages/BackingStoreDetailsPage.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/NamespaceStoreDetailsPage.tsx
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/constants/tooltips.tsx
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
  plugins/odf/console-plugin.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#613 feat: support key rotation encryption
  packages/odf/components/utils/common.ts
  packages/shared/types/storage.ts
Labels: approved, lgtm

#631 add nfs to the deployment flow
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/enable-nfs.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/shared/types/storage.ts
Labels: approved, lgtm

#633 Bug 2168635: fix redirect link to operator details page
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#591 [release-4.11] Bug 2160445: undefined check for infrastructure + shared utility method
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/shared/selectors/k8s.ts
  packages/shared/utils/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#615 Bug 2161655: [release-4.11] add pvcName to NSS instead of entire PVC CR
  packages/odf/components/namespace-store/namespace-store-form.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#581 Migrating application data policies status popover to ApplicationSet
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/modals/app-data-policies-status/acm-column-callback.tsx
  packages/mco/components/modals/app-data-policies-status/argo-application-set.tsx
  packages/mco/components/modals/app-data-policies-status/dr-status.tsx
  packages/mco/components/modals/app-data-policies-status/status-popover.tsx
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-modal.scss
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-modal.tsx
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-popover.scss
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-popover.tsx
  packages/mco/components/modals/app-data-policies-status/subscriptions/dr-status-card.tsx
  packages/mco/components/modals/app-data-policies-status/subscriptions/dr-status-table.scss
  packages/mco/components/modals/app-data-policies-status/subscriptions/dr-status-table.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/hooks/argo-application-set.ts
  packages/mco/utils/disaster-recovery.tsx
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#625 Bug 2165984: Replication image states shows incorrect colours
  packages/ocs/dashboards/block-pool/mirroring-card.tsx
  packages/ocs/dashboards/block-pool/states.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#637 Fix search issue in dr-policy
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/application-selector.tsx
  packages/mco/components/modals/drpolicy-apps-status/application-status.tsx
  packages/shared/generic/custom-dual-list-selector.tsx
Labels: approved, lgtm

#606 Refactoring drPolicy list page to support appset
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page-actions.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/helper.tsx
  packages/mco/components/empty-state-page/empty-page.tsx
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.scss
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.tsx
  packages/mco/components/modals/drpolicy-apps-status/application-status.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/hooks/applications-hook.ts
  packages/mco/hooks/index.ts
  packages/mco/hooks/mco-resources.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#592 [release-4.11-compatibility] Bug 2160445: undefined check for infrastructure + shared utility method
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/shared/selectors/k8s.ts
  packages/shared/utils/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#643 update nfs for deployment flow
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/enable-nfs.tsx
Labels: approved, lgtm

#632 Bug fix appset Apply policy modal
  packages/mco/components/modals/drpolicy-apps-apply/applicationset-handler.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx
  packages/mco/hooks/disaster-recovery.ts
  packages/mco/types/acm.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/modals/Selector.tsx
Labels: approved, lgtm

#611 feat: enabled kubernetes auth for SC and SS
  cypress/views/storage-class.ts
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/components/kms-config/vault-config.tsx
  packages/odf/constants/kms.ts
  packages/odf/types/kms.ts
Labels: approved, lgtm

#644 Topology: Add sidebar for NodeKind resources
  locales/en/plugin__odf-console.json
  package.json
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table.tsx
  packages/odf/components/utils/common.ts
  packages/odf/utils/ocs.ts
  packages/shared/alert/AlertsPanel.tsx
  packages/shared/alert/alerts.scss
  packages/shared/components/list/DetailPropertyList.tsx
  packages/shared/components/list/DetailPropertyListItem.tsx
  packages/shared/dashboards/utilization-card/prometheus-utilization-item.tsx
  packages/shared/heading/page-heading.tsx
  packages/shared/models/common.ts
  packages/shared/queries/node.ts
  packages/shared/queries/pod.ts
  packages/shared/status/Resource.ts
  packages/shared/topology/sidebar/TopologySideBar.tsx
  packages/shared/topology/sidebar/TopologySideBarContent.tsx
  packages/shared/topology/sidebar/node/NodeDetails.tsx
  packages/shared/topology/sidebar/node/NodeIPList.tsx
  packages/shared/topology/sidebar/node/NodeObserve.tsx
  packages/shared/topology/sidebar/node/NodeResources.tsx
  packages/shared/topology/sidebar/node/node-observe.scss
  packages/shared/topology/sidebar/node/node-resources.scss
  packages/shared/topology/sidebar/topology-sidebar-content.scss
  packages/shared/topology/sidebar/topology-sidebar.scss
  packages/shared/topology/sidebar/types.ts
  packages/shared/types/k8s.ts
  packages/shared/utils/index.ts
  packages/shared/utils/metrics.ts
  packages/shared/utils/node.ts
  yarn.lock
Labels: approved, lgtm

#642 Fix edit labels modelbody css issue
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/shared/modals/EditLabelModal.tsx
  packages/shared/modals/modal.scss
Labels: approved, lgtm

#640 Dashbaord changes
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.scss
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/mco-dashboard/data-policy/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/mco-dashboard/mco-common.scss
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/constants/dashboard.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/hooks/argo-application-set.ts
  packages/mco/models/acm.ts
  packages/mco/models/ramen.ts
  packages/mco/types/acm.ts
  packages/mco/types/dashboard.ts
  packages/mco/types/ramen.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/charts/utils.ts
  packages/shared/dashboards/status-card/HealthItem.tsx
  packages/shared/dashboards/utilization-card/utilization-item.tsx
  packages/shared/details-page/datetime.ts
  packages/shared/popup/status-popup.scss
  packages/shared/popup/status-popup.tsx
  packages/shared/utils/humanize.js
Labels: approved, lgtm

#653 update alert card for mco dashboard
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.scss
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/alert/AlertsPanel.tsx
Labels: approved, lgtm

#647 Remove Resource time line from cephblockpool performance card
  packages/ocs/dashboards/block-pool/utilization-card.tsx
Labels: approved, lgtm

#621 Topology View
  locales/en/plugin__odf-console.json
  packages/odf/components/odf-dashboard/dashboard.tsx
  packages/odf/components/topology/NodeGenerator.tsx
  packages/odf/components/topology/TopBar/SearchComponent.tsx
  packages/odf/components/topology/TopBar/TopologyNavigation.scss
  packages/odf/components/topology/TopBar/TopologyNavigation.tsx
  packages/odf/components/topology/TopBar/TopologySearch.scss
  packages/odf/components/topology/TopBar/TopologySearch.tsx
  packages/odf/components/topology/TopBar/TopologyTopBar.tsx
  packages/odf/components/topology/TopBar/index.ts
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/constants.ts
  packages/odf/components/topology/topology.scss
  packages/odf/components/topology/utils.ts
  packages/odf/resources.ts
  packages/shared/Nodes/index.ts
  packages/shared/error-handler/ErrorStateHandler.tsx
  packages/shared/models/common.ts
  packages/shared/monitoring/useAlert.ts
  packages/shared/topology/Context/SearchContext.ts
  packages/shared/topology/Context/TopologyContext.tsx
  packages/shared/topology/Context/index.ts
  packages/shared/topology/Nodes/Node.ts
  packages/shared/topology/Nodes/index.ts
  packages/shared/topology/factory/LayoutFactory.tsx
  packages/shared/topology/factory/StyleFactory.tsx
  packages/shared/topology/factory/StyleGroup.scss
  packages/shared/topology/factory/StyleGroup.tsx
  packages/shared/topology/factory/StyleNode.scss
  packages/shared/topology/factory/StyleNode.tsx
  packages/shared/topology/factory/index.ts
  packages/shared/topology/index.ts
  packages/shared/topology/sidebar/TopologySideBarContent.tsx
  packages/shared/topology/sidebar/index.ts
  packages/shared/topology/sidebar/node/index.ts
  packages/shared/topology/types.ts
  packages/shared/topology/utils/Monitoring.tsx
  packages/shared/topology/utils/index.ts
  packages/shared/utils/NodeHealth.ts
  packages/shared/utils/Tabs.tsx
  packages/shared/utils/common.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
  yarn.lock
Labels: approved, lgtm

#616 implemented TextInputWithFieldRequirements component on backing store…
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/body.tsx
  packages/odf/components/bucket-class/create-bc.tsx
  packages/odf/components/bucket-class/wizard-pages/general-page.tsx
  packages/odf/components/create-bs/create-bs.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-storage-class-step/create-storage-class-step.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/utils/validation.ts
  packages/shared/constants/fieldRequirements.ts
  packages/shared/input-with-requirements/TextInputWithFieldRequirements.tsx
  packages/shared/input-with-requirements/index.ts
  packages/shared/yup-validation-resolver/index.ts
  packages/shared/yup-validation-resolver/useYupValidationResolver.spec.ts
  packages/shared/yup-validation-resolver/useYupValidationResolver.ts
Labels: approved, lgtm

#655 Add deployments related sidebar components
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/utils.ts
  packages/shared/details-page/DetailsPage.tsx
  packages/shared/queries/deployment.ts
  packages/shared/queries/index.ts
  packages/shared/topology/factory/StyleNode.tsx
  packages/shared/topology/sidebar/TopologySideBarContent.tsx
  packages/shared/topology/sidebar/common/PodList.tsx
  packages/shared/topology/sidebar/common/node-resources.scss
  packages/shared/topology/sidebar/deployments/DeploymentDetails.tsx
  packages/shared/topology/sidebar/deployments/DeploymentObserve.tsx
  packages/shared/topology/sidebar/deployments/DeploymentResources.tsx
  packages/shared/topology/sidebar/deployments/index.ts
  packages/shared/topology/sidebar/deployments/node-resources.scss
  packages/shared/topology/utils/resource.ts
Labels: approved, lgtm

#654 Topology: Add sidebar tabs for StorageClusterKind
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/object-service/storage-efficiency-card/storage-efficiency-card.tsx
  packages/ocs/dashboards/persistent-external/utilization-card.tsx
  packages/ocs/dashboards/persistent-internal/storage-efficiency-card/storage-efficiency-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/sidebar/TopologySideBar.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/odf/components/topology/sidebar/index.ts
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterObserve.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterResources.tsx
  packages/odf/components/topology/sidebar/storage-cluster/index.tsx
  packages/odf/components/topology/sidebar/topology-sidebar-content.scss
  packages/odf/components/topology/sidebar/topology-sidebar.scss
  packages/shared/topology/sidebar/common/PodList.tsx
  packages/shared/topology/sidebar/common/resources-tab.scss
  packages/shared/topology/sidebar/deployments/DeploymentResources.tsx
  packages/shared/topology/sidebar/deployments/node-resources.scss
  packages/shared/topology/sidebar/node/NodeDetails.tsx
  packages/shared/topology/sidebar/node/NodeObserve.tsx
  packages/shared/topology/sidebar/node/NodeResources.tsx
  packages/shared/topology/sidebar/node/index.ts
  packages/shared/topology/sidebar/node/node-resources.scss
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#659 Changes order of Topology tab
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#660 Topology sidebar: fix unnecessary rendering issue
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/sidebar/TopologySideBar.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/shared/topology/sidebar/alerts/AlertsDetails.tsx
Labels: approved, lgtm

#657 Dashbaord font fix
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-list-page/helper.tsx
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/mco-dashboard/mco-common.scss
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx
  packages/mco/components/modals/drpolicy-apps-apply/subscriptions/apply-policy-modal.tsx
  packages/mco/constants/dashboard.ts
  packages/mco/types/dashboard.ts
  packages/shared/alert/AlertsPanel.tsx
  packages/shared/alert/alerts.scss
  packages/shared/monitoring/useAlert.ts
Labels: approved, lgtm

#651 add warning for no StorageClass (wizard)
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/shared/dropdown/ResourceDropdown.tsx
Labels: approved, lgtm

#593 RHSTOR 2516: in-transit encryption for ss deployment + details page
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/utils/common.ts
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/security-and-network-step.tsx
  packages/odf/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
  packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/types/common.ts
  packages/odf/types/external-storage.ts
  packages/shared/types/storage.ts
  packages/shared/utils/common.ts
Labels: approved, lgtm

#650 Implemented RHF and Yup schema validations on forms
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/body.tsx
  packages/odf/components/attach-obc/AttachOBC.tsx
  packages/odf/components/bucket-class/wizard-pages/general-page.tsx
  packages/odf/components/create-bs/create-bs.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-storage-class-step/create-storage-class-step.tsx
  packages/odf/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
  packages/odf/components/mcg-endpoints/gcp-endpoint-type.tsx
  packages/odf/components/mcg-endpoints/s3-endpoint-type.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/useObcNameSchema.ts
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/constants/index.ts
  packages/odf/constants/providerSchema.ts
  packages/odf/types/external-storage.ts
  packages/shared/constants/fieldRequirements.ts
  packages/shared/constants/formSettings.ts
  packages/shared/constants/index.ts
  packages/shared/dropdown/ResourceDropdown.tsx
  packages/shared/dropdown/StaticDropdown.tsx
  packages/shared/form-group-controller/FormGroupController.tsx
  packages/shared/form-group-controller/index.ts
  packages/shared/input-with-requirements/TextInputWithFieldRequirements.tsx
  packages/shared/input-with-requirements/useFieldRequirements.spec.ts
  packages/shared/yup-validation-resolver/useYupValidationResolver.spec.ts
  packages/shared/yup-validation-resolver/useYupValidationResolver.ts
Labels: approved, lgtm
