Repository red-hat-storage/odf-console, pull requests merged in 2023-03, with the labels that each got.

#658 Adds support for syncing deletion and bug fixes
  locales/en/plugin__odf-console.json
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/create-obc.scss
  packages/odf/components/mcg/log-replication-info-form.tsx
  packages/odf/components/mcg/replication-policy-form.tsx
  packages/odf/components/mcg/state.ts
  packages/odf/utils/mcg.ts
Labels: approved, lgtm

#664 Fix empty state for topology view
  locales/en/plugin__odf-console.json
  packages/odf/components/topology/Topology.tsx
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#670 Bug 2132733: Display raw-capacity for non-standard deployments
  packages/odf/constants/common.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#645 Enable save changes button only after labels added for all app
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx
Labels: approved, lgtm

#675 CI E2E: avoid memory issues during image building
  Dockerfile.ci
  Dockerfile.mco.ci
Labels: approved, lgtm

#662 Revert "feat: support key rotation encryption"
  packages/odf/components/utils/common.ts
  packages/shared/types/storage.ts
Labels: approved, lgtm

#678 CI: Add build step for mco
  .github/workflows/frontend-build.yml
Labels: approved, lgtm

#667 Fix rerender issues for Alerts tab
  packages/odf/components/topology/TopBar/TopologyNavigation.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/sidebar/TopologySideBar.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterObserve.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterResources.tsx
  packages/odf/components/topology/sidebar/topology-sidebar-content.scss
  packages/odf/components/topology/sidebar/topology-sidebar.scss
  packages/shared/topology/Context/TopologyContext.tsx
  packages/shared/topology/sidebar/deployments/DeploymentObserve.tsx
  packages/shared/topology/sidebar/deployments/DeploymentResources.tsx
  packages/shared/topology/sidebar/node/NodeDetails.tsx
  packages/shared/topology/sidebar/node/NodeObserve.tsx
  packages/shared/topology/sidebar/node/NodeResources.tsx
Labels: approved, lgtm

#681 Bug 2177695: Fix DR dashbaord metrics name
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/queries.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#610 Update copyright license details
  LICENSE
Labels: approved, lgtm

#620 Bug 2165128: removed the subversion check for the mco operator
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/utils/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#683 Fixes page breaking issue with topology
  packages/shared/topology/factory/StyleNode.tsx
  packages/shared/utils/NodeHealth.ts
Labels: approved, lgtm

#695 CI build: constrain the memory usage of node processes
  Dockerfile.ci
  Dockerfile.mco.ci
  webpack.config.ts
Labels: approved, lgtm

#699 CI: add .ci-operator.yaml
  .ci-operator.yaml
  .prettierignore
  Dockerfile.ci.runner
  README.md
Labels: approved, lgtm

#669 Bug 2115020: Removed sync interval update and create from mirror peer
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/mco/types/odf-mco.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#674 added condition to bucketclass schema field based on isNoobaa
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
Labels: approved, lgtm

#691 Topology: Fixes Issues pointed by UX
  locales/en/plugin__odf-console.json
  packages/odf/components/topology/NodeGenerator.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/odf/components/topology/topology.scss
  packages/odf/components/topology/utils.ts
  packages/odf/utils/ocs.ts
  packages/shared/topology/factory/StyleGroup.tsx
Labels: approved, lgtm

#688 Fix OBC flakes
  cypress/tests/active-health-checks.spec.ts
  cypress/tests/bucket-class.spec.ts
  cypress/tests/kms-encryption-sc.spec.ts
  cypress/tests/obc-test.spec.ts
  cypress/tests/persistent-dashboard-check.spec.ts
  cypress/views/obcPage.ts
  package.json
Labels: approved, lgtm

#665 Enabling MCO and DR dashboard based on admin privilege
  packages/mco/components/data-policies/data-policies-page.tsx
  packages/mco/constants/common.ts
  packages/mco/features.ts
  plugins/mco/console-extensions.json
Labels: approved, lgtm

#707 Fix for storage system href link on the ODF multicluster dashboard
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/components/mco-dashboard/storage-system/system-capacity-card/capacity-card.tsx
Labels: approved, lgtm

#680 Build: move to 'dependencies' the ones required for running a build
  .github/workflows/frontend-build.yml
  Dockerfile.ci
  Dockerfile.mco.ci
  package.json
  yarn.lock
Labels: approved, lgtm

#701 Add the valid AWS GovCloud regions
  packages/odf/constants/mcg.ts
Labels: approved, lgtm

#677 storage system deployment next button enable for IBM FS
  packages/odf/components/create-storage-system/footer.tsx
Labels: approved, lgtm

#728 Fixes topology search
  packages/odf/components/topology/TopBar/SearchComponent.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/topology.scss
  packages/shared/utils/NodeHealth.ts
Labels: approved, lgtm

#698 DR dashboard metrics changes
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/argo-application-set.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/constants/dashboard.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/utils/humanize.js
Labels: approved, lgtm

#702 Bug 2179798: [release-4.9] Update Nginx cache configuration
  default.conf
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#735 Bug 2181832: added placeholder for resource dropdown
  locales/en/plugin__odf-console.json
  packages/shared/dropdown/ResourceDropdown.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#744 Topology: fix 'Exit fullscreen' message not shown
  packages/odf/components/topology/TopBar/TopologySearch.tsx
Labels: approved, lgtm

#746 hide sidebar on level change
  packages/odf/components/topology/TopBar/TopologyNavigation.tsx
  packages/odf/components/topology/Topology.tsx
Labels: approved, lgtm

#742 added missing vault enterprise namespace to csi kms config map
  packages/odf/components/kms-config/utils.tsx
Labels: approved, lgtm

#753 Upgrade 'resolve-url-loader' dep.
  package.json
  yarn.lock
Labels: approved, lgtm

#679 Match the version of consoleplugin to odf operator
  package.json
  scripts/versionCheck.mts
Labels: approved, lgtm

#668 Fix last sync time on dr status popover
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-data-policies-status/dr-status.tsx
  packages/mco/components/modals/drpolicy-apps-apply/apply-policy-dual-list-selector.tsx
Labels: approved, lgtm

#693 Enable workflows (4.13 GH) + Update ODF operator version (4.13 CI)
  .github/workflows/frontend-build.yml
  openshift-ci/odf-catalog-source.yaml
Labels: approved, lgtm

#760 Fix relocate for metro/regional DR
  packages/mco/components/modals/app-failover-relocate/subscriptions/target-cluster-selector.tsx
Labels: approved, lgtm
