Repository red-hat-storage/odf-console, pull requests merged in 2023-06, with the labels that each got.

#891 Bug 2211807: [DR] Fix operator health status in dashboard
  packages/mco/components/mco-dashboard/data-policy/status-card/status-card.tsx
  packages/mco/constants/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#893 Bump core sdk + update "odf.dashboard/tab" extension
  package.json
  packages/odf-plugin-sdk/extensions/horizontal-nav-tab.ts
  packages/odf-plugin-sdk/extensions/index.ts
  packages/odf/components/odf-dashboard/dashboard.tsx
  packages/odf/components/odf-dashboard/utils.ts
  plugins/odf/console-extensions.json
  yarn.lock
Labels: approved, lgtm

#898 Bug 2122521: updated files for unique ip address validation for ibm fs
  locales/en/plugin__odf-console.json
  packages/ibm/utils.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/create-storage-class-step/create-storage-class-step.tsx
  packages/odf/package.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#892 Manage data policy list view
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/modals/app-manage-policies/acm-action-callback.tsx
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/mco/components/modals/app-manage-policies/style.scss
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/components/modals/app-manage-policies/utils/types.ts
  packages/mco/hooks/mco-resources.ts
  packages/mco/utils/acm.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/odf/components/bucket-class/backingstore-table.tsx
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table.tsx
  packages/odf/components/namespace-store/namespace-store-table.tsx
  packages/shared/dropdown/action-dropdown.tsx
  packages/shared/hooks/select-list.ts
  packages/shared/table/selectable-table.spec.tsx
  packages/shared/table/selectable-table.tsx
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#895 move object resources to new nav item
  cypress/support/pages/app.ts
  cypress/tests/create-backing-store.spec.ts
  cypress/tests/namespace-store.spec.ts
  cypress/tests/obc-test.spec.ts
  cypress/views/bc.ts
  cypress/views/common.ts
  cypress/views/obcPage.ts
  locales/en/plugin__odf-console.json
  packages/odf-plugin-sdk/extensions/horizontal-nav-tab.ts
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/ObjectBucket.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/components/object-service-nav-item/object-service.tsx
  packages/odf/components/odf-dashboard/dashboard.tsx
  packages/odf/components/odf-dashboard/utils.ts
  packages/odf/components/resource-pages/BackingStoreDetailsPage.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/NamespaceStoreDetailsPage.tsx
  packages/odf/utils/horizontal-nav-tab.tsx
  packages/odf/utils/index.ts
  packages/shared/constants/common.ts
  packages/shared/utils/index.ts
  packages/shared/utils/link.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#904 fix flaky CI (installation + block-pool tests)
  cypress/support.ts
  cypress/views/block-pool.ts
Labels: approved, lgtm

#902 Bug 2216707: Fixes for topology view for external mode
  locales/en/plugin__odf-console.json
  packages/odf/components/topology/Topology.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#894 Bulk unassign data policy for application
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/helper/messages.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
Labels: approved, lgtm

#880 Bug 2210040: added the section heading for deployment details in topology view
  locales/en/plugin__odf-console.json
  packages/shared/topology/sidebar/deployments/DeploymentDetails.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#896 Add pvc+namespace based used-capacity queries
  packages/ocs/queries/ceph-storage.ts
Labels: approved, lgtm

#900 Adds support for single replica pool
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
Labels: approved, lgtm

#901 Adds dashboard for ocs client operator
  Dockerfile.client
  locales/en/plugin__odf-console.json
  package.json
  packages/client/Dockerfile
  packages/client/package.json
  packages/client/src/components/dashboards/cards/activity-card.scss
  packages/client/src/components/dashboards/cards/activity-card.tsx
  packages/client/src/components/dashboards/cards/details-card.tsx
  packages/client/src/components/dashboards/cards/index.ts
  packages/client/src/components/dashboards/cards/inventory-card.tsx
  packages/client/src/components/dashboards/cards/status-card.tsx
  packages/client/src/components/dashboards/client-dashboard.tsx
  packages/client/src/constants.ts
  packages/client/src/models.ts
  packages/client/src/types.ts
  packages/ocs/constants/common.ts
  packages/ocs/dashboards/ocs-system-dashboard.tsx
  packages/ocs/dashboards/persistent-external/breakdown-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/ocs-upgrade-activity.tsx
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx
  packages/ocs/queries/ceph-storage.ts
  packages/shared/queries/index.ts
  packages/shared/queries/types.ts
  plugins/client/console-extensions.json
  plugins/client/console-plugin.json
  scripts/generatePluginPackage.mts
  scripts/versionCheck.mts
Labels: approved, lgtm
