Repository red-hat-storage/odf-console, pull requests merged in 2023-12, with the labels that each got.

#1109 E2E: move catalog source to 4.15
  cypress/tests/active-health-checks.spec.ts
  openshift-ci/odf-catalog-source.yaml
Labels: approved, lgtm

#1102 Create StorageSystem: add perfomance mode selector
  cypress/support.ts
  locales/en/plugin__odf-console.json
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/bucket-class/wizard-pages/review-page.tsx
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table-footer.tsx
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table.spec.tsx
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/tooltips.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.scss
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
  packages/odf/types/common.ts
  packages/odf/utils/ocs.ts
  packages/shared/src/types/storage.ts
Labels: approved, lgtm

#1095 Provide option to optimise cluster for Regional-DR
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/ocs/utils/index.ts
Labels: approved, lgtm

#1120 [RHSTOR-5136] Updates for building client operator UI
  Dockerfile.client
  package.json
  packages/client/Dockerfile
  plugins/client/console-extensions.json
Labels: approved, lgtm

#1117 [RHSTOR-5140] Adds Ceph mon count update for 5 zones
  locales/en/plugin__odf-console.json
  packages/odf/modals/configure-mons/configure-mons.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1111 Blocking DRPolicy creation for multiple ODF cluster
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.scss
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/constants/acm.ts
  packages/mco/types/acm.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/odf/components/mcg-endpoints/pvc-endpoint-type.tsx
  packages/shared/src/utils/RequestSizeInput.tsx
Labels: approved, lgtm

#1124 Fixes RDR error message appearance issue
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
Labels: approved, lgtm

#1115 [RHSTOR-5133] Adds Provider Mode support
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/odf/components/odf-dashboard/status-card/status-card-popover.scss
  packages/odf/components/odf-dashboard/status-card/status-card-popover.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/status-card/utils.ts
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/list-filter.ts
  packages/odf/components/storage-consumers/onboarding-modal.scss
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/features.ts
  packages/odf/i18n-comments.ts
  packages/odf/models/ocs.ts
  packages/shared/src/dashboards/status-card/HealthItem.tsx
  packages/shared/src/details-page/datetime.ts
  packages/shared/src/details-page/timestamp.tsx
  packages/shared/src/types/storage.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1116 Block RDR policy creation for non-DR optimized cluster
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/constants/acm.ts
Labels: approved, lgtm

#1131 Bug 2252035: Updates query to report raw availability of a pool
  packages/ocs/queries/ceph-storage.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#1105 Remove unnecessary tool-tips and appset specific details
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
Labels: approved, lgtm

#1114 Add parser for subscription application
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/application.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard-context.tsx
  packages/mco/components/mco-dashboard/data-policy/dr-dashboard.tsx
  packages/mco/components/mco-dashboard/data-policy/parsers/applicationset-parser.tsx
  packages/mco/components/mco-dashboard/data-policy/parsers/subscription-parser.tsx
  packages/mco/components/mco-dashboard/data-policy/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.tsx
  packages/mco/constants/dashboard.ts
  packages/mco/hooks/argo-application-set.ts
  packages/mco/hooks/subscription.ts
  packages/mco/types/dashboard.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#1128 Application view for subscription application monitoring
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/application.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.scss
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/data-policy/parsers/subscription-parser.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/mco/types/acm.ts
  packages/mco/types/dashboard.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/src/hooks/index.ts
  packages/shared/src/hooks/scheduler.ts
  packages/shared/src/utils/common.ts
Labels: approved, lgtm

#1137 Bug 2255340: Updates CephMonCountLow alert modal errors
  locales/en/plugin__odf-console.json
  packages/odf/modals/configure-mons/configure-mons.tsx
  packages/odf/redux/selectors/odf-system-flags.ts
  packages/shared/src/types/storage.ts
  plugins/odf/console-extensions.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1143 Updates Onboarding modal to connect with provider proxy
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/onboarding-modal.tsx
Labels: approved, lgtm

#1144 remove 'co-*' classes supporting PF5 imports/variables
  packages/client/src/components/dashboards/cards/activity-card.tsx
  packages/client/src/components/dashboards/cards/status-card.tsx
  packages/client/style.scss
  packages/ocs/block-pool/body.tsx
  packages/ocs/dashboards/object-service/activity-card/activity-card.tsx
  packages/ocs/dashboards/object-service/status-card/status-card.scss
  packages/ocs/dashboards/object-service/status-card/status-card.tsx
  packages/ocs/dashboards/persistent-external/status-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
  packages/ocs/modals/block-pool/create-block-pool-modal.tsx
  packages/ocs/storage-class/sc-form.tsx
  packages/ocs/style.scss
  packages/odf/components/bucket-class/_backingstore-table.scss
  packages/odf/components/create-bs/backing-store-dropdown.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table.scss
  packages/odf/components/namespace-store/namespace-store-dropdown.tsx
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/components/namespace-store/namespace-store-table.scss
  packages/odf/components/odf-dashboard/status-card/status-card.scss
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/utils/osd-size-dropdown.tsx
  packages/shared/src/dashboards/utilization-card/multi-utilization-item.tsx
  packages/shared/src/dashboards/utilization-card/utilization-item.tsx
  packages/shared/src/details-page/DetailsPage.tsx
  packages/shared/src/dropdown/ResourceDropdown.tsx
  packages/shared/src/dropdown/resourceDropdown.scss
  packages/shared/src/generic/FieldLevelHelp.tsx
  packages/shared/src/generic/ModalTitle.tsx
  packages/shared/src/generic/field-level-help.scss
  packages/shared/src/generic/status-box.tsx
  packages/shared/src/modals/modal.scss
  packages/shared/src/resource-link/resource-link.tsx
  packages/shared/src/style.scss
  packages/shared/src/styles/_common.scss
  packages/shared/src/styles/_dashboard.scss
  packages/shared/src/styles/_dropdown.scss
  packages/shared/src/styles/_resource.scss
  packages/shared/src/styles/_vars.scss
  packages/shared/src/utils/Errors.tsx
  packages/shared/src/utils/SecretValue.tsx
Labels: approved, lgtm
