Repository red-hat-storage/odf-console, pull requests merged in 2023-09, with the labels that each got.

#1001 Bug 2203362: [release-4.11] Fix the capacity queries
  packages/ocs/queries/ceph-storage.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1022 add mpath for LSO device types
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/constants/lso.ts
  packages/odf/types/lso.ts
  packages/odf/utils/lso.ts
  packages/shared/package.json
  packages/shared/src/dropdown/multiselectdropdown.tsx
  yarn.lock
Labels: approved, lgtm

#1018 Fix incorrect applicaiton type on connected app modal
  packages/mco/hooks/applications-hook.ts
Labels: approved, lgtm

#1025 Bug 2214023: Fixes Provider ID to show the complete id in node details
  packages/shared/src/topology/sidebar/node/NodeDetails.tsx
  packages/shared/src/utils/node.spec.ts
  packages/shared/src/utils/node.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1031 Bug 2182351: [release-4.14] add mpath for LSO device types
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/constants/lso.ts
  packages/odf/types/lso.ts
  packages/odf/utils/lso.ts
  packages/shared/package.json
  packages/shared/src/dropdown/multiselectdropdown.tsx
  yarn.lock
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1029 Fixes OBC page crash issue
  package.json
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/kms-config/providers.ts
  packages/odf/components/kms-config/vault-config.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
  packages/shared/package.json
  packages/shared/src/details-page/DetailsPage.tsx
  packages/shared/src/modals/EditAnnotations.tsx
  packages/shared/src/modals/EditLabelModal.tsx
  yarn.lock
Labels: approved, lgtm

#1028 Random bogus error in relocate/failover dialog: "No DRPolicy found"
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-popover.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
Labels: approved, lgtm

#1033 Bug 2235423: Random bugs error in relocate/failover dialog: "No DRPolicy found"
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1034 revert EditAnnotation and EditLabel (shared) changes
  packages/shared/src/details-page/DetailsPage.tsx
  packages/shared/src/modals/EditAnnotations.tsx
  packages/shared/src/modals/EditLabelModal.tsx
Labels: approved, lgtm

#1036 disable OBC tests to unblock CI
  cypress/tests/obc-test.spec.ts
Labels: approved, lgtm

#1030 update requested capacity card for external mode
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.tsx
  packages/ocs/dashboards/persistent-external/breakdown-card.tsx
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx
  packages/ocs/queries/ceph-storage.ts
Labels: approved, lgtm

#1040 Bug 2237213: Fixes OBC crash issue
  package.json
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#950 Add proper error message when MDR policy creation failure
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/reducer.ts
  packages/mco/components/disaster-recovery/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
  packages/mco/components/disaster-recovery/create-dr-policy/selected-cluster-view.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/data-policy/summary-card/summary-card.tsx
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/target-cluster-selector.tsx
  packages/mco/constants/acm.ts
  packages/mco/utils/acm.ts
Labels: approved, lgtm

#1039 Added required field check in wizard flow
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/helper/select-policy-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/style.scss
  packages/mco/constants/disaster-recovery.ts
  packages/mco/utils/common.ts
  packages/shared/src/dropdown/singleselectdropdown.tsx
  packages/shared/src/utils/NameValueEditor.tsx
Labels: approved, lgtm

#1046 fix Create StorageClass form
  packages/ocs/storage-class/sc-form.tsx
Labels: approved, lgtm

#1015 Support translation for ODF sub tab items
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/BlockPoolDetailsPage.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/components/resource-pages/BackingStoreDetailsPage.tsx
  packages/odf/components/resource-pages/BucketClassDetailsPage.tsx
  packages/odf/components/resource-pages/NamespaceStoreDetailsPage.tsx
  packages/odf/i18n-comments.ts
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#1053 remove 'Volume type' from BlockPool create/update form
  cypress/views/block-pool.ts
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/body.scss
  packages/ocs/block-pool/body.tsx
  packages/ocs/block-pool/reducer.ts
  packages/ocs/modals/block-pool/update-block-pool-modal.tsx
Labels: approved, lgtm

#1049 fix StorageClass filtering for add capacity modal
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/utils/ocs.ts
Labels: approved, lgtm
