Repository red-hat-storage/odf-console, pull requests merged in 2023-07, with the labels that each got.

#905 feat: added the options to select via pvc and namespace for the breakdown card
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.scss
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx
  packages/ocs/queries/ceph-storage.ts
  packages/odf/resources.ts
  packages/shared/src/dashboards/breakdown-card/breakdown-body.tsx
  packages/shared/src/dashboards/breakdown-card/breakdown-capacity.tsx
  packages/shared/src/queries/types.ts
Labels: approved, lgtm

#912 Disable bulk unassign
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/shared/src/table/selectable-table.tsx
Labels: approved, lgtm

#914 [release-4.12] Bug 2214575: Fixes PluginManifest version during plugin build process
  package.json
  plugins/odf/console-plugin.json
  scripts/versionCheck.mts
  yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#915 [release-4.12-compatibility] Bug 2214575: Fixes PluginManifest version during plugin build process
  package.json
  plugins/odf/console-plugin.json
  scripts/versionCheck.mts
  yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#913 Fix KMIP file upload error message
  locales/en/plugin__odf-console.json
  packages/odf/components/kms-config/thales-config.tsx
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
Labels: approved, lgtm, ok-to-test

#903 Policy configuration view for application
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/create-dr-policy/select-replication-type.tsx
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/helper/messages.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-config-viewer.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/policy-config-view.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/mco/components/modals/app-manage-policies/style.scss
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/components/modals/app-manage-policies/utils/types.ts
  packages/mco/constants/disaster-recovery.ts
  packages/shared/src/dropdown/singleselectdropdown.tsx
  packages/shared/src/index.ts
  packages/shared/src/labels/index.ts
  packages/shared/src/labels/labels.tsx
Labels: approved, lgtm

#911 Adds support for bucket replication scaling
  locales/en/plugin__odf-console.json
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/create-obc.scss
  packages/odf/components/mcg/log-replication-info-form.tsx
  packages/odf/components/mcg/replication-policy-form.tsx
Labels: approved, lgtm

#918 Set @odf-console/shared as source library
  locales/en/plugin__odf-console.json
  package.json
  packages/client/package.json
  packages/ibm/package.json
  packages/mco/package.json
  packages/odf/package.json
  packages/shared/LICENSE
  packages/shared/package.json
  packages/shared/src/models/common.ts
  packages/shared/src/models/console-models.ts
  packages/shared/tsconfig.json
  packages/shared/webpack.config.ts
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#906 Assign policy wizard
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/messages.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-config-viewer.tsx
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/helper/select-policy-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/mco/components/modals/app-manage-policies/style.scss
  packages/mco/components/modals/app-manage-policies/utils/acm-search-quries.ts
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/components/modals/app-manage-policies/utils/types.ts
  packages/mco/components/modals/drpolicy-apps-apply/utils.tsx
  packages/mco/constants/acm.ts
  packages/mco/constants/common.ts
  packages/mco/constants/dashboard.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/constants/index.ts
  packages/mco/constants/url-paths.ts
  packages/mco/hooks/acm-safe-fetch.ts
  packages/mco/hooks/argo-application-set.ts
  packages/mco/hooks/index.ts
  packages/mco/types/acm.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/shared/src/dropdown/multiselectdropdown.tsx
  packages/shared/src/hooks/custom-prometheus-poll/safe-fetch-hook.ts
  packages/shared/src/modals/EditAnnotations.tsx
  packages/shared/src/utils/NameValueEditor.tsx
Labels: approved, lgtm

#917 Manage policy modal for subscription applications
  packages/mco/components/modals/app-manage-policies/acm-action-callback.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.tsx
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/hooks/index.ts
  packages/mco/hooks/subscription.ts
  packages/mco/utils/acm.ts
  packages/mco/utils/disaster-recovery.tsx
  plugins/mco/console-extensions.json
Labels: approved, lgtm

#919 Deprecate bulk DR policy assign actions
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/disaster-recovery/drpolicy-list-page/helper.ts
  packages/mco/constants/disaster-recovery.ts
Labels: approved, lgtm

#920 update shared yarn.lock
  yarn.lock
Labels: approved, lgtm

#921 update selectable table to support column tooltip/popover
  packages/shared/src/table/selectable-table.tsx
Labels: approved, lgtm

#907 Add CEPH RBD snapshot and replication throughput graph
  locales/en/plugin__odf-console.json
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.scss
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/queries.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/src/charts/utils.ts
  packages/shared/src/dashboards/utilization-card/area-chart.tsx
  packages/shared/src/dashboards/utilization-card/prometheus-utilization-item.tsx
  packages/shared/src/dashboards/utilization-card/utilization-item.tsx
  packages/shared/src/details-page/datetime.ts
Labels: approved, lgtm

#923 Shared lib: create GH action for publishing & bump version
  .github/workflows/shared-lib-publish.yml
  packages/shared/README.md
  packages/shared/package.json
  packages/shared/scripts/publish-new.sh
  yarn.lock
Labels: approved, lgtm

#924 added selectProps to MultiSelectDropdown
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/shared/package.json
  packages/shared/src/dropdown/multiselectdropdown.tsx
  yarn.lock
Labels: approved, lgtm

#926 Selectable table bug fix
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/shared/package.json
  packages/shared/src/table/selectable-table.spec.tsx
  packages/shared/src/table/selectable-table.tsx
  yarn.lock
Labels: approved, lgtm

#928 Bug 2214033: Fixes Pod memory query for Topology sidebar
  packages/shared/src/queries/pod.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#929 Bug 2210047: Adds loading state for ODF dashboard until all pages are resolved
  packages/odf/components/odf-dashboard/dashboard.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#927 Bug 2213550: Correct the display names of rbd image statuses on BlockPools page
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/block-pool/states.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#925 test: add annotations mutators
  packages/ocs/storage-class/mutators.spec.ts
Labels: approved, lgtm

#938 Bug 2209251: Fixes Topology view Deployment resources view
  packages/shared/src/topology/sidebar/deployments/DeploymentResources.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#939 Bug 2211482: Page loader to delay in fetching application DR info
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#930 Removes 304 logs for local development server
  webpack.config.ts
Labels: approved, lgtm

#942 Bug 2213183: Block users to switch StorageClass arbitrarily
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#941 Bug 2209258: Fixes sidebar content length dynamically based on screen size
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/sidebar/TopologySideBar.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/odf/components/topology/sidebar/topology-sidebar-content.scss
  packages/shared/src/hooks/useAutoExpand.ts
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#860 tests: for inventory and icons in shared status folder
  packages/shared/status/Inventory.spec.tsx
  packages/shared/status/icons.spec.tsx
Labels: approved, lgtm

#933 Bug 2225223: other stats data for breakdown card
  packages/shared/src/dashboards/breakdown-card/utils.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#940 Bug 2213552: Modified to a standard time format in DR pages
  packages/mco/components/modals/app-data-policies-status/subscriptions/dr-status-table.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/peer-cluster-status.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/target-cluster-selector.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/mco/utils/common.ts
  packages/shared/src/details-page/datetime.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low
