Repository red-hat-storage/odf-console, pull requests merged in 2024-02, with the labels that each got.

#1205 publish '@odf-console/shared' version 'beta12'
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm

#1204 Rename data policies navigation to disaster recovery
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/data-policies/data-policies-page.tsx
  packages/mco/components/disaster-recovery-page/disaster-recovery.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/alert-card/alert-card.scss
  packages/mco/components/mco-dashboard/disaster-recovery/alert-card/alert-card.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/alert-card/alert-item.scss
  packages/mco/components/mco-dashboard/disaster-recovery/alert-card/alert-item.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/application.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster-app-card.scss
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/common.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/dr-dashboard-context.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/dr-dashboard.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/parsers/applicationset-parser.spec.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/parsers/applicationset-parser.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/parsers/subscription-parser.spec.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/parsers/subscription-parser.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/status-card/status-card.scss
  packages/mco/components/mco-dashboard/disaster-recovery/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/summary-card/summary-card.scss
  packages/mco/components/mco-dashboard/disaster-recovery/summary-card/summary-card.tsx
  packages/mco/components/modals/app-manage-policies/acm-action-callback.tsx
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#1211 Remove support for Single Replica pool from wizard flow
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
Labels: approved, lgtm

#1218 Bug 2263313: Backport fusion hci phase 2 related changes to 4.14 branch
  Dockerfile.client
  locales/en/plugin__odf-console.json
  package.json
  packages/client/Dockerfile
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/odf/components/odf-dashboard/status-card/status-card-popover.scss
  packages/odf/components/odf-dashboard/status-card/status-card-popover.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/status-card/utils.ts
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/list-filter.ts
  packages/odf/components/storage-consumers/onboarding-modal.scss
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/features.ts
  packages/odf/i18n-comments.ts
  packages/odf/models/ocs.ts
  packages/shared/src/dashboards/status-card/HealthItem.tsx
  packages/shared/src/details-page/datetime.ts
  packages/shared/src/details-page/timestamp.tsx
  packages/shared/src/types/storage.ts
  plugins/client/console-extensions.json
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#1219 Bug 2263313: Backport fusion hci phase 2 related changes to 4.14 branch
  Dockerfile.client
  locales/en/plugin__odf-console.json
  package.json
  packages/client/Dockerfile
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/odf/components/odf-dashboard/status-card/status-card-popover.scss
  packages/odf/components/odf-dashboard/status-card/status-card-popover.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/status-card/utils.ts
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/list-filter.ts
  packages/odf/components/storage-consumers/onboarding-modal.scss
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/features.ts
  packages/odf/i18n-comments.ts
  packages/odf/models/ocs.ts
  packages/shared/src/dashboards/status-card/HealthItem.tsx
  packages/shared/src/details-page/datetime.ts
  packages/shared/src/details-page/timestamp.tsx
  packages/shared/src/types/storage.ts
  plugins/client/console-extensions.json
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#1223 [release-4.14] Bug 2263214: Fixes prop type accepted for StatusCardPopover
  packages/odf/components/odf-dashboard/status-card/status-card-popover.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1224 [release-4.14-compatibility] Bug 2263214: Fixes prop type accepted for StatusCardPopover
  packages/odf/components/odf-dashboard/status-card/status-card-popover.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1226 Fix multicloudgateway spec
  packages/odf/components/utils/common.ts
Labels: approved, lgtm

#1230 Adds spec changes to enable Tls on Postgres
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/utils/common.ts
  packages/shared/src/types/storage.ts
Labels: approved, lgtm

#1138 Bug 2249001: [release-4.12] remove 'Volume type' from BlockPool create/update form
  cypress/views/block-pool.ts
  locales/en/plugin__odf-console.json
  packages/ocs/block-pool/body.scss
  packages/ocs/block-pool/body.tsx
  packages/ocs/block-pool/reducer.ts
  packages/ocs/modals/block-pool/update-block-pool-modal.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1235 CSS issue fix for pvc label selector step
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
Labels: approved, lgtm

#1236 add imperative apps list page
  locales/en/plugin__odf-console.json
  packages/mco/components/disaster-recovery-page/disaster-recovery.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/application.tsx
  packages/mco/components/modals/app-manage-policies/helper/policy-list-view-table.tsx
  packages/mco/components/protected-applications/components.tsx
  packages/mco/components/protected-applications/list-page.tsx
  packages/mco/components/protected-applications/protected-apps.scss
  packages/mco/components/protected-applications/utils.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/ramen.ts
  packages/odf/components/odf-dashboard/performance-card/performance-card.tsx
  packages/shared/src/details-page/datetime.ts
  packages/shared/src/generic/Error.tsx
  packages/shared/src/resource-link/resource-link.tsx
  packages/shared/src/table/composable-table.tsx
  packages/shared/src/table/index.ts
  packages/shared/src/table/selectable-table.tsx
  packages/shared/src/table/table.tsx
  packages/shared/src/utils/common.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/table.ts
Labels: approved, lgtm

#1210 Discovered application DR enroll Wizard - Step1
  cypress/support/login.ts
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.scss
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.spec.tsx
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.tsx
  packages/mco/components/discovered-application-wizard/footer.tsx
  packages/mco/components/discovered-application-wizard/utils/reducer.ts
  packages/mco/components/discovered-application-wizard/wizard-steps/namespace-step/namesapce-table.tsx
  packages/mco/components/discovered-application-wizard/wizard-steps/namespace-step/namespace-step.scss
  packages/mco/components/discovered-application-wizard/wizard-steps/namespace-step/namespace-step.tsx
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/utils/acm-search-quries.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/hooks/acm-safe-fetch.ts
  packages/mco/types/acm.ts
  packages/mco/utils/acm-search-quries.ts
  packages/mco/utils/index.ts
  packages/shared/src/table/selectable-table.tsx
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/namespace.ts
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm

#1238 Update imperative apps list page
  cypress/support/login.ts
  locales/en/plugin__odf-console.json
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/empty-state-page/empty-page.scss
  packages/mco/components/empty-state-page/empty-page.tsx
  packages/mco/components/protected-applications/components.tsx
  packages/mco/components/protected-applications/list-page.tsx
  packages/mco/components/protected-applications/protected-apps.scss
  packages/mco/components/protected-applications/utils.tsx
  packages/shared/src/index.ts
  packages/shared/src/list-page/index.ts
  packages/shared/src/list-page/paginated-list-page.tsx
  packages/shared/src/table/composable-table.tsx
Labels: approved, lgtm
