Repository red-hat-storage/odf-console, pull requests merged in 2024-04, with the labels that each got.

#1277 Adds missing features for Provider mode
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/list-filter.ts
  packages/odf/components/storage-consumers/remove-client-modal.tsx
  packages/odf/components/storage-consumers/rotate-keys-modal.tsx
  packages/odf/components/utils/common.ts
  packages/shared/src/types/storage.ts
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#1263 Bug 2270472: [release-4.15] Remove TP badge for Multus
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#1275 fix 'catastrophic backtracking' issue with text-input regex
  packages/shared/src/utils/validation.ts
Labels: approved, lgtm

#1276 fix issue with rbd (checkbox) state reset when navigating back
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/set-rbd-sc-default.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/set-rbd-sc-default.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
Labels: approved, lgtm

#1272 Kebab menu fix for DRPolicy
  packages/mco/components/drpolicy-list-page/helper.ts
  packages/shared/src/kebab/kebab.tsx
Labels: approved, lgtm

#1281 Removing ODR_MODEL flag check from console-extensions.json
  plugins/mco/console-extensions.json
Labels: approved, lgtm

#1296 Updates console sdk packages
  package.json
  yarn.lock
Labels: approved, lgtm

#1280 Storage System: Get nodes' memory from metrics
  .eslintrc.js
  .prettierignore
  jest/config.js
  jest/helpers.ts
  jest/setup.ts
  locales/en/plugin__odf-console.json
  package.json
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/getting-started-card/getting-started-card.spec.tsx
  packages/mco/components/modals/app-failover-relocate/parser/discovered-application-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/protected-applications/managed-applications-modal.spec.tsx
  packages/mco/components/protected-applications/protected-apps-list-page.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/selected-capacity.tsx
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table.spec.tsx
  packages/odf/components/create-storage-system/select-nodes-table/select-nodes-table.tsx
  packages/odf/components/kms-config/azure-config.spec.tsx
  packages/odf/components/utils/common.ts
  packages/odf/hooks/index.ts
  packages/odf/hooks/useNodesData.spec.ts
  packages/odf/hooks/useNodesData.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
  packages/odf/types/common.ts
  packages/odf/utils/ocs.spec.ts
  packages/odf/utils/ocs.ts
  packages/shared/src/queries/node.ts
  packages/shared/src/status/icons.spec.tsx
  setupJest.ts
Labels: approved, lgtm

#1297 Fixes issues of Topology page breaking when ownerRef is absent
  packages/odf/components/topology/utils.ts
  packages/shared/src/topology/utils/resource.ts
Labels: approved, lgtm

#1273 calculate uptime using metrics for averages
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
  packages/ocs/queries/ceph-storage.ts
  packages/shared/src/constants/prometheus.ts
  packages/shared/src/dashboards/utilization-card/area-chart.tsx
  packages/shared/src/details-page/datetime.ts
Labels: approved, lgtm

#1293 read deployment cluster from DRPC in case of hub recovery
  packages/mco/components/mco-dashboard/disaster-recovery/parsers/subscription-parser.tsx
  packages/mco/components/modals/app-failover-relocate/parser/discovered-application-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.tsx
Labels: approved, lgtm

#1309 Remove proxy call for rotation of signing keys
  packages/odf/components/storage-consumers/rotate-keys-modal.tsx
Labels: approved, lgtm

#1269 Count namespace protected DRPC as one application
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/utils/k8s-utils.ts
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/drpolicy-list-page/helper.ts
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.scss
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.tsx
  packages/mco/hooks/applications-hook.ts
  packages/mco/hooks/index.ts
  packages/mco/hooks/protected-applications.ts
  packages/mco/types/ramen.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#1318 Bug 2275254: [release-4.16] Count namespace protected DRPC as one app
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/utils/k8s-utils.ts
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/drpolicy-list-page/helper.ts
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.scss
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.tsx
  packages/mco/hooks/applications-hook.ts
  packages/mco/hooks/index.ts
  packages/mco/hooks/protected-applications.ts
  packages/mco/types/ramen.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1319 Bug 2275254: [release-4.16-compatibility] Count namespace protected DRPC as one application
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/utils/k8s-utils.ts
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/drpolicy-list-page/helper.ts
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.scss
  packages/mco/components/modals/connected-apps-modal/connected-apps-modal.tsx
  packages/mco/hooks/applications-hook.ts
  packages/mco/hooks/index.ts
  packages/mco/hooks/protected-applications.ts
  packages/mco/types/ramen.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1312 account for multiple mgrs in the storage system
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
Labels: approved, lgtm

#1323 Remove project dropdown from SS create page
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/odf/components/create-storage-system/header.tsx
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#1325 Edit labels - error message improvement
  locales/en/plugin__odf-console.json
  packages/shared/src/modals/EditLabelModal.tsx
Labels: approved, lgtm

#1327 Fix CSS issue with RBD image state
  packages/ocs/dashboards/block-pool/mirroring-card.tsx
Labels: approved, lgtm

#1278 Fixes i18n missing
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/noobaa-external-postgres/postgres-connection-details.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
Labels: approved, lgtm

#1324 [MDR] Should not allow to create a 2nd DR policy on existing cluster pair
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
Labels: approved, lgtm

#1295 Kubernetes objects Sync status fix
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.spec.tsx
  packages/mco/components/discovered-application-wizard/utils/k8s-utils.ts
  packages/mco/components/discovered-application-wizard/wizard-steps/namespace-step/namesapce-table.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/application.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/parsers/discovered-parser.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/parser/discovered-application-parser.tsx
  packages/mco/components/modals/app-manage-policies/policy-list-view.tsx
  packages/mco/components/protected-applications/components.tsx
  packages/mco/components/protected-applications/list-page.tsx
  packages/mco/components/protected-applications/protected-apps-list-page.spec.tsx
  packages/mco/components/protected-applications/utils.tsx
  packages/mco/constants/common.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/dashboard.ts
  packages/mco/types/ramen.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#1340 use subqueries to aggregate before delta
  packages/ocs/queries/ceph-storage.ts
Labels: approved, lgtm

#1344 Bug 2277184: [release-4.16-compatibility] Kebab menu fix for DRPolicy
  packages/mco/components/drpolicy-list-page/helper.ts
  packages/shared/src/kebab/kebab.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1345 Bug 2277184: [release-4.16] Kebab menu fix for DRPolicy
  packages/mco/components/drpolicy-list-page/helper.ts
  packages/shared/src/kebab/kebab.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
