Repository red-hat-storage/odf-console, pull requests merged in 2024-10, with the labels that each got.

#1607 Update OWNERS file
  OWNERS
Labels: approved, lgtm

#1608 Add 'Create Bucket' form (via S3-compat API)
  locales/en/plugin__odf-console.json
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/s3-browser/create-bucket/CreateBucket.tsx
  packages/odf/components/s3-browser/create-bucket/CreateBucketForm.tsx
  packages/odf/components/s3-browser/create-bucket/create-bucket-form.scss
  packages/odf/components/s3-browser/create-bucket/useS3BucketFormValidation.ts
  packages/odf/constants/s3-browser.ts
  packages/shared/src/constants/fieldRequirements.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/utils/NameValueEditor.tsx
Labels: approved, lgtm

#1604 Add object actions - presigned URL, download and preview
  locales/en/plugin__odf-console.json
  package.json
  packages/odf/components/s3-browser/bucket-overview/BucketOverview.tsx
  packages/odf/components/s3-browser/bucket-overview/PageTitle.tsx
  packages/odf/components/s3-browser/download-and-preview/download-and-preview.ts
  packages/odf/components/s3-browser/objects-list/ObjectsList.tsx
  packages/odf/components/s3-browser/objects-list/table-components.tsx
  packages/odf/modals/s3-browser/presigned-url/PresignedURLModal.tsx
  packages/odf/modals/s3-browser/presigned-url/presigned-modal.scss
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/utils/common.ts
  yarn.lock
Labels: approved, lgtm

#1611 Bug 2312137: [release-4.17] Fix DR optimization check flag
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/types/odf-mco.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1613 Bug 2312137: [release-4.17-compatibility] Fix DR optimization check flag
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/types/odf-mco.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1612 Create S3 Bucket form cleanup
  packages/odf/components/s3-browser/create-bucket/CreateBucketForm.tsx
Labels: approved, lgtm

#1617 Hide In-transit Encryption checkbox when MCG deployment mode is selected
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
Labels: approved, lgtm

#1614 Reset radio button when Provider mode is selected from dropdown
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
Labels: approved, lgtm

#1620 Fetch external cluster python script from Rook CM
  packages/odf/components/create-storage-system/external-ceph-storage/system-connection-details.tsx
  packages/shared/src/constants/common.ts
Labels: approved, lgtm

#1582 Bug 2308217: [release-4.15-compatibility] Security: fix webpack version
  package.json
  yarn.lock
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1626 Fix bundle analyzer script
  .eslintrc.js
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm

#1619 Adds support for new volume modes in IBM flashsystem
  locales/en/plugin__odf-console.json
  packages/ibm/system-connection-details.tsx
Labels: approved, lgtm

#1610 Add object actions - create folder and delete object(s)
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/objects-list/ObjectsList.tsx
  packages/odf/components/s3-browser/objects-list/table-components.tsx
  packages/odf/modals/s3-browser/create-folder/CreateFolderModal.tsx
  packages/odf/modals/s3-browser/delete-objects/DeleteObjectsModal.tsx
  packages/odf/modals/s3-browser/delete-objects/DeleteObjectsSummary.tsx
  packages/odf/modals/s3-browser/delete-objects/LazyDeleteModals.ts
  packages/odf/modals/s3-browser/delete-objects/delete-objects.scss
  packages/odf/utils/s3-browser.ts
  packages/shared/src/list-page/ListFilter.tsx
  packages/shared/src/list-page/index.ts
  packages/shared/src/list-page/paginated-list-page.tsx
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/status/icons.tsx
  packages/shared/src/table/composable-table.tsx
Labels: approved, lgtm

#1598 RHSTOR-6195: Bucket - list page
  locales/en/plugin__odf-console.json
  package.json
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.tsx
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
  packages/mco/components/protected-applications/components.tsx
  packages/odf/components/s3-browser/buckets-list-page/bucketListTable.tsx
  packages/odf/components/s3-browser/buckets-list-page/bucketPagination.tsx
  packages/odf/components/s3-browser/buckets-list-page/bucketsListPage.tsx
  packages/odf/components/s3-browser/objects-list/ObjectsList.tsx
  packages/odf/components/s3-browser/pagination-helper.tsx
  packages/odf/constants/s3-browser.ts
  packages/odf/features.ts
  packages/odf/types/s3-browser.ts
  packages/odf/utils/s3-browser.ts
  packages/shared/src/details-page/timestamp.tsx
  packages/shared/src/empty-state-page/empty-page.scss
  packages/shared/src/empty-state-page/empty-page.tsx
  packages/shared/src/empty-state-page/index.ts
  packages/shared/src/hooks/index.ts
  packages/shared/src/hooks/useUserSettingsLocalStorage.ts
  packages/shared/src/index.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/table/composable-table.tsx
  packages/shared/src/utils/table.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
  yarn.lock
Labels: approved, lgtm, jira/valid-reference

#1634 Search objects by prefix
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/objects-list/ObjectsList.tsx
  packages/odf/constants/s3-browser.ts
  packages/odf/utils/s3-browser.ts
Labels: approved, lgtm

#1638 TypeScript Lint: don't allow unused params
  .eslintrc.js
  cypress/tests/multiple-storageclass-selection.spec.ts
  cypress/views/multiple-storageclass.ts
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/components/bucket-class/time-duration-dropdown.tsx
  packages/odf/components/bucket-class/wizard-pages/namespace-store-pages/cache-namespace-store.tsx
  packages/odf/components/bucket-class/wizard-pages/placement-policy-page.tsx
  packages/odf/components/kms-config/utils.tsx
  packages/odf/components/topology/TopBar/SearchComponent.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/odf/components/utils/common.ts
  packages/odf/features.ts
  packages/odf/modals/advanced-kms-modal/advanced-vault-modal.tsx
  packages/odf/modals/configure-mons/configure-mons.tsx
  packages/shared/src/charts/tooltip.tsx
  packages/shared/src/details-page/DetailsPage.tsx
  packages/shared/src/details-page/datetime.ts
  packages/shared/src/hooks/sort-list.ts
  packages/shared/src/utils/node.ts
  tsconfig.json
Labels: approved, lgtm

#1609 Add encryption configuration details to ODF dashboard
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/common/details-card/encryption-popover.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/odf/constants/kms.ts
  packages/shared/src/status/icons.tsx
Labels: approved, lgtm

#1636 Bucket Details Page: add 'Bucket overview' + OB Details
  locales/en/plugin__odf-console.json
  packages/odf/components/mcg/ObjectBucket.tsx
  packages/odf/components/s3-browser/bucket-details/BucketDetails.tsx
  packages/odf/components/s3-browser/bucket-overview/BucketOverview.tsx
  packages/odf/constants/s3-browser.ts
  packages/shared/src/details-page/DetailsPage.tsx
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
Labels: approved, lgtm

#1644 Fix object preview
  packages/odf/components/s3-browser/download-and-preview/download-and-preview.ts
Labels: approved, lgtm

#1645 Create Bucket Form: set OBC method as default
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/create-bucket/CreateBucket.tsx
Labels: approved, lgtm

#1649 Bug 2312118: Fix 'Not Found' error with encryption form
  packages/ocs/storage-class/sc-form.tsx
  packages/shared/src/utils/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#1589 RHSTOR-6347: Enable recipe-based DR enrollment for discovered applications
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.spec.tsx
  packages/mco/components/discovered-application-wizard/wizard-steps/configuration-step/configuration-step.tsx
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/shared/src/table/selectable-table.tsx
Labels: approved, lgtm, jira/valid-reference

#1643 RHSTOR-6558: Enhance the DRPolicy creation page to select client clusters for RDR
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.scss
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/select-cluster-list.scss
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-validator.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/components/create-dr-policy/utils/cluster-list-utils.ts
  packages/mco/components/create-dr-policy/utils/k8s-utils.ts
  packages/mco/components/create-dr-policy/utils/reducer.ts
  packages/mco/constants/acm.ts
  packages/shared/src/table/selectable-table.tsx
Labels: approved, lgtm, jira/valid-reference

#1646 Display non-blocking warnings for synchronization delays
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/helper/error-messages.tsx
  packages/mco/components/modals/app-failover-relocate/parser/argo-application-set-parser.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/dr-policy-selector.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/error-messages.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/peer-cluster-status.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/reducer.ts
  packages/mco/components/protected-applications/list-page.tsx
  packages/mco/components/protected-applications/utils.tsx
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm
