Repository red-hat-storage/odf-console, pull requests merged in 2024-07, with the labels that each got.

#1416 adding option to flatten pvc clone during drpolicy creation
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/constants/disaster-recovery.ts
Labels: approved, lgtm

#1457 Hide 'Provider Mode' deployment for ODF
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
  packages/odf/redux/provider-hooks/useODFNamespace.ts
Labels: approved, lgtm

#1452 Add support for MCG in client console
  packages/client/package.json
  packages/client/src/components/mcg/index.ts
  packages/client/src/features.ts
  packages/odf/components/mcg/index.ts
  packages/odf/redux/provider-hooks/useODFNamespace.ts
  plugins/client/console-extensions.json
  plugins/client/console-plugin.json
Labels: approved, lgtm

#1462 Add missing snapshot sync info for AppSet
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster-app-card.tsx
Labels: approved, lgtm

#1424 Add support for French & Spanish locales
  locales/es/plugin__odf-console.json
  locales/fr/plugin__odf-console.json
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
  scripts/i18n/common.js
  scripts/i18n/i18n-to-po.js
  scripts/i18n/languages.sh
  webpack.config.ts
Labels: approved, lgtm

#1465 Add yarn script: dev:no-type-check
  package.json
  webpack.config.ts
Labels: approved, lgtm

#1460 Syncing latest changes from master for odf-console
  locales/en/plugin__odf-console.json
  locales/es/plugin__odf-console.json
  locales/fr/plugin__odf-console.json
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
  packages/client/package.json
  packages/client/src/components/mcg/index.ts
  packages/client/src/features.ts
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster-app-card.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/useLSOProvisionedVolumes.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/useVolumeTypeValidation.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/create-local-volume-set-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/selected-capacity.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/useLSODiscoveredDisks.ts
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/mcg/index.ts
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/components/utils/common.ts
  packages/odf/components/utils/index.ts
  packages/odf/components/utils/lso.ts
  packages/odf/constants/lso.ts
  packages/odf/hooks/index.ts
  packages/odf/hooks/useLSODiskDiscovery.ts
  packages/odf/hooks/useNodesData.ts
  packages/odf/redux/provider-hooks/useODFNamespace.ts
  packages/odf/types/common.ts
  packages/odf/types/lso.ts
  packages/odf/utils/lso.ts
  packages/odf/utils/ocs.ts
  packages/shared/src/dropdown/multiselectdropdown.tsx
  packages/shared/src/dropdown/singleselectdropdown.tsx
  packages/shared/src/hooks/use-fetch-csv.tsx
  packages/shared/src/utils/csv-status.tsx
  plugins/client/console-extensions.json
  plugins/client/console-plugin.json
  scripts/i18n/common.js
  scripts/i18n/i18n-to-po.js
  scripts/i18n/languages.sh
  webpack.config.ts
Labels: approved, lgtm

#1467 add 'Yup' schema support to 'odf.wizard/storageclass' extension
  locales/en/plugin__odf-console.json
  packages/ibm/package.json
  packages/ibm/system-connection-details.tsx
  packages/ocs/package.json
  packages/odf-plugin-sdk/extensions/external-storage/README.md
  packages/odf-plugin-sdk/extensions/external-storage/external-storage.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/create-storage-class-step/create-storage-class-step.tsx
  packages/odf/package.json
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#1456 Remove Provider mode guard for In transit encryption checkbox
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
Labels: approved, lgtm

#1423 Update activity card for bluestore-rdr to bluestore migration
  cypress/support.ts
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/constants/acm.ts
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.spec.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/ocs/utils/osd-migration.ts
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/data-protection-step/data-protection-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/index.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/data-protection.ts
Labels: approved, lgtm

#1471 Publish latest 'odf-console/shared'
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm

#1473 Fix CVE-2024-28863 for node-tar issue
  package.json
  yarn.lock
Labels: approved, lgtm

#1466 Provider mode: Set storage quota on storage clients
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
  packages/ocs/dashboards/persistent-internal/raw-capacity-card/raw-capacity-card.tsx
  packages/odf/components/storage-consumers/client-list.scss
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/onboarding-modal.scss
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/components/storage-consumers/remove-client-modal.tsx
  packages/odf/components/storage-consumers/update-storage-quota-modal.tsx
  packages/odf/constants/tooltips.tsx
  packages/odf/hooks/index.ts
  packages/odf/hooks/useRawCapacity.ts
  packages/odf/types/index.ts
  packages/odf/types/storage-consumer.ts
  packages/odf/utils/storage.ts
  packages/shared/src/generic/FieldLevelHelp.tsx
  packages/shared/src/status/icons.tsx
  packages/shared/src/types/storage.ts
  packages/shared/src/utils/metrics.ts
  tsconfig.json
Labels: approved, lgtm

#1472 Syncing latest changes from master for odf-console
  cypress/support.ts
  locales/en/plugin__odf-console.json
  package.json
  packages/ibm/package.json
  packages/ibm/system-connection-details.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/constants/acm.ts
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.spec.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/ocs/package.json
  packages/ocs/utils/osd-migration.ts
  packages/odf-plugin-sdk/extensions/external-storage/README.md
  packages/odf-plugin-sdk/extensions/external-storage/external-storage.ts
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-storage-class-step/create-storage-class-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/data-protection-step/data-protection-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/index.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/data-protection.ts
  packages/odf/package.json
  packages/shared/package.json
  plugins/odf/console-extensions.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#1474 Fix storage pool description visibility in modal
  packages/ocs/modals/storage-pool/create-storage-pool-modal.tsx
  packages/ocs/modals/storage-pool/storage-pool-modal.scss
  packages/ocs/modals/storage-pool/update-storage-pool-modal.tsx
Labels: approved, lgtm

#1476 Annotate RBD storageclasses for keyrotation
  packages/ocs/storage-class/mutators.ts
Labels: approved, lgtm

#1480 Syncing latest changes from master for odf-console
  locales/en/plugin__odf-console.json
  package.json
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
  packages/ocs/dashboards/persistent-internal/raw-capacity-card/raw-capacity-card.tsx
  packages/ocs/modals/storage-pool/create-storage-pool-modal.tsx
  packages/ocs/modals/storage-pool/storage-pool-modal.scss
  packages/ocs/modals/storage-pool/update-storage-pool-modal.tsx
  packages/odf/components/storage-consumers/client-list.scss
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/onboarding-modal.scss
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/components/storage-consumers/remove-client-modal.tsx
  packages/odf/components/storage-consumers/update-storage-quota-modal.tsx
  packages/odf/constants/tooltips.tsx
  packages/odf/hooks/index.ts
  packages/odf/hooks/useRawCapacity.ts
  packages/odf/types/index.ts
  packages/odf/types/storage-consumer.ts
  packages/odf/utils/storage.ts
  packages/shared/src/generic/FieldLevelHelp.tsx
  packages/shared/src/status/icons.tsx
  packages/shared/src/types/storage.ts
  packages/shared/src/utils/metrics.ts
  tsconfig.json
  yarn.lock
Labels: approved, lgtm

#1475 Bug 2297295: Hide builtin-mgr CephBlockPool
  packages/ocs/storage-class/sc-form.tsx
  packages/ocs/storage-pool/StoragePoolListPage.tsx
  packages/odf/resources.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#1482 Cleanup: remove duplicated resource models
  packages/mco/components/mco-dashboard/storage-system/status-card/status-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/hooks/useOcsHealth.ts
  packages/ocs/modals/storage-pool/create-storage-pool-modal.tsx
  packages/ocs/modals/storage-pool/delete-storage-pool-modal.tsx
  packages/ocs/modals/storage-pool/update-storage-pool-modal.tsx
  packages/ocs/models/core.ts
  packages/ocs/storage-pool/BlockPoolDetailsPage.tsx
  packages/ocs/storage-pool/CreateStoragePool.tsx
  packages/ocs/storage-pool/body.tsx
  packages/ocs/utils/storage-pool.tsx
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/components/cluster-overview-extensions/ClusterExpansion.tsx
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/external-ceph-storage/system-connection-details.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/odf/components/topology/utils.ts
  packages/odf/features.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
  packages/odf/redux/provider-hooks/useODFSystemFlags.ts
  packages/odf/resources.ts
  packages/shared/src/models/common.ts
  packages/shared/src/models/storage.ts
  packages/shared/src/topology/factory/StyleGroup.tsx
  packages/shared/src/topology/utils/AlertFilters.ts
  packages/shared/src/utils/storage.ts
Labels: approved, lgtm

#1477 DFBUGS-24: Bump webpack-bundle-analyzer, jest-environment-jsdom & webpack-dev-server
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-reference

#1483 tsconfig: set '@odf' path mapping correctly
  packages/mco/components/modals/remove-disaster-recovery/remove-disaster-recovery.tsx
  packages/ocs/modals/storage-pool/delete-storage-pool-modal.tsx
  tsconfig.json
Labels: approved, lgtm

#1469 support negative values in humanizeBinaryBytes
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
  packages/shared/src/dashboards/utilization-card/area-chart.tsx
  packages/shared/src/dashboards/utilization-card/prometheus-utilization-item.tsx
  packages/shared/src/dashboards/utilization-card/utilization-item.tsx
  packages/shared/src/generic/FieldLevelHelp.tsx
  packages/shared/src/utils/humanize.js
Labels: approved, lgtm

#1470 Bug 2297447: Use ManagedClusterView for ODF info - DRPolicy creation
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/discovered-application-wizard/utils/reducer.ts
  packages/mco/components/discovered-application-wizard/wizard-steps/configuration-step/recipe-selection.tsx
  packages/mco/constants/acm.ts
  packages/mco/constants/common.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/odf-mco.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1492 Syncing latest changes from master for odf-console
  locales/en/plugin__odf-console.json
  package.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/discovered-application-wizard/utils/reducer.ts
  packages/mco/components/discovered-application-wizard/wizard-steps/configuration-step/recipe-selection.tsx
  packages/mco/components/mco-dashboard/storage-system/status-card/status-card.tsx
  packages/mco/components/modals/remove-disaster-recovery/remove-disaster-recovery.tsx
  packages/mco/constants/acm.ts
  packages/mco/constants/common.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/odf-mco.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/hooks/useOcsHealth.ts
  packages/ocs/modals/storage-pool/create-storage-pool-modal.tsx
  packages/ocs/modals/storage-pool/delete-storage-pool-modal.tsx
  packages/ocs/modals/storage-pool/update-storage-pool-modal.tsx
  packages/ocs/models/core.ts
  packages/ocs/storage-class/mutators.ts
  packages/ocs/storage-class/sc-form.tsx
  packages/ocs/storage-pool/BlockPoolDetailsPage.tsx
  packages/ocs/storage-pool/CreateStoragePool.tsx
  packages/ocs/storage-pool/StoragePoolListPage.tsx
  packages/ocs/storage-pool/body.tsx
  packages/ocs/utils/storage-pool.tsx
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/components/cluster-overview-extensions/ClusterExpansion.tsx
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/external-ceph-storage/system-connection-details.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
  packages/odf/components/topology/utils.ts
  packages/odf/features.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
  packages/odf/redux/provider-hooks/useODFSystemFlags.ts
  packages/odf/resources.ts
  packages/shared/src/dashboards/utilization-card/area-chart.tsx
  packages/shared/src/dashboards/utilization-card/prometheus-utilization-item.tsx
  packages/shared/src/dashboards/utilization-card/utilization-item.tsx
  packages/shared/src/generic/FieldLevelHelp.tsx
  packages/shared/src/models/common.ts
  packages/shared/src/models/storage.ts
  packages/shared/src/topology/factory/StyleGroup.tsx
  packages/shared/src/topology/utils/AlertFilters.ts
  packages/shared/src/utils/humanize.js
  packages/shared/src/utils/storage.ts
  tsconfig.json
  yarn.lock
Labels: approved, lgtm

#1489 Provider Mode: Object Dashboard: fix RGW performance card
  packages/ocs/dashboards/object-service/data-consumption-card/data-consumption-card.tsx
  packages/ocs/dashboards/object-service/data-consumption-card/performance-graph.tsx
  packages/shared/src/details-page/datetime.ts
Labels: approved, lgtm

#1301 Bug 2270492: [release-4.14] Remove TP badge for Multus
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1496 GH action: trigger build workflow on any release PR
  .github/workflows/frontend-build.yml
Labels: approved, lgtm
