Repository red-hat-storage/odf-console, pull requests merged in 2024-09, with the labels that each got.

#1556 Fix label overriding issue when same label is used with different values
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/utils/common.ts
Labels: approved, lgtm

#1451 Bug 2290863: [release-4.15] Fix dashboard queries (Inventory + Capacity + Utilization cards)
  packages/client/src/components/dashboards/cards/inventory-card.tsx
  packages/ocs/constants/common.ts
  packages/ocs/dashboards/persistent-external/breakdown-card.tsx
  packages/ocs/dashboards/persistent-external/utilization-card.tsx
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx
  packages/ocs/dashboards/persistent-internal/inventory-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
  packages/ocs/hooks/index.ts
  packages/ocs/hooks/useStorageClassQueryFilter.ts
  packages/ocs/queries/ceph-storage.spec.ts
  packages/ocs/queries/ceph-storage.ts
  packages/ocs/utils/common.ts
  packages/shared/src/constants/index.ts
  packages/shared/src/constants/k8s.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1454 Bug 2290863: [release-4.15-compatibility] Fix dashboard queries (Inventory + Capacity + Utilization cards)
  packages/client/src/components/dashboards/cards/inventory-card.tsx
  packages/ocs/constants/common.ts
  packages/ocs/dashboards/persistent-external/breakdown-card.tsx
  packages/ocs/dashboards/persistent-external/utilization-card.tsx
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx
  packages/ocs/dashboards/persistent-internal/inventory-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
  packages/ocs/hooks/index.ts
  packages/ocs/hooks/useStorageClassQueryFilter.ts
  packages/ocs/queries/ceph-storage.spec.ts
  packages/ocs/queries/ceph-storage.ts
  packages/ocs/utils/common.ts
  packages/shared/src/constants/index.ts
  packages/shared/src/constants/k8s.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1567 Adds optional chaining for label selector in topology view
  packages/odf/components/topology/utils.ts
Labels: approved, lgtm

#1565 Bug 2310154: [release-4.15] Fix tar CVE issue
  package.json
  yarn.lock
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1566 Bug 2310154: [release-4.15-compatibility] Fix tar CVE issue
  package.json
  yarn.lock
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1569 Add initial setup for AWS S3 SDK
  package.json
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/odf/constants/index.ts
  packages/odf/constants/s3-browser.ts
  packages/shared/src/models/console-models.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/index.ts
  packages/shared/src/s3/types.ts
  yarn.lock
Labels: approved, lgtm

#1575 Bug 2311867: [release-4.17] Prepare cluster for disaster recovery
  cypress/support.ts
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.spec.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-modal.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/ocs/utils/osd-migration.ts
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/data-protection-step/data-protection-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/index.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/data-protection.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#1585 Bug 2311867: [release-4.17-compatibility] Prepare cluster for disaster recovery
  cypress/support.ts
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.spec.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/cluster-migration-activity.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-modal.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/ocs/utils/osd-migration.ts
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/data-protection-step/data-protection-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/index.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/data-protection.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#1590 Block creation of external mode when Provider mode is already present
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
Labels: approved, lgtm

#1549 Bug 2304905: [release-4.16-compatibility] Add cluster name and id on clients' list page
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/client-list.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1548 Bug 2304905: [release-4.16] Add cluster name and id on clients' list page
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/client-list.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1594 Create Bucket page: display CreateOBC form.
  locales/en/plugin__odf-console.json
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/s3-browser/create-bucket/CreateBucket.tsx
  packages/shared/src/dropdown/ResourceDropdown.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1597 Fix flaky E2E test
  cypress/views/storage-pool.ts
Labels: approved, lgtm

#1599 Sanity checks: ensure client plugin build is healthy
  .github/workflows/frontend-build.yml
  package.json
Labels: approved, lgtm

#1586 Bug 2312137: [release-4.17-compatibility] RDR optimization check for the ODF cluster
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/types/odf-mco.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1579 Bug 2312137: [release-4.17] RDR optimization check for the ODF cluster
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/reducer.ts
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-view.tsx
  packages/mco/types/odf-mco.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1591 Add buckets overview page (header, details/objects list tabs, actions) layout
  locales/en/plugin__odf-console.json
  package.json
  packages/odf/components/s3-browser/bucket-overview/BucketOverview.tsx
  packages/odf/components/s3-browser/bucket-overview/PageTitle.tsx
  packages/odf/components/s3-browser/bucket-overview/bucket-overview.scss
  packages/odf/components/s3-browser/objects-list/ObjectsList.tsx
  packages/odf/components/s3-browser/objects-list/index.ts
  packages/odf/components/s3-browser/objects-list/table-components.tsx
  packages/odf/constants/s3-browser.ts
  packages/odf/types/index.ts
  packages/odf/types/s3-browser.ts
  packages/odf/utils/index.ts
  packages/odf/utils/s3-browser.ts
  packages/shared/src/hooks/index.ts
  packages/shared/src/hooks/useRefresh.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/table/selectable-table.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
  yarn.lock
Labels: approved, lgtm
