Repository red-hat-storage/odf-console, pull requests merged in 2024-12, with the labels that each got.

#1753 [DR] Fix assign policy wizard PVC selection step issue
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
Labels: approved, lgtm

#1755 Fix warning message is triggered for healthy replication
  packages/mco/__mocks__/drplacementcontrol.tsx
  packages/mco/components/modals/app-failover-relocate/parser/argo-application-set-parser.spec.tsx
  packages/mco/components/modals/app-failover-relocate/parser/discovered-application-parser.spec.tsx
  packages/mco/components/modals/app-failover-relocate/parser/discovered-application-parser.tsx
Labels: approved, lgtm

#1732 Moves upload component to mobX
  .eslintrc.js
  package.json
  packages/odf/components/s3-browser/objects-list/ObjectListWithSidebar.tsx
  packages/odf/components/s3-browser/upload-objects/UploadSidebar.tsx
  packages/odf/components/s3-browser/upload-objects/store.ts
  packages/odf/components/s3-browser/upload-objects/types.ts
  packages/odf/components/s3-browser/upload-objects/upload-component/FileUploadComponent.tsx
  packages/odf/components/s3-browser/upload-objects/upload-component/uploads.ts
  packages/odf/components/s3-browser/upload-objects/upload-status/UploadStatusBasedAlert.tsx
  packages/odf/components/s3-browser/upload-objects/upload-status/UploadStatusItem.tsx
  packages/odf/components/s3-browser/upload-objects/upload-status/UploadStatusList.tsx
  packages/odf/components/s3-browser/upload-objects/utils.ts
  packages/odf/modals/s3-browser/abort-uploads/AbortUploadsModal.tsx
  yarn.lock
Labels: approved, lgtm

#1765 [CVE] Improper input validation in PostCSS
  package.json
  yarn.lock
Labels: approved, lgtm

#1627 DFBUGS-317: [release-4.14] Security: fix webpack version
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1709 DFBUGS-922: [release-4.15-compatibility] Fix security issue: Backtracking regular expressions
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1628 DFBUGS-317: [release-4.14-compatibility] Security: fix webpack version
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1719 Bug DFBUGS-934: [release-4.15] Tough-cookie: prototype pollution in cookie memstore
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1727 Bug DFBUGS-608: [release-4.14] css-tools: Improper Input Validation causes Denial of Service via Regular Expression
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1720 Bug DFBUGS-934: [release-4.15-compatibility] Tough-cookie: prototype pollution in cookie memstore
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1710 DFBUGS-923: [release-4.14] Fix security issue: Backtracking regular expressions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1711 DFBUGS-923: [release-4.14-compatibility] Fix security issue: Backtracking regular expressions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1764 Add translations for 4.18 release
  locales/es/plugin__odf-console.json
  locales/fr/plugin__odf-console.json
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
Labels: approved, lgtm

#1708 DFBUGS-922: [release-4.15] Fix security issue: Backtracking regular expressions
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1782 Navigate to buckets' list page on deletion
  packages/odf/modals/s3-browser/delete-and-empty-bucket/DeleteBucketModal.tsx
Labels: approved, lgtm

#1783 Fix 'nanoid' CVE
  package.json
  yarn.lock
Labels: approved, lgtm

#1777 Bug DFBUGS-922: [release-4.15] Reverting back CVE fix for DFBUGS-922 and DFBUGS-934
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1776 Bug DFBUGS-923: [release-4.14-compatibility] Reverting back CVE fix for DFBUGS-923
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1797 DFBUGS-923: [release-4.14-compatibility] Revert: Reverting fix for DFBUGS-923
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1798 DFBUGS-922: [release-4.15] Revert: Reverting CVE fix for DFBUGS-922 and DFBUGS-934
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1728 Bug DFBUGS-608: [release-4.14-compatibility] css-tools: Improper Input Validation causes Denial of Service via Regular Expression
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1799 DFBUGS-922: [release-4.15-compatibility] Revert: Reverting fix for DFBUGS-922 …
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1726 Bug DFBUGS-936: [release-4.15-compatibility] css-tools: Improper Input Validation causes Denial of Service via Regular Expression
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1793 DFBUGS-1020: [release-4.17] Fix 'nanoid' CVE
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1796 DFBUGS-1019: [release-4.16-compatibility] Fix 'nanoid' CVE
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1794 DFBUGS-1020: [release-4.17-compatibility] Fix 'nanoid' CVE
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1630 DFBUGS-461: [release-4.16] Fix security issue: Backtracking regular expressions
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, bugzilla/severity-medium, lgtm, bugzilla/invalid-bug, jira/valid-bug, jira/valid-reference

#1633 DFBUGS-461: [release-4.16-compatibility] Fix security issue: Backtracking regular expressions
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#1718 Bug DFBUGS-935: [release-4.16-compatibility] CVE tough-cookie: prototype pollution in cookie memstore
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1725 Bug DFBUGS-936: [release-4.15] css-tools: Improper Input Validation causes Denial of Service via Regular Expression
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1745 DFBUGS-810: [release-4.17] Fix 'cross-spawn' CVE
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1746 DFBUGS-810: [release-4.17-compatibility] Fix 'cross-spawn' CVE
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1717 Bug DFBUGS-935: [release-4.16] CVE tough-cookie: prototype pollution in cookie memstore
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1724 Bug DFBUGS-937: [release-4.16-compatibility] CVE css-tools: Improper Input Validation causes Denial of Service via Regular Expression
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1723 DFBUGS-937: [release-4.16] CVE css-tools: Improper Input Validation causes Denial of Service via Regular Expression
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1747 DFBUGS-809: [release-4.16] Fix 'cross-spawn' CVE
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1748 DFBUGS-809: [release-4.16-compatibility] Fix 'cross-spawn' CVE
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1721 Bug DFBUGS-933: [release-4.14]tough-cookie: prototype pollution in cookie memstore
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1800 Revert "[release-4.16-compatibility] DFBUGS-713: Block creation of external mode when Provider mode is already present"
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
