Repository red-hat-storage/odf-console, pull requests merged in 2024-08, with the labels that each got.

#1510 Provider mode: Storage Client list: remove 'Used Capacity' column
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/client-list.tsx
  packages/shared/src/types/storage.ts
Labels: approved, lgtm

#1519 Fix nodes' label for ROSA clusters
  packages/ocs/dashboards/persistent-internal/inventory-card.tsx
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/constants/common.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/redux/provider-hooks/useODFNamespace.ts
  packages/shared/src/constants/common.ts
Labels: approved, lgtm

#1484 Update Sync Status Message for Application Volumes (PVCs)
  locales/en/plugin__odf-console.json
  packages/mco/components/protected-applications/components.tsx
  packages/mco/components/protected-applications/list-page.tsx
  packages/mco/components/protected-applications/utils.tsx
Labels: approved, lgtm

#1515 CVE-2023-26136 odf-multicluster-console-container: tough-cookie: prototype pollution in cookie memstore
  package.json
  yarn.lock
Labels: approved, lgtm

#1518 CVE - css-tools: Improper Input Validation causes Denial of Service via Regular Expression
  package.json
  yarn.lock
Labels: approved, lgtm

#1520 Optimizing the chunk size using devtool
  webpack.config.ts
Labels: approved, lgtm

#1529 Fix custom storage quota (value input)
  packages/shared/src/utils/RequestSizeInput.tsx
Labels: approved, lgtm

#1546 Bug 2304993: [release-4.17] Optimizing the chunk size for production
  webpack.config.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1547 Bug 2304993: [release-4.17-compatibility] Optimizing the chunk size for production
  webpack.config.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1544 Optimizing the chunk size for production
  webpack.config.ts
Labels: approved, lgtm

#1375 Updated the clean up application resource message
  locales/en/plugin__odf-console.json
  packages/mco/__mocks__/drplacementcontrol.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/application.tsx
  packages/mco/components/protected-applications/components.tsx
  packages/mco/components/protected-applications/list-page.tsx
  packages/mco/components/protected-applications/utils.tsx
  packages/mco/types/ramen.ts
Labels: approved, lgtm

#1541 Attach OBC to Deployment - fix incorrect validations
  locales/en/plugin__odf-console.json
  packages/odf/components/attach-obc/AttachOBC.scss
  packages/odf/components/attach-obc/AttachOBC.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/mcg/useObcFormSchema.spec.ts
  packages/odf/components/mcg/useObcFormSchema.ts
Labels: approved, lgtm

#1505 Bug 2300332: [release-4.16] Hide builtin-mgr CephBlockPool
  packages/ocs/block-pool/BlockPoolListPage.tsx
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/resources.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#1545 Bug 2290675: [Release-4.16] Optimize chunk size by changing devtool
  webpack.config.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1540 [release-4.16-compatibility] Bug 2290675: Optimize chunk size by changing devtool
  webpack.config.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1555 Disable remove disaster recovery button after a click
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
  packages/mco/components/protected-applications/utils.tsx
Labels: approved, lgtm

#1523 Bug 2303083: [release-4.16] Fix nodes' label for ROSA clusters
  packages/ocs/dashboards/persistent-internal/inventory-card.tsx
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/constants/common.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/redux/provider-hooks/useODFNamespace.ts
  packages/shared/src/constants/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1524 Bug 2303083: [release-4.16-compatibility] Fix nodes' label for ROSA clusters
  packages/ocs/dashboards/persistent-internal/inventory-card.tsx
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/constants/common.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/redux/provider-hooks/useODFNamespace.ts
  packages/shared/src/constants/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1506 Bug 2300332: [release-4.16-compatibility] Hide builtin-mgr CephBlockPool
  packages/ocs/block-pool/BlockPoolListPage.tsx
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/resources.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#1550 Add 'enableCrushUpdates' flag to custom block pool
  packages/ocs/storage-pool/CreateStoragePool.tsx
  packages/ocs/types.ts
Labels: approved, lgtm
