Repository red-hat-storage/odf-console, pull requests merged in 2024-01, with the labels that each got.

#1132 Hide PVC label selector that should not work for DR
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/mco/constants/acm.ts
Labels: approved, lgtm

#1141 Add test cases for dr-brownfield and subscription management
  packages/mco/components/mco-dashboard/data-policy/parsers/applicationset-parser.spec.tsx
  packages/mco/components/mco-dashboard/data-policy/parsers/subscription-parser.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
Labels: approved, lgtm

#1159 [RDR] Optimise cluster for RDR dialog fails with error msg
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/odf/constants/data-protection.ts
Labels: approved, lgtm

#1160 Bug 2257222: [RDR] Optimise cluster for RDR dialog fails with error msg
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/odf/constants/data-protection.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#1161 Bug 2257222: [RDR] Optimise cluster for RDR dialog fails with error msg
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
  packages/odf/constants/data-protection.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#1156 [MDR] Application view saying PVCs unhealthy but cluster view shows healthy
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/common.tsx
  packages/mco/types/dashboard.ts
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#1142 support cluster creation even if namespace already exists
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
Labels: approved, lgtm

#1149 Fix default RBD StorageClass option for external mode
  packages/odf-plugin-sdk/extensions/external-storage/external-storage.ts
  packages/odf/components/create-storage-system/external-ceph-storage/system-connection-details.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
Labels: approved, lgtm

#1153 [RDR] [UI] DR UI allows Relocate and Failover to same peer causing the failover stuck
  packages/mco/components/modals/app-failover-relocate/argo-application-set.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal-body.tsx
  packages/mco/components/modals/app-failover-relocate/failover-relocate-modal.tsx
  packages/mco/components/modals/app-failover-relocate/subscriptions/failover-relocate-modal.tsx
Labels: approved, lgtm

#1051 Change raw capacity tool tips message
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/block-pool/raw-capacity-card.tsx
Labels: approved, lgtm

#1158 Data Foundation UI textual updates
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/set-rbd-sc-default.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/set-rbd-sc-default.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/constants/tooltips.tsx
  packages/odf/modals/configure-mons/configure-mons.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
Labels: approved, lgtm

#1157 DR UI textual update for the epic 4.15
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/application.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
Labels: approved, lgtm

#1176 Updates path for MonCount value getter
  packages/odf/modals/configure-mons/configure-mons.tsx
  packages/shared/src/types/storage.ts
Labels: approved, lgtm

#1177 Bug 2255332: [release-4.15] DR UI textual update
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/application.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1178 Bug 2255332: [release-4.15-compatibility] DR UI textual update
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/application.tsx
  packages/mco/components/mco-dashboard/data-policy/cluster-app-card/cluster.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.spec.tsx
  packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-progress.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.spec.tsx
  packages/ocs/modals/osd-migration/osd-migration-details.tsx
  packages/ocs/modals/osd-migration/osd-migration-modal.tsx
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1164 Do not filter external Ceph from 'System raw capacity' card
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
Labels: approved, lgtm

#1183 Add translations for 4.15 release
  locales/ja/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
Labels: approved, lgtm

#1187 Bug 2259554: Fixes table row id for client list page
  packages/odf/components/storage-consumers/client-list.tsx
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#1186 Updates text in onboarding token modal
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/onboarding-modal.tsx
Labels: approved, lgtm

#1190 Bug 2260818: Updates selector for failure domain values
  packages/odf/modals/configure-mons/configure-mons.tsx
  packages/shared/src/types/storage.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#1197 Fix typo in StorageClusterKind
  packages/odf/components/utils/common.ts
  packages/shared/src/types/storage.ts
Labels: approved, lgtm
