Repository red-hat-storage/odf-console, pull requests merged in 2024-11, with the labels that each got.

#1656 Use https for S3 Route
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
Labels: approved, lgtm

#1655 Fix storage clients display issue on DRPolicy creation page
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
Labels: approved, lgtm

#1648 Bug 2317212: Fix Clients' list page filtering
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/list-filter.ts
  packages/shared/src/utils/common.ts
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#1654 Upgrading 'react-router-dom-v5-compat' package to 6.27.0
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved

#1658 Enable S3 browser for all modes
  packages/odf/components/object-service-nav-item/object-service.tsx
  packages/odf/features.ts
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#1660 Upgrade webpack-dev-server and webpack-cli dependencies
  package.json
  yarn.lock
Labels: approved, lgtm

#1661 Upgrade ts-node dependency
  package.json
  yarn.lock
Labels: approved, lgtm

#1665 Update Footer Button Order based on PF guidelines
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/footer.tsx
  packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
Labels: approved, lgtm

#1668 Fix favourites option for the bucket overview page
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-overview/PageTitle.tsx
  packages/odf/components/s3-browser/upload-objects/upload-component/FileUploadComponent.tsx
  packages/odf/components/s3-browser/upload-objects/upload-component/fileUploadComponent.scss
  packages/odf/components/s3-browser/upload-objects/upload-status/UploadStatusItem.tsx
Labels: approved, lgtm

#1670 Adds column for quota utilization in client list page
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/client-list.tsx
  packages/shared/src/types/storage.ts
Labels: approved, lgtm

#1671 Fix issues in client list page
  packages/odf/components/storage-consumers/client-list.tsx
Labels: approved, lgtm

#1672 Fix BackingStore details shows incorrect provider
  packages/odf/components/resource-pages/Providers.tsx
Labels: approved, lgtm

#1663 TSLint: enable rule 'react/no-unstable-nested-components'
  .eslintrc.js
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/utils/k8s-utils.ts
  packages/mco/components/discovered-application-wizard/wizard-steps/namespace-step/namespace-step.tsx
  packages/mco/components/discovered-application-wizard/wizard-steps/namespace-step/namespace-table.tsx
  packages/mco/components/discovered-application-wizard/wizard-steps/replication-step/replication-step.tsx
  packages/mco/components/mco-dashboard/storage-system/status-card/status-card.spec.tsx
  packages/mco/components/modals/app-data-policies-status/subscriptions/data-policies-status-popover.tsx
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/mco/utils/acm-search-queries.ts
  packages/mco/utils/index.ts
  packages/ocs/dashboards/object-service/buckets-card/buckets-card-item.tsx
  packages/ocs/dashboards/object-service/buckets-card/buckets-card.tsx
  packages/odf/components/s3-browser/object-details/ObjectDetailsSidebar.tsx
  packages/odf/components/s3-browser/upload-objects/upload-status/UploadStatusList.tsx
  packages/shared/src/kebab/kebab.tsx
Labels: approved, lgtm

#1659 Upgrade Cypress
  cypress/cypress.config.ts
  cypress/support.ts
  cypress/support/login.ts
  package.json
  yarn.lock
Labels: approved, lgtm

#1674 Adds progress component for storage quota utilization
  packages/odf/components/storage-consumers/QuotaUtilizationProgress.tsx
  packages/odf/components/storage-consumers/client-list.tsx
Labels: approved, lgtm

#1669 Syncing latest changes from master for odf-console
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-overview/PageTitle.tsx
  packages/odf/components/s3-browser/upload-objects/upload-component/FileUploadComponent.tsx
  packages/odf/components/s3-browser/upload-objects/upload-component/fileUploadComponent.scss
  packages/odf/components/s3-browser/upload-objects/upload-status/UploadStatusItem.tsx
Labels: approved, lgtm

#1673 Add CA issue prerequisites
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/common/details-card/encryption-popover.tsx
  packages/odf/components/s3-browser/buckets-list-page/bucketsListPage.tsx
  packages/odf/components/s3-browser/ca-error/CAErrorMessage.tsx
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/shared/src/constants/doc.ts
  packages/shared/src/status/icons.tsx
Labels: approved, lgtm

#1675 Cypress: enable Test Isolation
  .gitignore
  cypress/cypress.config.ts
  cypress/support.ts
  cypress/support/login.ts
  cypress/support/pages/app.ts
  cypress/tests/active-health-checks.spec.ts
  cypress/tests/add-capacity.spec.ts
  cypress/tests/bucket-class.spec.ts
  cypress/tests/create-backing-store.spec.ts
  cypress/tests/expand-pvc.spec.ts
  cypress/tests/kms-encryption-sc.spec.ts
  cypress/tests/list-page.spec.ts
  cypress/tests/multiple-storageclass-selection.spec.ts
  cypress/tests/namespace-store.spec.ts
  cypress/tests/obc-test.spec.ts
  cypress/tests/object-service-dashboards.spec.ts
  cypress/tests/persistent-dashboard-check.spec.ts
  cypress/tests/storage-pool-in-storageclass-form.spec.ts
  cypress/tests/storage-pool.spec.ts
  cypress/views/obcPage.ts
  cypress/views/pvc.ts
Labels: approved, lgtm

#1677 Upgrade Jest & React Testing Library
  package.json
  yarn.lock
Labels: approved, lgtm

#1652 Empty and Delete bucket modals
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-overview/BucketOverview.tsx
  packages/odf/components/s3-browser/buckets-list-page/bucketListTable.tsx
  packages/odf/components/s3-browser/buckets-list-page/bucketsListPage.tsx
  packages/odf/constants/s3-browser.ts
  packages/odf/modals/s3-browser/delete-and-empty-bucket/DeleteBucketModal.tsx
  packages/odf/modals/s3-browser/delete-and-empty-bucket/EmptyBucketModal.tsx
  packages/odf/modals/s3-browser/delete-and-empty-bucket/lazy-delete-and-empty-bucket.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
Labels: approved, lgtm

#1662 Epic: Support for multiple deviceClass on baremetal clusters
  locales/en/plugin__odf-console.json
  packages/ocs/storage-pool/body.tsx
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/attach-storage-storagesystem/attach-storage-footer.tsx
  packages/odf/components/attach-storage-storagesystem/attach-storage.scss
  packages/odf/components/attach-storage-storagesystem/attach-storage.tsx
  packages/odf/components/attach-storage-storagesystem/lso-storageclass-dropdown.tsx
  packages/odf/components/attach-storage-storagesystem/state.ts
  packages/odf/components/attach-storage-storagesystem/storage-pool-form.tsx
  packages/odf/components/attach-storage-storagesystem/storageclass-form.tsx
  packages/odf/components/attach-storage-storagesystem/utils.ts
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/constants/attach-storage.tsx
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/shared/src/constants/k8s.ts
  packages/shared/src/kebab/kebab.tsx
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1676 UI check to avoid peering a same managed cluster with more than one cluster
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/selected-cluster-validator.tsx
Labels: approved, lgtm

#1683 S3 textual updates + UX fixes
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/create-bucket/CreateBucket.tsx
  packages/odf/components/s3-browser/object-details/ObjectDetailsSidebar.tsx
  packages/odf/components/s3-browser/objects-list/ObjectListWithSidebar.tsx
  packages/odf/components/s3-browser/objects-list/ObjectsList.tsx
  packages/odf/components/s3-browser/objects-list/table-components.tsx
  packages/odf/modals/s3-browser/create-folder/CreateFolderModal.tsx
  packages/odf/modals/s3-browser/delete-objects/DeleteObjectsModal.tsx
Labels: approved, lgtm

#1679 Upgrade Webpack & Sass
  package.json
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.scss
  packages/mco/components/mco-dashboard/disaster-recovery/alert-card/alert-item.scss
  packages/ocs/dashboards/object-service/buckets-card/buckets-card.scss
  packages/ocs/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.scss
  packages/ocs/dashboards/object-service/data-consumption-card/data-consumption-card.scss
  packages/ocs/dashboards/object-service/resource-providers-card/resource-providers-card.scss
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.scss
  packages/odf/modals/add-capacity/add-capacity-modal.scss
  packages/shared/package.json
  packages/shared/src/styles/_vars.scss
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#1687 Upgrade @openshift/console dependencies
  package.json
  packages/odf/hooks/useNodesData.ts
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm

#1681 Disables deletion for local client
  packages/odf/components/storage-consumers/client-list.tsx
  packages/shared/src/models/common.ts
  packages/shared/src/types/k8s.ts
Labels: approved, lgtm

#1685 Enable ESLint rule: react/jsx-no-constructed-context-values
  .eslintrc.js
  packages/mco/components/mco-dashboard/disaster-recovery/dr-dashboard.tsx
  packages/ocs/dashboards/block-pool/block-pool-dashboard.tsx
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/odf/components/topology/Topology.tsx
Labels: approved, lgtm

#1691 Use 'sass' dependency instead of 'sass-embedded'
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm

#1666 Enhance block pool mirroring status card to cover rados namespace
  locales/en/plugin__odf-console.json
  packages/ocs/constants/common.ts
  packages/ocs/dashboards/block-pool/mirroring-card.tsx
  packages/ocs/dashboards/block-pool/states.ts
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/ocs/models/core.ts
  packages/ocs/queries/ceph-storage.ts
  packages/ocs/storage-pool/StoragePoolListPage.tsx
  packages/ocs/types.ts
Labels: approved, lgtm

#1497 Fix 'PLUGIN_VERSION' export from 'shared'
  packages/shared/src/constants/common.ts
Labels: approved, lgtm

#1481 Fix missing i18n
  locales/en/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
  packages/ocs/dashboards/block-pool/utilization-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utils.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
  packages/odf/i18n-comments.ts
  packages/odf/types/common.ts
  plugins/odf/console-extensions.json
Labels: approved, lgtm

#1695 Fix 'cross-spawn' CVE
  package.json
  yarn.lock
Labels: approved, lgtm

#1696 DFBUGS-867: [RDR] UI blocks a DR operation on an appset based workload
  packages/mco/components/modals/app-failover-relocate/helper/error-messages.tsx
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#1692 Hide NFS builtin pool
  cypress/constants/storage-pool-const.ts
  cypress/support.ts
  cypress/tests/storage-pool-in-storageclass-form.spec.ts
  cypress/views/storage-pool.ts
  packages/ocs/storage-class/sc-form.scss
  packages/ocs/storage-class/sc-form.tsx
  packages/ocs/storage-pool/StoragePoolListPage.tsx
  packages/odf/resources.ts
Labels: approved, lgtm

#1647 Add info alert for In-transit Encryption in external mode
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
  packages/shared/src/constants/doc.ts
Labels: approved, lgtm

#1697 Syncing latest changes from master for odf-console
  .eslintrc.js
  cypress/tests/persistent-dashboard-check.spec.ts
  locales/en/plugin__odf-console.json
  locales/ko/plugin__odf-console.json
  locales/zh/plugin__odf-console.json
  openshift-ci/odf-catalog-source.yaml
  package.json
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.scss
  packages/mco/components/mco-dashboard/disaster-recovery/alert-card/alert-item.scss
  packages/mco/components/mco-dashboard/disaster-recovery/dr-dashboard.tsx
  packages/ocs/constants/common.ts
  packages/ocs/dashboards/block-pool/block-pool-dashboard.tsx
  packages/ocs/dashboards/block-pool/mirroring-card.tsx
  packages/ocs/dashboards/block-pool/states.ts
  packages/ocs/dashboards/block-pool/utilization-card.tsx
  packages/ocs/dashboards/object-service/buckets-card/buckets-card.scss
  packages/ocs/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.scss
  packages/ocs/dashboards/object-service/data-consumption-card/data-consumption-card.scss
  packages/ocs/dashboards/object-service/resource-providers-card/resource-providers-card.scss
  packages/ocs/dashboards/odf-system-dashboard.tsx
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.scss
  packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utils.tsx
  packages/ocs/models/core.ts
  packages/ocs/queries/ceph-storage.ts
  packages/ocs/storage-pool/StoragePoolListPage.tsx
  packages/ocs/types.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
  packages/odf/components/s3-browser/create-bucket/CreateBucket.tsx
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/odf/components/s3-browser/object-details/ObjectDetailsSidebar.tsx
  packages/odf/components/s3-browser/objects-list/ObjectListWithSidebar.tsx
  packages/odf/components/s3-browser/objects-list/ObjectsList.tsx
  packages/odf/components/s3-browser/objects-list/table-components.tsx
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/hooks/useNodesData.ts
  packages/odf/i18n-comments.ts
  packages/odf/modals/add-capacity/add-capacity-modal.scss
  packages/odf/modals/s3-browser/create-folder/CreateFolderModal.tsx
  packages/odf/modals/s3-browser/delete-objects/DeleteObjectsModal.tsx
  packages/odf/types/common.ts
  packages/shared/package.json
  packages/shared/src/constants/common.ts
  packages/shared/src/kebab/kebab.tsx
  packages/shared/src/models/common.ts
  packages/shared/src/styles/_vars.scss
  packages/shared/src/types/k8s.ts
  plugins/odf/console-extensions.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#1703 Fix kebab menu click behavior
  packages/shared/src/kebab/kebab.tsx
Labels: approved, lgtm

#1682 Fix webhook warning in bucket and obc creation
  packages/odf/components/create-bs/create-bs.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/namespace-store/namespace-store-form.tsx
  packages/odf/types/mcg.ts
  packages/odf/utils/mcg.ts
Labels: approved, lgtm

#1707 Fix 'Model does not exist' error
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/redux/provider-hooks/useODFSystemFlags.ts
Labels: approved, lgtm

#1716 Add 'encryptionKMSID' for 'Attach Storage' form
  packages/odf/components/attach-storage-storagesystem/attach-storage-footer.tsx
  packages/odf/components/attach-storage-storagesystem/attach-storage.scss
  packages/odf/components/attach-storage-storagesystem/state.ts
  packages/odf/components/attach-storage-storagesystem/storageclass-form.tsx
  packages/odf/components/attach-storage-storagesystem/utils.ts
Labels: approved, lgtm

#1715 Run sanity checks on PR base branch change
  .github/workflows/frontend-build.yml
Labels: approved, lgtm

#1741 [release-4.14-compatibility] Run sanity checks on PR base branch change
  .github/workflows/frontend-build.yml
Labels: approved, lgtm

#1744 Debug: add instructions & vscode 'launch.json' template
  .gitignore
  .vscode/launch.template.json
  .vscode/settings.json
  README.md
Labels: approved, lgtm

#1706 Fix Sync Warning not refreshed while Changing target cluster
  packages/mco/components/modals/app-failover-relocate/subscriptions/peer-cluster-status.tsx
Labels: approved, lgtm
