Repository red-hat-storage/odf-console, pull requests merged in 2025-01, with the labels that each got.

#1792 Sort package.json alphabetically
  package.json
  packages/shared/package.json
Labels: approved, lgtm

#1801 Fix for tooltip rendered behind the chart
  package.json
  packages/shared/package.json
  packages/shared/src/charts/tooltip.tsx
  yarn.lock
Labels: approved, lgtm

#1588 Fix UI alignment on Connect KMS form
  packages/odf/components/kms-config/kms-config.tsx
Labels: approved, lgtm

#1805 Adds prefix for blockpool in AttachStorage form
  packages/ocs/modals/storage-pool/create-storage-pool-modal.tsx
  packages/ocs/modals/storage-pool/update-storage-pool-modal.tsx
  packages/ocs/storage-pool/CreateStoragePool.tsx
  packages/ocs/storage-pool/body.scss
  packages/ocs/storage-pool/body.tsx
  packages/odf/components/attach-storage-storagesystem/storage-pool-form.tsx
Labels: approved, lgtm

#1810 Enhanced rule message for name used in obc
  locales/en/plugin__odf-console.json
  packages/odf/components/mcg/useObcFormSchema.spec.ts
  packages/odf/components/mcg/useObcFormSchema.ts
  packages/shared/src/constants/fieldRequirements.ts
Labels: approved, lgtm

#1815 Update query for capacity usage of PVC by namespace
  packages/ocs/queries/ceph-storage.spec.ts
  packages/ocs/queries/ceph-storage.ts
Labels: approved, lgtm

#1819 MDR DR policy creation issue with UI
  packages/mco/__mocks__/managedcluster.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/create-dr-policy.tsx
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/select-replication-type.tsx
  packages/mco/components/create-dr-policy/selected-cluster-validator.tsx
Labels: approved, lgtm

#1818 Volsync in DR dashboard reports operator degraded
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster-app-card.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/cluster-app-card/cluster.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/dr-dashboard-context.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/dr-dashboard.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/status-card/status-card.tsx
  packages/mco/components/mco-dashboard/queries.ts
Labels: approved, lgtm

#1827 Revert "[release-4.17] DFBUGS-1314: Update query for capacity usage of PVC by namespace"
  packages/ocs/queries/ceph-storage.spec.ts
  packages/ocs/queries/ceph-storage.ts
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#1826 Revert "[release-4.17-compatibility] DFBUGS-1314: Update query for capacity usage of PVC by namespace"
  packages/ocs/queries/ceph-storage.spec.ts
  packages/ocs/queries/ceph-storage.ts
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#1830 Fix pool name check for blockpools
  packages/ocs/storage-pool/body.tsx
Labels: approved, lgtm

#1836 Updates i18n conv to fix CVE-2024-21528
  package.json
  yarn.lock
Labels: approved, lgtm

#1838 DFBUGS-236: Updates i18n conv to fix CVE-2024-21528
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1837 DFBUGS-236: Updates i18n conv to fix CVE-2024-21528
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1839 Upgrade TS minor version
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm

#1844 Add S3 navigation skeleton
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-details/BucketDetails.tsx
  packages/odf/components/s3-browser/bucket-overview/BucketOverview.tsx
  packages/odf/components/s3-browser/bucket-overview/ManagementNav.tsx
  packages/odf/components/s3-browser/bucket-overview/PermissionsNav.tsx
  packages/odf/components/s3-browser/bucket-overview/bucket-overview.scss
  packages/odf/components/s3-browser/buckets-list-page/bucketListTable.tsx
  packages/odf/components/s3-browser/objects-list/ObjectListWithSidebar.tsx
  packages/shared/src/utils/Tabs.tsx
Labels: approved, lgtm

#1833 Object Browser: access S3 endpoint via console proxy
  README.md
  packages/mco/constants/url-paths.ts
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/constants/attach-storage.tsx
  packages/shared/src/constants/common.ts
  packages/shared/src/hooks/custom-prometheus-poll/utils.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/constants.ts
  packages/shared/src/s3/index.ts
Labels: approved, lgtm

#1846 DFBUGS-1349: [release-4.18] Object Browser: access S3 endpoint via console proxy
  README.md
  packages/mco/constants/url-paths.ts
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/constants/attach-storage.tsx
  packages/shared/src/constants/common.ts
  packages/shared/src/hooks/custom-prometheus-poll/utils.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/constants.ts
  packages/shared/src/s3/index.ts
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#1847 DFBUGS-1349: [release-4.18-compatibility] Object Browser: access S3 endpoint via console proxy
  README.md
  packages/mco/constants/url-paths.ts
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/odf/constants/attach-storage.tsx
  packages/shared/src/constants/common.ts
  packages/shared/src/hooks/custom-prometheus-poll/utils.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/constants.ts
  packages/shared/src/s3/index.ts
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#1849 Upgrade jest/RTL deps & remove unnecessary deps
  package.json
  packages/odf/components/mcg-endpoints/gcp-endpoint-type.tsx
  packages/odf/utils/mcg.ts
  packages/shared/package.json
  packages/shared/src/charts/utils.ts
  packages/shared/src/generic/ButtonBar.tsx
  packages/shared/src/hooks/useUserSettingsLocalStorage.ts
  yarn.lock
Labels: approved, lgtm
