Repository red-hat-storage/odf-console, pull requests merged in 2025-02, with the labels that each got.

#1852 Update ReadMe (NooBaa Object Browser setup)
  README.md
Labels: approved, lgtm

#1851 Add support for Bucket Policy (S3)
  locales/en/plugin__odf-console.json
  package.json
  packages/odf/components/s3-browser/bucket-overview/BucketOverview.tsx
  packages/odf/components/s3-browser/bucket-overview/ManagementNav.tsx
  packages/odf/components/s3-browser/bucket-overview/PermissionsNav.tsx
  packages/odf/components/s3-browser/bucket-policy/BucketPolicy.tsx
  packages/odf/components/s3-browser/bucket-policy/PreConfiguredPolicies.tsx
  packages/odf/components/s3-browser/bucket-policy/bucket-policy.scss
  packages/odf/constants/s3-browser.ts
  packages/odf/modals/s3-browser/bucket-policy/DeleteBucketPolicy.tsx
  packages/odf/modals/s3-browser/bucket-policy/SaveBucketPolicy.tsx
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  yarn.lock
Labels: approved, lgtm

#1859 Bug DFBUGS-876: [Release-4.15] [CVE] Improper input validation in PostCSS
  .eslintrc.js
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1848 Bug DFBUGS-879: [Release-4.17] [CVE] Improper input validation in PostCSS
  .eslintrc.js
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1858 Bug DFBUGS-883: [Release-4.16] [CVE] Improper input validation in PostCSS
  .eslintrc.js
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1854 [release-4.17-compatibility] DFBUGS-1543: Updates i18n conv to fix CVE-2024-21528
  .github/workflows/frontend-build.yml
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1860 Bug DFBUGS-887: [Release-4.14] [CVE] Improper input validation in PostCSS
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1863 [release-4.16-comaptibility] DFBUGS-545: Updates i18n conv to fix CVE-2024-21528
  .github/workflows/frontend-build.yml
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1862 [release-4.16] DFBUGS-545: Updates i18n conv to fix CVE-2024-21528
  .github/workflows/frontend-build.yml
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1867 [release-4.15] DFBUGS-1544: Updates i18n conv to fix CVE-2024-21528
  .github/workflows/frontend-build.yml
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1872 Bug DFBUGS-876: [Release-4.15-compatibility] [CVE] Improper input validation in PostCSS
  .eslintrc.js
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1871 Bug DFBUGS-883: [Release-4.16-compatibility] [CVE] Improper input validation in PostCSS
  .eslintrc.js
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1870 Bug DFBUGS-879: [Release-4.17-compatibility] [CVE] Improper input validation in PostCSS
  .eslintrc.js
  analyzeTest.ts
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1850 RHSTOR-6905: Enhance storage system creation flow
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/select-deployment.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/multus.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/nic.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/nic.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/nic.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/security-and-network-step.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/odf/types/common.ts
  packages/odf/types/network.ts
  packages/shared/src/types/storage.ts
Labels: approved, lgtm, jira/valid-reference

#1861 Create Lifecycle rules (S3)
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-policy/BucketPolicy.tsx
  packages/odf/components/s3-browser/create-lifecycle-rules/CreateLifecycleRule.tsx
  packages/odf/components/s3-browser/create-lifecycle-rules/GeneralConfigAndFilters.tsx
  packages/odf/components/s3-browser/create-lifecycle-rules/RuleActions.tsx
  packages/odf/components/s3-browser/create-lifecycle-rules/create-lifecycle-rules.scss
  packages/odf/components/s3-browser/create-lifecycle-rules/reducer.ts
  packages/odf/components/s3-browser/create-lifecycle-rules/validations.ts
  packages/odf/constants/s3-browser.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/utils/humanize.js
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1876 Cancel icon not working ("Create new BackingStore" modal) #1874
  packages/odf/components/create-bs/create-bs-modal.tsx
Labels: approved, lgtm, ok-to-test

#1878 [RDR] PVC label selector causes infinite blinking when applying DRPolicy
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.tsx
Labels: approved, lgtm

#1829 Upgrading react-router-dom-v5-compat package
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm

#1828 Upgrading webpack and other webpack plugins
  package.json
  yarn.lock
Labels: approved, lgtm

#1880 Add spacing class in body.tsx to insert space between the header and …
  packages/ocs/storage-pool/body.tsx
Labels: approved, lgtm

#1877 Add lifecycle rules list, edit and delete pages
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-overview/ManagementNav.tsx
  packages/odf/components/s3-browser/bucket-overview/PermissionsNav.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/CreateOrEditLifecycleRule.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/GeneralConfigAndFilters.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/RuleActions.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/create-lifecycle-rules.scss
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/reducer.ts
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/useEditLifecycleRule.ts
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/validations.ts
  packages/odf/components/s3-browser/lifecycle-rules-list/LifecycleRulesList.tsx
  packages/odf/constants/s3-browser.ts
  packages/odf/modals/s3-browser/bucket-policy/SaveBucketPolicy.tsx
  packages/odf/modals/s3-browser/delete-lifecyclerules/DeleteLifecycleRuleModal.tsx
  packages/odf/utils/s3-browser.ts
  packages/shared/src/s3/utils.ts
  packages/shared/src/utils/common.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm
