Repository red-hat-storage/odf-console, pull requests merged in 2025-07, with the labels that each got.

#2140 Add PublicAccessBlock config page
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-overview/PermissionsNav.tsx
  packages/odf/components/s3-browser/public-access-block/PublicAccessBlock.tsx
  packages/odf/components/s3-browser/public-access-block/utils.tsx
  packages/odf/constants/s3-browser.ts
  packages/odf/modals/s3-browser/public-access-block-confirmation/PublicAccessBlockConfirmation.tsx
  packages/shared/src/checkbox-tree/CheckboxTree.tsx
  packages/shared/src/checkbox-tree/index.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/s3/utils.ts
Labels: approved, lgtm

#2139 RHSTOR-7461Upgrade Yup to version 1.6.1
  package.json
  packages/odf/components/mcg/useObcFormSchema.ts
  packages/odf/components/s3-browser/create-bucket/useS3BucketFormValidation.ts
  packages/odf/constants/providerSchema.ts
  packages/shared/package.json
  packages/shared/src/yup-validation-resolver/useYupValidationResolver.spec.ts
  yarn.lock
Labels: approved, lgtm

#2130 Update to installation process
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/block-pool/compression-details-card.tsx
  packages/ocs/dashboards/block-pool/raw-capacity-card.tsx
  packages/ocs/dashboards/block-pool/utilization-card.tsx
  packages/ocs/dashboards/network-file-system/status-card/status-card.tsx
  packages/ocs/dashboards/object-service/activity-card/activity-card.tsx
  packages/ocs/dashboards/object-service/buckets-card/buckets-card.tsx
  packages/ocs/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.spec.tsx
  packages/ocs/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.tsx
  packages/ocs/dashboards/object-service/data-consumption-card/data-consumption-card.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/object-service/resource-providers-card/resource-providers-card.tsx
  packages/ocs/dashboards/object-service/status-card/status-card.tsx
  packages/ocs/dashboards/object-service/storage-efficiency-card/storage-efficiency-card.tsx
  packages/ocs/dashboards/ocs-dashboard-providers.ts
  packages/ocs/dashboards/ocs-system-dashboard.tsx
  packages/ocs/dashboards/persistent-external/breakdown-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-external/status-card.tsx
  packages/ocs/dashboards/persistent-external/utilization-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/capacity-breakdown-card/capacity-breakdown-card.tsx
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/dashboards/persistent-internal/inventory-card.tsx
  packages/ocs/dashboards/persistent-internal/raw-capacity-card/raw-capacity-card.tsx
  packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
  packages/ocs/dashboards/persistent-internal/storage-efficiency-card/storage-efficiency-card.tsx
  packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
  packages/ocs/storage-pool/BlockPoolDetailsPage.tsx
  packages/ocs/storage-pool/CreateStoragePool.tsx
  packages/ocs/storage-pool/StoragePoolListPage.tsx
  packages/odf/components/Sections/InitialEmptyStatePage.tsx
  packages/odf/components/Sections/ObjectStorageSection.tsx
  packages/odf/components/Sections/StorageClusterSection.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/odf/modals/ConfigureDF/StorageClusterCreateModal.scss
  packages/odf/modals/ConfigureDF/StorageClusterCreateModal.spec.tsx
  packages/odf/modals/ConfigureDF/StorageClusterCreateModal.tsx
  packages/odf/modals/ConfigureDF/util.ts
  packages/odf/types/install-ui.ts
  packages/shared/src/utils/tabs.scss
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#2123 RHSTOR-6175 Automate key rotation for encrypted RBD storage classes
  packages/ocs/storage-class/mutators.ts
Labels: approved, lgtm

#2145 RHSTOR-7589 Remove style-loader (use mini-css-extract-plugin)
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#2142 RHSTOR-7577 Remove file-loader dependency: use asset module
  package.json
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm

#2165 Remove 'subscriptionResource' duplicates
  packages/client/src/components/dashboards/cards/activity-card.tsx
  packages/ocs/dashboards/object-service/capacity-breakdown/capacity-breakdown-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/odf/resources.ts
  packages/shared/src/resources/common.ts
Labels: approved, lgtm, do-not-merge/hold

#2159 Show warning for subscription application deprecation
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
Labels: approved, lgtm

#2160 Fixes cypress tests
  .ci-operator.yaml
  .nvmrc
  Dockerfile.ci
  Dockerfile.ci.runner
  cypress/support.ts
  cypress/tests/active-health-checks.spec.ts
  cypress/tests/add-capacity.spec.ts
  cypress/tests/list-page.spec.ts
  cypress/tests/multiple-storageclass-selection.spec.ts
  cypress/tests/object-service-dashboards.spec.ts
  cypress/tests/persistent-dashboard-check.spec.ts
  cypress/views/block-pool.ts
  cypress/views/common.ts
  cypress/views/multiple-storageclass.ts
  cypress/views/odf-common.ts
  cypress/views/storage-pool.ts
  packages/ocs/storage-pool/StoragePoolListPage.tsx
  packages/odf/components/Sections/InitialEmptyStatePage.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/overview/storage-cluster-card/StorageClusterCard.tsx
  packages/odf/modals/ConfigureDF/StorageClusterCreateModal.tsx
  packages/shared/src/dropdown/ResourceDropdown.tsx
  packages/shared/src/kebab/kebab.tsx
  test-prow-e2e.sh
Labels: approved

#2170 Make data-test ID for Kebab always have a fallback
  packages/shared/src/kebab/kebab.tsx
Labels: approved, lgtm
