Repository red-hat-storage/odf-console, pull requests merged in 2025-04, with the labels that each got.

#1931 Typeahead dropdown: allow selected value to be a number + unit tests
  packages/shared/src/dropdown/TypeaheadDropdown.spec.tsx
  packages/shared/src/dropdown/TypeaheadDropdown.tsx
Labels: approved, lgtm

#1924 Updates token generation mechanism
  locales/en/plugin__odf-console.json
  packages/odf/components/storage-consumers/CreateStorageConsumer.tsx
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/components/storage-consumers/onboarding-modal.scss
  packages/odf/components/storage-consumers/onboarding-modal.tsx
  packages/shared/src/constants/fieldRequirements.ts
  packages/shared/src/types/storage.ts
  packages/shared/src/utils/validation.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1930 Adds facade for StorageSystem resource in UI
  cypress/consts.ts
  cypress/support.ts
  cypress/tests/add-capacity.spec.ts
  cypress/tests/object-service-dashboards.spec.ts
  cypress/views/multiple-storageclass.ts
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/odf-dashboard/performance-card/performance-card.tsx
  packages/odf/components/odf-dashboard/status-card/status-card.tsx
  packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/features.ts
  packages/odf/redux/provider-hooks/useODFSystemFlags.ts
  packages/shared/src/hooks/useWatchStorageSystems.ts
  packages/shared/src/kebab/kebab.tsx
Labels: approved, lgtm

#1935 Fix for ManagedClusterAction mca-64x44 violates policy 299
  packages/mco/types/acm.ts
  packages/mco/utils/managed-cluster-action.ts
Labels: approved, lgtm

#1938 Relax storage class validation logic and fix async completion handling
  packages/mco/components/create-dr-policy/selected-cluster-validator.tsx
Labels: approved, lgtm

#1939 Add '1 TiB' & '8 TiB' to Day-1 OSD size dropdown
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/utils/osd-size-dropdown.tsx
  packages/odf/constants/common.ts
  packages/shared/src/utils/storage.ts
Labels: approved, lgtm

#1936 Fix test failure for subscription parser-test and appset parser
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.spec.tsx
Labels: approved, lgtm

#1941 Rename 'Smart scaling' to 'Automatic capacity scaling'
  locales/en/plugin__odf-console.json
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/modals/capacity-autoscaling/capacity-autoscaling-modal.tsx
Labels: approved, lgtm

#1946 Upgrade loader-utils to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm

#1944 DFBUGS-2095: [release-4.18] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1945 DFBUGS-2095: [release-4.18-compatibility] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1948 DFBUGS-48: [release-4.17] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1953 DFBUGS-44: [release-4.16] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1955 DFBUGS-43: [release-4.15] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1954 Client plugin: hide S3 Object browser
  plugins/client/console-extensions.json
  plugins/client/console-plugin.json
Labels: approved, lgtm

#1952 DFBUGS-44: [release-4.16-compatibility] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1959 DFBUGS-2110: [release-4.14] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1956 DFBUGS-43: [release-4.15-compatibility] Fix CVEs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1965 Fix ODF system dashboard
  packages/shared/src/hooks/useWatchStorageSystems.ts
Labels: approved, lgtm

#1966 Upgrade ansi-regex & json5 to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm

#1970 DFBUGS-1968: [release-4.18-compatibility] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1969 DFBUGS-1968: [release-4.18] Upgrade ansi-regex, json5 & loader-utils to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1998 DFBUGS-2177: [release-4.17-compatibility] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2002 DFBUGS-2189: [release-4.16-compatibility] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, jira/invalid-bug

#2003 DFBUGS-2201: [release-4.17]CVE fix for minimist and yargs-parser
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1943 Fix CVE-2024-4068, CVE-2022-25883 and CVE-2024-39249
  package.json
  yarn.lock
Labels: approved, lgtm

#2005 DFBUGS-2201: [release-4.17-compatibility]CVE fix for minimist and yargs-parser
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2010 DFBUGS-2207: [release-4.14-compatibility] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: lgtm, jira/valid-bug, jira/valid-reference

#2009 DFBUGS-2207: [release-4.14] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: lgtm, jira/valid-bug, jira/valid-reference

#2006 DFBUGS-2199: [release-4.15-compatibility] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: lgtm, jira/valid-bug, jira/valid-reference

#2004 DFBUGS-2199: [release-4.15] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: lgtm, jira/valid-bug, jira/valid-reference

#1997 DFBUGS-2177: [release-4.17] Upgrade ansi-regex, json5 & loader-utils
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2000 DFBUGS-1962: [release-4.18-compatibility] CVE fix for minimist, showdown and yargs-parser
  package.json
  packages/client/src/components/dashboards/cards/details-card.tsx
  packages/ocs/dashboards/block-pool/compression-details-card.tsx
  packages/ocs/dashboards/block-pool/details-card.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/shared/src/index.ts
  packages/shared/src/overview-page/OverviewDetailItem.scss
  packages/shared/src/overview-page/OverviewDetailItem.tsx
  packages/shared/src/overview-page/index.ts
  packages/shared/src/styles/_skeleton.scss
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1993 DFBUGS-1962: [release-4.18] CVE fix for minimist, showdown and yargs-parser
  package.json
  packages/client/src/components/dashboards/cards/details-card.tsx
  packages/ocs/dashboards/block-pool/compression-details-card.tsx
  packages/ocs/dashboards/block-pool/details-card.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/shared/src/index.ts
  packages/shared/src/overview-page/OverviewDetailItem.scss
  packages/shared/src/overview-page/OverviewDetailItem.tsx
  packages/shared/src/overview-page/index.ts
  packages/shared/src/styles/_skeleton.scss
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2007 DFBUGS-2204: [release-4.16]CVE fix for minimist and yargs-parser
  package.json
  yarn.lock
Labels: lgtm, jira/valid-bug, jira/valid-reference

#1951 DFBUGS-1998: Fix CVE-2025-27789: Upgrade '@babel/runtime' package
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2013 DFBUGS-2213: [release-4.14] CVE fix for showdown, minimist and yargs-parser
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2012 DFBUGS-2212: [release-4.15-compatibility] CVE fix for showdown, minimist and yargs-parser
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2011 DFBUGS-2212: [release-4.15] CVE fix for showdown, minimist and yargs-parser
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2029 Fix for DRPolicy creation issue for MDR
  packages/mco/components/create-dr-policy/selected-cluster-validator.tsx
  packages/mco/components/create-dr-policy/utils/cluster-list-utils.ts
  packages/mco/components/create-dr-policy/utils/reducer.ts
Labels: approved, lgtm

#2014 DFBUGS-2213: [release-4.14-compatibility] CVE fix for showdown, minimist and yargs-parser
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2021 DFBUGS-2225: [release-4.19] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2032 Fix CVE-2024-39249
  package.json
  yarn.lock
Labels: approved, lgtm

#2028 Decode onboarding token
  packages/odf/components/storage-consumers/onboarding-modal.tsx
Labels: approved, lgtm

#2027 DFBUGS-2156: [release-4.17-compatibility] fix: update serialize-javascript to >=6.0.2 to address XSS vulnerability
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2026 DFBUGS-2151: [release-4.17] fix: update serialize-javascript to >=6.0.2 to address XSS vulnerability
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2024 DFBUGS-2149: [release-4.15] fix: update serialize-javascript to >=6.0.2 to address XSS vulnerability
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1980 upgrade minimatch, undici, underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm

#2035 DFBUGS-2174: [release-4.19] CVE-2024-39249
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2025 DFBUGS-2144: [release-4.15-compatibility] fix: update serialize-javascript to >=6.0.2 to address XSS vulnerability
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1960 DFBUGS-2116: [release-4.18] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1971 DFBUGS-2116: [release-4.18-compatibility] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1999 DFBUGS-2002: [release-4.19] upgrade minimatch, undici, and underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1986 DFBUGS-1963: [release-4.18] upgrade minimatch, undici, and underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2022 DFBUGS-2148: [release-4.14] fix: update serialize-javascript to >=6.0.2 to address XSS vulnerability
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2037 DFBUGS-2180: [release-4.18] Fix cvs
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2038 DFBUGS-2180: [release-4.18-compatibility] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2023 DFBUGS-2153: [release-4.14-compatibility] fix: update serialize-javascript to >=6.0.2 to address XSS vulnerability
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1989 DFBUGS-2184: [release-4.17-compatibility] upgrade minimatch, and underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1981 DFBUGS-2130: [release-4.17-compatibility] Fix CVE-2024-4067 and CVE-2025-27789
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1963 DFBUGS-2130: [release-4.17] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1964 DFBUGS-2137: [release-4.16] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1982 DFBUGS-2137: [release-4.16-compatibility] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1900 DFBUGS-2182: [release-4.17] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2039 DFBUGS-2182: [release-4.17-compatibility] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2041 DFBUGS-2191: [release-4.16-compatibility] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1984 DFBUGS-2170: [release-4.14-compatibility] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1983 DFBUGS-2163: [release-4.15-compatibility] Fix CVE-2024-4067 and CVE-2025-27789 issues
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2042 DFBUGS-2186: [release-4.15] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2045 DFBUGS-2188: [release-4.14-compatibility] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2043 DFBUGS-2186: [release-4.15-compatibility] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#2044 DFBUGS-2188: [release-4.14] Upgrading packages semver, async and braces
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#1926 DFBUGS-1634 Fix selection tabs, chart donut, skeletons, and loading placeholders.
  packages/ocs/dashboards/common/capacity-card/capacity-card.scss
  packages/shared/src/utils/tabs.scss
Labels: approved, lgtm

#1991 DFBUGS-2252: [release-4.16-compatibility] upgrade minimatch, and underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1996 DFBUGS-2254: [release-4.14-compatibility] upgrade minimatch, and underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1995 DFBUGS-2254: [release-4.14] upgrade minimatch, and underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1994 DFBUGS-2253: [release-4.15-compatibility] upgrade minimatch, and underscore.string to secure versions
  package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2050 Fix CORS rule deletion issue + other minor fixes
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/cors-rules-list/CORSRulesList.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/CreateOrEditCorsRule.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/CreateOrEditLifecycleRule.tsx
  packages/odf/components/s3-browser/lifecycle-rules-list/LifecycleRulesList.tsx
  packages/odf/modals/s3-browser/delete-corsrules/DeleteCorsRuleModal.tsx
  packages/odf/modals/s3-browser/delete-lifecyclerules/DeleteLifecycleRuleModal.tsx
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
Labels: approved, lgtm

#2054 Convert dl, dd, dt to PF DescriptionList + Remove DetailsBody component
  packages/client/src/components/dashboards/cards/details-card.tsx
  packages/ocs/dashboards/block-pool/compression-details-card.tsx
  packages/ocs/dashboards/block-pool/details-card.tsx
  packages/ocs/dashboards/block-pool/mirroring-card-body.tsx
  packages/ocs/dashboards/block-pool/mirroring-card-item.tsx
  packages/ocs/dashboards/block-pool/mirroring-card.scss
  packages/ocs/dashboards/block-pool/status-card.tsx
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-external/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/odf/components/bucket-class/wizard-pages/review-page.tsx
  packages/odf/components/mcg/ObjectBucket.tsx
  packages/odf/components/mcg/ObjectBucketClaim.tsx
  packages/odf/components/mcg/secret.tsx
  packages/odf/components/s3-browser/bucket-details/BucketDetails.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
  packages/shared/src/details-page/DetailsPage.tsx
  packages/shared/src/details-page/details.scss
  packages/shared/src/overview-page/OverviewDetailItem.scss
  packages/shared/src/overview-page/OverviewDetailItem.tsx
  packages/shared/src/styles/_common.scss
  packages/shared/src/topology/sidebar/node/NodeDetails.tsx
  packages/shared/src/utils/SecretValue.tsx
Labels: approved, lgtm

#2055 [MDR] Bug fix in MDR DRPolicy creation
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/select-cluster-list.tsx
  packages/mco/components/create-dr-policy/selected-cluster-validator.tsx
  packages/mco/components/create-dr-policy/utils/cluster-list-utils.ts
  packages/mco/constants/acm.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/src/selectors/k8s.ts
Labels: approved, lgtm

#2053 Introduces new flag for detection of internal mode
  packages/shared/src/global.d.ts
  plugins/client/console-extensions.json
Labels: approved, lgtm

#2049 E2E: upgrade CatalogSource to 4.19
  cypress/support/login.ts
  cypress/support/views.ts
  cypress/tests/add-capacity.spec.ts
  cypress/tests/storage-pool-in-storageclass-form.spec.ts
  cypress/tests/storage-pool.spec.ts
  cypress/views/obcPage.ts
  openshift-ci/odf-catalog-source.yaml
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
Labels: approved, lgtm
