Repository red-hat-storage/odf-console, pull requests merged in 2025-03, with the labels that each got.

#1886 Make the create backing store dropdown work
  packages/odf/components/bucket-class/create-bc.tsx
  packages/odf/components/bucket-class/wizard-pages/namespace-store-pages/cache-namespace-store.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/useEditLifecycleRule.ts
Labels: approved, lgtm

#1891 DFBUGS-1779: Fix 'NaN' issue with 'Estimated days until full' (Capacity Trends)
  packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-important

#1890 Add eslint-plugin-testing-library
  .eslintrc.js
  package.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.spec.tsx
  packages/mco/components/drpolicy-list-page/drpolicy-list-page.spec.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/getting-started-card/getting-started-card.spec.tsx
  packages/mco/components/mco-dashboard/storage-system/status-card/status-card.spec.tsx
  packages/mco/components/modals/app-failover-relocate/parser/argo-application-set-parser.spec.tsx
  packages/mco/components/modals/app-failover-relocate/parser/discovered-application-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.spec.tsx
  packages/mco/components/modals/protected-applications/managed-applications-modal.spec.tsx
  packages/mco/components/protected-applications/protected-apps-list-page.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/nic.spec.tsx
  packages/odf/components/kms-config/azure-config.spec.tsx
  packages/odf/components/kms-config/azure-config.tsx
  packages/shared/src/getting-started-grid/GettingStartedExpandableGrid.spec.tsx
  packages/shared/src/label-expression-selector/labelExpressionSelector.spec.tsx
  packages/shared/src/table/selectable-table.spec.tsx
  yarn.lock
Labels: approved, lgtm

#1888 Add support for SC distribution modal for storage clients
  locales/en/plugin__odf-console.json
  package.json
  packages/client/src/components/dashboards/cards/activity-card.tsx
  packages/ocs/dashboards/persistent-internal/activity-card/activity-card.tsx
  packages/ocs/utils/common.ts
  packages/odf/components/ResourceDistribution/ResourceDistributionTable.spec.tsx
  packages/odf/components/ResourceDistribution/ResourceDistributionTable.tsx
  packages/odf/components/ResourceDistribution/utils.ts
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/constants/common.ts
  packages/odf/modals/ResourceDistributionModal/ResourceDistributionModal.spec.tsx
  packages/odf/modals/ResourceDistributionModal/ResourceDistributionModal.tsx
  packages/odf/utils/ocs.ts
  packages/shared/package.json
  packages/shared/src/constants/index.ts
  packages/shared/src/constants/storageClasses.ts
  packages/shared/src/models/common.ts
  packages/shared/src/selectors/index.ts
  packages/shared/src/selectors/storageClasses.ts
  packages/shared/src/skeletal-loader/TableSkeleton.tsx
  packages/shared/src/types/k8s.ts
  packages/shared/src/types/storage.ts
  packages/shared/src/utils/storage.ts
  yarn.lock
Labels: approved, lgtm

#1898 Upgrade dev dep: http-server
  package.json
  yarn.lock
Labels: approved, lgtm

#1904 Remove unused assets folder from mco plugin
  packages/mco/assets/EmptyPageIcon.png
Labels: approved, lgtm

#1856 RHSTOR-6968: Disaster recovery UI for Kubevirt VM - managed application
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/acm-action-callback.tsx
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal-body.tsx
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/modal-context-viewer.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/index.ts
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/virtual-machine-parser.tsx
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/types.ts
  packages/mco/constants/acm.ts
  packages/mco/hooks/subscription.ts
  packages/mco/models/index.ts
  packages/mco/models/kubevirt.ts
  packages/mco/types/acm.ts
  packages/mco/utils/acm-search-queries.ts
  packages/mco/utils/disaster-recovery.tsx
  plugins/mco/console-extensions.json
  plugins/mco/console-plugin.json
Labels: approved, lgtm, jira/valid-reference

#1907 Adds support for SC and VSC distrbution to clients
  locales/en/plugin__odf-console.json
  packages/odf/components/ResourceDistribution/utils.ts
  packages/odf/components/odf-dashboard/status-card/utils.ts
  packages/odf/components/storage-consumers/client-list.tsx
  packages/odf/modals/StorageClientDistributionModal/StorageClientAttacherModal.tsx
  packages/odf/modals/StorageClientDistributionModal/storageClientAttacherComponent.scss
  packages/odf/modals/StorageClientDistributionModal/useStorageClientAttacherAction.ts
  packages/shared/src/selectors/index.ts
  packages/shared/src/selectors/volumeSnapshots.ts
  packages/shared/src/utils/storage.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1881 Add Capacity AutoScaling
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/mcg-endpoints/pvc-endpoint-type.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/reducer.ts
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/lso.ts
  packages/odf/modals/capacity-autoscaling/capacity-autoscaling-modal.scss
  packages/odf/modals/capacity-autoscaling/capacity-autoscaling-modal.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
  packages/odf/types/common.ts
  packages/odf/utils/ocs.ts
  packages/odf/utils/storage.ts
  packages/shared/src/constants/common.ts
  packages/shared/src/dropdown/TypeaheadDropdown.tsx
  packages/shared/src/dropdown/index.ts
  packages/shared/src/models/storage.ts
  packages/shared/src/types/common.ts
  packages/shared/src/types/storage.ts
  packages/shared/src/utils/common.ts
  packages/shared/src/utils/storage.ts
Labels: approved, lgtm

#1905 Add CORS create/edit page (S3)
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/buckets-list-page/bucketsListPage.tsx
  packages/odf/components/s3-browser/ca-error/CAErrorMessage.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/CorsFormContents.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/CreateOrEditCorsRule.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/create-cors-rules.scss
  packages/odf/components/s3-browser/create-or-edit-cors-rules/reducer.ts
  packages/odf/components/s3-browser/create-or-edit-cors-rules/useEditCorsRule.ts
  packages/odf/components/s3-browser/create-or-edit-cors-rules/validations.ts
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/CreateOrEditLifecycleRule.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/useEditLifecycleRule.ts
  packages/odf/constants/s3-browser.ts
  packages/odf/utils/s3-browser.ts
  packages/shared/src/constants/common.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/s3/utils.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1908 Add CORS details page (S3)
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/cors-details/CorsDetailsPage.tsx
  packages/odf/utils/s3-browser.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1889 RHSTOR-7003: Disaster recovery UI for Kubevirt VM - Discovered(Standalone)
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/enroll-discovered-application.spec.tsx
  packages/mco/components/discovered-application-wizard/utils/k8s-utils.ts
  packages/mco/components/discovered-application-wizard/wizard-steps/replication-step/replication-selection-helper.tsx
  packages/mco/components/discovered-application-wizard/wizard-steps/replication-step/replication-step.tsx
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal-body.tsx
  packages/mco/components/modals/app-manage-policies/app-manage-policies-modal.tsx
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
  packages/mco/components/modals/app-manage-policies/helper/protection-type-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/helper/replication-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/helper/review-and-assign.tsx
  packages/mco/components/modals/app-manage-policies/helper/select-policy-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/modal-context-viewer.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/discovered-vm-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/virtual-machine-parser.tsx
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/components/modals/app-manage-policies/utils/types.ts
  packages/mco/constants/common.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/hooks/mco-resources.ts
  packages/mco/types/ramen.ts
  packages/shared/src/input-with-requirements/NameInputWithValidation.tsx
  packages/shared/src/input-with-requirements/index.ts
Labels: approved, lgtm, jira/valid-reference

#1911 Fix styling issues due to OCP's PF6 migration (StatusBox and Heading tags)
  cypress/support/pages/app.ts
  packages/ocs/storage-pool/CreateStoragePool.tsx
  packages/odf/components/kms-config/kms-config.tsx
  packages/odf/components/mcg/CreateObjectBucketClaim.tsx
  packages/odf/components/s3-browser/bucket-overview/PageTitle.tsx
  packages/odf/components/s3-browser/create-bucket/CreateBucket.tsx
  packages/odf/components/s3-browser/object-details/ObjectDetailsSidebar.tsx
  packages/shared/src/generic/Loading.tsx
  packages/shared/src/generic/status-box.tsx
  packages/shared/src/heading/page-heading.tsx
  packages/shared/src/style.scss
  packages/shared/src/styles/_common.scss
  packages/shared/src/styles/_status-box.scss
Labels: approved, lgtm

#1920 CI build: Increase network timeout
  Dockerfile.ci
Labels: approved, lgtm

#1913 Syncing latest changes from master for odf-console
  locales/en/plugin__odf-console.json
  packages/ocs/dashboards/object-service/details-card/details-card.tsx
  packages/ocs/dashboards/persistent-internal/details-card.tsx
  packages/ocs/storage-class/sc-form.tsx
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/create-storage-system/create-steps.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.scss
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/create-local-volume-set-step/body.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/create-storage-system.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/mcg-endpoints/pvc-endpoint-type.tsx
  packages/odf/components/s3-browser/buckets-list-page/bucketsListPage.tsx
  packages/odf/components/s3-browser/ca-error/CAErrorMessage.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/CorsFormContents.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/CreateOrEditCorsRule.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/create-cors-rules.scss
  packages/odf/components/s3-browser/create-or-edit-cors-rules/reducer.ts
  packages/odf/components/s3-browser/create-or-edit-cors-rules/useEditCorsRule.ts
  packages/odf/components/s3-browser/create-or-edit-cors-rules/validations.ts
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/CreateOrEditLifecycleRule.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/reducer.ts
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/useEditLifecycleRule.ts
  packages/odf/components/system-list/odf-system-list.tsx
  packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
  packages/odf/components/utils/common-odf-install-el.tsx
  packages/odf/components/utils/common.ts
  packages/odf/constants/common.ts
  packages/odf/constants/lso.ts
  packages/odf/constants/s3-browser.ts
  packages/odf/modals/capacity-autoscaling/capacity-autoscaling-modal.scss
  packages/odf/modals/capacity-autoscaling/capacity-autoscaling-modal.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
  packages/odf/types/common.ts
  packages/odf/utils/ocs.ts
  packages/odf/utils/s3-browser.ts
  packages/odf/utils/storage.ts
  packages/shared/src/constants/common.ts
  packages/shared/src/dropdown/TypeaheadDropdown.tsx
  packages/shared/src/dropdown/index.ts
  packages/shared/src/models/storage.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/types.ts
  packages/shared/src/s3/utils.ts
  packages/shared/src/types/common.ts
  packages/shared/src/types/storage.ts
  packages/shared/src/utils/common.ts
  packages/shared/src/utils/storage.ts
  plugins/odf/console-extensions.json
  plugins/odf/console-plugin.json
Labels: approved, lgtm

#1917 Client plugin: add S3 Object Browser
  README.md
  index.d.ts
  packages/client/package.json
  packages/client/src/components/mcg/index.ts
  packages/odf/components/s3-browser/create-bucket/CreateBucket.tsx
  packages/odf/components/s3-browser/noobaa-context.tsx
  packages/odf/constants/s3-browser.ts
  packages/shared/src/constants/common.ts
  packages/shared/src/global.d.ts
  packages/shared/src/s3/commands.ts
  packages/shared/src/s3/constants.ts
  packages/shared/src/s3/utils.ts
  packages/shared/src/useCustomTranslationHook.ts
  packages/shared/src/utils/common.ts
  plugins/client/console-extensions.json
  plugins/client/dev/s3-forward-proxy.yaml
  tsconfig.json
  webpack.config.ts
Labels: approved, lgtm

#1918 Fix S3 bucket overview routing
  packages/shared/src/utils/Tabs.tsx
Labels: approved, lgtm

#1906 Adding CORS rules list page
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-overview/PermissionsNav.tsx
  packages/odf/components/s3-browser/cors-rules-list/CORSRulesList.tsx
  packages/odf/constants/s3-browser.ts
  packages/odf/modals/s3-browser/delete-corsrules/DeleteCorsRuleModal.tsx
Labels: approved, lgtm

#1919 Adds support for VolumeGroupSnapshotClass in resource distribution pages
  locales/en/plugin__odf-console.json
  packages/odf/components/ResourceDistribution/ResourceDistributionTable.tsx
  packages/odf/features.ts
  packages/odf/modals/ResourceDistributionModal/ResourceDistributionModal.spec.tsx
  packages/odf/modals/ResourceDistributionModal/ResourceDistributionModal.tsx
  packages/shared/src/models/common.ts
  packages/shared/src/types/k8s.ts
  packages/shared/src/types/storage.ts
Labels: approved, lgtm

#1899 RHSTOR-7003: PVC and VM label update for DR protection
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
  packages/mco/components/modals/app-manage-policies/helper/replication-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/helper/review-and-assign.tsx
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/parsers/application-set-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/parsers/discovered-vm-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/subscription-parser.spec.tsx
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/acm.ts
  packages/mco/utils/managed-cluster-action.ts
  packages/mco/utils/managed-cluster-view.ts
  packages/shared/src/models/acm.ts
  packages/shared/src/utils/error/http-error.ts
Labels: approved, lgtm, jira/valid-reference

#1916 RHSTOR-7186: DR Status popover for virtual machine list page.
  locales/en/plugin__odf-console.json
  packages/mco/components/dr-status-popover/acm-column-callback.tsx
  packages/mco/components/dr-status-popover/dr-status-popover.tsx
  packages/mco/components/dr-status-popover/parsers/virtualmachine-parser.tsx
  packages/mco/constants/doc.tsx
  plugins/mco/console-extensions.json
Labels: approved, lgtm, jira/valid-reference

#1921 Add actions dropdown to CORS details (S3)
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/bucket-overview/bucket-overview.scss
  packages/odf/components/s3-browser/cors-details/CorsDetailsPage.tsx
  packages/odf/components/s3-browser/cors-rules-list/CORSRulesList.tsx
  packages/odf/components/s3-browser/create-or-edit-cors-rules/CreateOrEditCorsRule.tsx
  packages/odf/components/s3-browser/create-or-edit-lifecycle-rules/CreateOrEditLifecycleRule.tsx
  packages/odf/modals/s3-browser/delete-corsrules/DeleteCorsRuleModal.tsx
  packages/odf/modals/s3-browser/delete-lifecyclerules/DeleteLifecycleRuleModal.tsx
Labels: approved, lgtm

#1914 Storage Cluster modals fix: re-render on cluster change
  cypress/tests/add-capacity.spec.ts
  packages/odf/components/actions/csv-actions.ts
  packages/odf/components/alerts/alert-action-path.tsx
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/modals/capacity-autoscaling/capacity-autoscaling-modal.tsx
  packages/odf/modals/configure-performance/configure-performance-modal.tsx
  packages/shared/src/modals/common.ts
Labels: approved, lgtm

#1903 add modal to view consistency groups for managed applications
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/helper/consistency-groups.tsx
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/modal-context-viewer.tsx
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/components/modals/app-manage-policies/volume-consistency-group-view.tsx
  packages/mco/components/protected-applications/components.tsx
  packages/mco/components/protected-applications/protected-apps-list-page.spec.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/types/ramen.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/shared/src/constants/common.ts
Labels: approved, lgtm

#1909 RHSTOR-7112: Disaster recovery UI for Kubevirt VM - Discovered(Shared)
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/wizard-steps/replication-step/replication-selection-helper.tsx
  packages/mco/components/dr-status-popover/parsers/virtualmachine-parser.tsx
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/protection-type-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/helper/replication-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/helper/shared-virtual-machine-table.tsx
  packages/mco/components/modals/app-manage-policies/modal-context-viewer.tsx
  packages/mco/components/modals/app-manage-policies/parsers/discovered-vm-parser.tsx
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/components/modals/app-manage-policies/utils/types.ts
  packages/shared/src/dropdown/StaticDropdown.tsx
  packages/shared/src/hooks/select-list.ts
  packages/shared/src/table/selectable-table.tsx
  packages/shared/src/table/table.tsx
  packages/shared/src/utils/RequestSizeInput.tsx
  packages/shared/src/utils/table.ts
Labels: approved, lgtm, jira/valid-reference

#1922 Unit tests for Capacity Autoscaling
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.spec.tsx
Labels: approved, lgtm

#1923 RHSTOR-7113: Disable DR for Standalone and Shared VMs
  locales/en/plugin__odf-console.json
  packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/helper/replication-wizard-content.tsx
  packages/mco/components/modals/app-manage-policies/manage-policy-view.tsx
  packages/mco/components/modals/app-manage-policies/modal-context-viewer.tsx
  packages/mco/components/modals/app-manage-policies/parsers/discovered-vm-parser.tsx
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/reducer.ts
  packages/mco/components/modals/app-manage-policies/utils/types.ts
  packages/mco/utils/disaster-recovery.tsx
  packages/mco/utils/managed-cluster-action.ts
Labels: approved, lgtm, jira/valid-reference

#1925 Removes support for data path separation feature
  packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/configure.tsx
Labels: approved, lgtm

#1887 Add storageclass validations to policy creation
  locales/en/plugin__odf-console.json
  packages/mco/components/create-dr-policy/create-dr-policy.spec.tsx
  packages/mco/components/create-dr-policy/selected-cluster-validator.tsx
  packages/mco/constants/disaster-recovery.ts
  packages/mco/utils/acm-search-queries.ts
Labels: approved, lgtm

#1928 Capacity Autoscaling modal: show 'Failed' state timestamp & message.
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.spec.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-autoscaling.tsx
  packages/odf/components/create-storage-system/footer.tsx
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/constants/common.ts
  packages/odf/modals/add-capacity/add-capacity-modal.tsx
  packages/odf/modals/capacity-autoscaling/capacity-autoscaling-modal.tsx
  packages/shared/src/constants/common.ts
  packages/shared/src/dropdown/TypeaheadDropdown.tsx
  packages/shared/src/utils/storage.spec.ts
  packages/shared/src/utils/storage.ts
Labels: approved, lgtm
