Repository red-hat-storage/odf-console, pull requests merged in 2025-06, with the labels that each got.

#2100 Adds support for default virtualization storage class
  locales/en/plugin__odf-console.json
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/backing-storage-step.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/backing-storage-step/set-virtualize-sc-default.tsx
  packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
  packages/odf/components/create-storage-system/payloads.ts
  packages/odf/components/create-storage-system/reducer.ts
  packages/odf/components/utils/common.ts
  packages/shared/src/types/storage.ts
Labels: approved, lgtm

#1934 Add provision to recipe parameters while enrolling applicaiton
  locales/en/plugin__odf-console.json
  packages/mco/components/discovered-application-wizard/utils/k8s-utils.ts
  packages/mco/components/discovered-application-wizard/utils/reducer.ts
  packages/mco/components/discovered-application-wizard/wizard-steps/configuration-step/recipe-parameter-input.tsx
  packages/mco/components/discovered-application-wizard/wizard-steps/configuration-step/recipe-selection.tsx
  packages/mco/components/discovered-application-wizard/wizard-steps/review-step/review-step.tsx
Labels: approved, lgtm

#2113 Fix S3 upload issue
  locales/en/plugin__odf-console.json
  packages/odf/components/s3-browser/upload-objects/upload-component/FileUploadComponent.tsx
Labels: approved, lgtm

#2118 i18n: sort keys
  i18next-parser.config.js
  locales/en/plugin__odf-console.json
Labels: approved, lgtm

#2116 Fetch primary cluster for different DRPC phases
  locales/en/plugin__odf-console.json
  packages/mco/components/dr-status-popover/dr-status-popover.tsx
  packages/mco/components/dr-status-popover/parsers/applicationset-parser.tsx
  packages/mco/components/dr-status-popover/parsers/discovered-parser.tsx
  packages/mco/components/dr-status-popover/parsers/subscription-parser.tsx
  packages/mco/components/mco-dashboard/disaster-recovery/parsers/discovered-parser.tsx
  packages/mco/components/modals/app-failover-relocate/parser/discovered-application-parser.tsx
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/components/protected-applications/components.tsx
  packages/mco/components/protected-applications/list-page.tsx
  packages/mco/components/protected-applications/protected-apps-list-page.spec.tsx
  packages/mco/utils/disaster-recovery.tsx
Labels: approved, lgtm

#2129 A11y lint: enable the disabled rules & fix related issues.
  .eslintrc.js
  locales/en/plugin__odf-console.json
  packages/ocs/storage-class/sc-form.tsx
  packages/ocs/storage-pool/body.scss
  packages/ocs/storage-pool/body.tsx
  packages/odf/components/s3-browser/bucket-policy/BucketPolicy.tsx
  packages/odf/components/topology/TopBar/TopologyNavigation.scss
  packages/odf/components/topology/TopBar/TopologyNavigation.tsx
  packages/odf/components/topology/TopBar/TopologySearch.scss
  packages/odf/components/topology/TopBar/TopologySearch.tsx
  packages/odf/components/topology/Topology.tsx
  packages/odf/components/topology/topology.scss
  packages/shared/src/alert/AlertsPanel.tsx
  packages/shared/src/alert/alerts.scss
  packages/shared/src/modals/EditLabelModal.tsx
  packages/shared/src/modals/Selector.scss
  packages/shared/src/modals/Selector.tsx
  stylelint.config.js
Labels: approved, lgtm

#2107 RHSTOR-7460: Upgrade packages in both package.json files
  .github/workflows/frontend-build.yml
  Dockerfile.ci
  package.json
  packages/shared/package.json
  yarn.lock
Labels: approved, lgtm, jira/valid-reference

#2131 Fix BlockPool dashboard - mirroring card
  packages/ocs/dashboards/block-pool/mirroring-card.tsx
Labels: approved, lgtm

#2128 Fix DR Status issue for discovered apps in Virtual Machine page
  packages/mco/components/dr-status-popover/parsers/virtualmachine-parser.tsx
  packages/mco/components/modals/app-manage-policies/parsers/discovered-vm-parser.tsx
  packages/mco/components/modals/app-manage-policies/utils/k8s-utils.ts
  packages/mco/components/modals/app-manage-policies/utils/parser-utils.ts
  packages/mco/constants/common.ts
Labels: approved, lgtm

#2059 DFBUGS-1837: [release-4.18] Client plugin: Hide Object Storage
  plugins/client/console-extensions.json
  plugins/client/console-plugin.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
